"""
Django settings for llm_monitor project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1^ql#^w)r=70(!w2s-m9(y)y8ux!0yp3wniaeylu^z5u#pgy8q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS - can be comma-separated list in .env
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver', cast=lambda v: [s.strip() for s in v.split(',')] if v else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'authentication',
    'domains',
    'keywords',
    'prompts',
    'alerts',
    'competitors.apps.CompetitorsConfig',
    'topics',
    'analytics',
    'integrations.apps.IntegrationsConfig',
    'reports',
    'misinformation',
    'content',
    'chat',
    'seo_rankings',
]
# Site URL for building absolute links in emails
SITE_URL = config('SITE_URL', default='http://localhost:8080')

# CORS allowed origins - can be comma-separated list in .env
# Default includes common development ports
CORS_ALLOWED_ORIGINS_ENV = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080,http://localhost:8081,http://127.0.0.1:8081',
    cast=lambda v: [s.strip() for s in v.split(',')] if v else []
)

# Combine CORS_ALLOWED_ORIGINS from env with SITE_URL (if not already present)
CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS_ENV + ([SITE_URL] if SITE_URL and SITE_URL not in CORS_ALLOWED_ORIGINS_ENV else [])))

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llm_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llm_monitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='llm_monitor'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default='Monit@2025$'),
        'HOST': config('DB_HOST', default='64.227.190.42'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'gssencmode': 'disable',  # Disable GSSAPI to prevent macOS fork crashes
            'connect_timeout': 10,
            'keepalives': 1,  # Enable TCP keepalives
            'keepalives_idle': 30,  # Seconds before sending keepalive probes
            'keepalives_interval': 10,  # Seconds between keepalive probes
            'keepalives_count': 5,  # Number of keepalives before giving up
        },
        'CONN_MAX_AGE': 300,  # Reduced to 5 minutes to prevent stale connections
        'CONN_HEALTH_CHECKS': True,  # Django 4.1+ health checks before using connection
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded reference documents, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'authentication.Account'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'llm_monitor.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 20  # Default page size (can be overridden with ?page_size= up to 1000)
}

# CORS settings
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for development
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in debug mode
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# SSL/TLS Configuration - Disabled for development
# Set USE_TLS=True in .env to enable SSL (requires SSL certificates)
USE_TLS = config('USE_TLS', default=False, cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# ==================== EMAIL CONFIGURATION (MAILGUN HTTP API) ====================

# Mailgun HTTP API Configuration
MAILGUN_API_KEY = config('MAILGUN_API_KEY', default='')
MAILGUN_DOMAIN = config('MAILGUN_DOMAIN', default='')

# Sender Email
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='LLM Monitor <noreply@sandbox.mailgun.org>'
)

# Frontend URL for email links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8080')

# Email timeout (seconds)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# ==================== END EMAIL CONFIGURATION ====================

# Engine (processing) service configuration
ENGINE_API_URL = config('ENGINE_API_URL', default='http://localhost:8001')

# OpenAI API Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY', default=None)

# Google Gemini API Configuration (for AI-powered features)
GOOGLE_GEMINI_API_KEY = config('GOOGLE_GEMINI_API_KEY', default=None)
# Gemini model name — single source of truth so a model retirement (Google returns
# 404 "model not found, use a newer model") is a one-line env change, not a code
# edit across every call site. Mirrors the engine's GEMINI_MODEL setting. Override
# per-environment via the GEMINI_MODEL env var if a key only supports a specific model.
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-2.5-flash')

# ScrapingDog API Configuration (still used by misinformation crawler & domains/views.py — /scrape endpoint)
SCRAPINGDOG_API_KEY = config('SCRAPINGDOG_API_KEY', default=None)

# DataBlue API Configuration (SEO keyword ranking / SERP — /v1/data/google/search)
DATABLUE_API_KEY = config('DATABLUE_API_KEY', default='')
DATABLUE_NUM_RESULTS = config('DATABLUE_NUM_RESULTS', default=50, cast=int)
DATABLUE_CONCURRENCY = config('DATABLUE_CONCURRENCY', default=100, cast=int)
DATABLUE_TIMEOUT = config('DATABLUE_TIMEOUT', default=60, cast=int)

# Google PageSpeed Insights API Configuration (for Core Web Vitals & Performance)
GOOGLE_PAGESPEED_API_KEY = config('GOOGLE_PAGESPEED_API_KEY', default=None)

# Moz API Configuration (for Website Authority - free tier: 2,500 rows/month)
MOZ_ACCESS_ID = config('MOZ_ACCESS_ID', default=None)
MOZ_SECRET_KEY = config('MOZ_SECRET_KEY', default=None)

# LLM platforms to hide from the AI Visibility Excel export.
# The engine still calls these LLMs and stores their data — only the export
# display omits them (rows and Mentions/Citations totals exclude their share).
# Comma-separated. Match values stored on snapshots: "ChatGPT", "Google Gemini",
# "Perplexity", "Claude", "Grok", "DeepSeek".
AI_VISIBILITY_HIDDEN_PLATFORMS = [
    s.strip() for s in config(
        'AI_VISIBILITY_HIDDEN_PLATFORMS',
        default='Perplexity,Grok,DeepSeek',
    ).split(',') if s.strip()
]

# DataForSEO API Configuration (for Backlink Portfolio in dashboard export)
DATAFORSEO_LOGIN = config('DATAFORSEO_LOGIN', default=None)
DATAFORSEO_PASSWORD = config('DATAFORSEO_PASSWORD', default=None)
# When True, hit sandbox.dataforseo.com instead of api.dataforseo.com. The
# sandbox is free but returns fixed mock data (same numbers for every brand),
# so it's useful before the paid Backlinks subscription is activated. Flip to
# False once the live Backlinks plan is active — same code path.
DATAFORSEO_USE_SANDBOX = config('DATAFORSEO_USE_SANDBOX', default=False, cast=bool)

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='1080254283876-0o3ur4sr7ii1kh4ugaij4c7n1ptibn4j.apps.googleusercontent.com')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='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')
# GOOGLE_OAUTH_REDIRECT_URI - can be set in .env, or will be constructed from SITE_URL
GOOGLE_OAUTH_REDIRECT_URI = config('GOOGLE_OAUTH_REDIRECT_URI', default=None)
if not GOOGLE_OAUTH_REDIRECT_URI:
    # Auto-construct from SITE_URL if not explicitly set
    GOOGLE_OAUTH_REDIRECT_URI = f"{SITE_URL.rstrip('/')}/integrations/google/callback/"

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    # Increased from 60 minutes to 8 hours to reduce frequent session timeouts
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    # Increased from 7 days to 30 days for better user experience
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR.parent / 'logs' / 'backend.log',
            'maxBytes': 1024 * 1024 * 50,  # 50MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'content': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'domains': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
