"""
Django settings for llm_monitor project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import sys
if str(BASE_DIR.parent) not in sys.path:
    sys.path.append(str(BASE_DIR.parent))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1^ql#^w)r=70(!w2s-m9(y)y8ux!0yp3wniaeylu^z5u#pgy8q')

# Secret used to encrypt/decrypt per-organisation BYOK API keys at rest.
# Defaults to SECRET_KEY so backend encryption/decryption is UNCHANGED from before
# this feature (any keys already stored keep decrypting). MUST be identical in the
# engine for the engine to decrypt; if you run a custom SECRET_KEY in production,
# set API_KEY_ENCRYPTION_SECRET to that same value in BOTH backend and engine env.
API_KEY_ENCRYPTION_SECRET = config('API_KEY_ENCRYPTION_SECRET', default=SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS - can be comma-separated list in .env
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver', cast=lambda v: [s.strip() for s in v.split(',')] if v else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'authentication',
    'domains',
    'keywords',
    'prompts',
    'alerts',
    'competitors.apps.CompetitorsConfig',
    'topics',
    'analytics',
    'integrations.apps.IntegrationsConfig',
    'reports',
    'misinformation',
    'content',
    'chat',
    'seo_rankings',
    'audits',
]
# Site URL for building absolute links in emails
SITE_URL = config('SITE_URL', default='http://localhost:8080')

# CORS allowed origins - can be comma-separated list in .env
# Default includes common development ports
CORS_ALLOWED_ORIGINS_ENV = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080,http://localhost:8081,http://127.0.0.1:8081',
    cast=lambda v: [s.strip() for s in v.split(',')] if v else []
)

# Combine CORS_ALLOWED_ORIGINS from env with SITE_URL (if not already present)
CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS_ENV + ([SITE_URL] if SITE_URL and SITE_URL not in CORS_ALLOWED_ORIGINS_ENV else [])))

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'llm_monitor.middleware.ThreadLocalRequestMiddleware',
    # Fail-closed domain-access backstop; must run after auth middleware so a
    # session user is populated, and it resolves JWT bearer tokens itself.
    'llm_monitor.middleware_domain_access.DomainAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llm_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llm_monitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='llm_monitor'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='9486'),   # or your actual local postgres password
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'gssencmode': 'disable',
            'connect_timeout': 10,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
        'CONN_MAX_AGE': 300,
        'CONN_HEALTH_CHECKS': True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded reference documents, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'authentication.Account'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Service API keys (Authorization: Api-Key pmxk_...) resolve to a
        # hidden org service account with role 'client' — org-wide read-only.
        'authentication.api_key_auth.ApiKeyAuthentication',
        # Status-aware JWT: rejects tokens for suspended/disabled accounts on
        # every request (immediate lockout, not at token expiry).
        'authentication.jwt_auth.StatusCheckingJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'llm_monitor.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 20  # Default page size (can be overridden with ?page_size= up to 1000)
}

# CORS settings
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for development
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in debug mode
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# SSL/TLS Configuration - Disabled for development
# Set USE_TLS=True in .env to enable SSL (requires SSL certificates)
USE_TLS = config('USE_TLS', default=False, cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# ==================== EMAIL CONFIGURATION (MAILGUN HTTP API) ====================

# Mailgun HTTP API Configuration
MAILGUN_API_KEY = config('MAILGUN_API_KEY', default='')
MAILGUN_DOMAIN = config('MAILGUN_DOMAIN', default='')

# Sender Email
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='Promptmaxx App <noreply@sandbox.mailgun.org>'
)

# Frontend URL for email links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8080')

# Email timeout (seconds)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# ==================== END EMAIL CONFIGURATION ====================

# Engine (processing) service configuration
ENGINE_API_URL = config('ENGINE_API_URL', default='http://localhost:8001')

# OpenAI API Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY', default=None)

# Anthropic (Claude) API Configuration. Accept either ANTHROPIC_API_KEY (engine's
# canonical name) or the backend's historical CLAUDE_API_KEY env var, so the shared
# api_key_service .env fallback can resolve Claude in the backend process too.
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default=config('CLAUDE_API_KEY', default=None))

# ============== OPENROUTER (ChatGPT + Claude + Perplexity transport) ==============
# Every Claude call — mention tracking and content generation — and every
# ChatGPT and Perplexity call is routed through OpenRouter's OpenAI-compatible
# endpoint (Claude via core/openrouter_client.py). OPENAI_API_KEY and
# ANTHROPIC_API_KEY above are no longer used by those paths, and no
# PERPLEXITY_API_KEY is needed. Mirrors the engine's OPENROUTER_* settings;
# keep the two in sync.
OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default=None)
OPENROUTER_BASE_URL = config('OPENROUTER_BASE_URL', default='https://openrouter.ai/api/v1')
OPENROUTER_SITE_URL = config('OPENROUTER_SITE_URL', default=None)
OPENROUTER_SITE_TITLE = config('OPENROUTER_SITE_TITLE', default=None)
# OpenRouter model slug, not an Anthropic model id.
ANTHROPIC_MODEL = config('ANTHROPIC_MODEL', default='anthropic/claude-sonnet-5')
# Likewise an OpenRouter slug, NOT the bare 'sonar' the direct Perplexity API
# takes. Mirrors the engine's PERPLEXITY_MODEL; keep the two in sync.
PERPLEXITY_MODEL = config('PERPLEXITY_MODEL', default='perplexity/sonar')
# Likewise an OpenRouter slug, NOT the bare 'gpt-4o' the direct OpenAI API takes.
# Used by the AI Mention Check's ChatGPT engine. Deliberately the SAME slug as
# OPENROUTER_INTERNAL_MODEL below — one model for every call — and kept as its
# own setting only so the two can be split again from .env. gpt-5-mini is a
# REASONING model: any call site that caps max_tokens must leave room for the
# ~800-1000 hidden reasoning tokens it spends before emitting text.
# Mirrors the engine's OPENAI_CHATGPT_MODEL.
OPENAI_CHATGPT_MODEL = config('OPENAI_CHATGPT_MODEL', default='openai/gpt-5-mini')
# Web search for that call is answered by OpenRouter's `web` plugin rather than
# OpenAI's native tool. Same on/off switch, different search backend.
OPENAI_CHATGPT_WEB_SEARCH = config('OPENAI_CHATGPT_WEB_SEARCH', default=True, cast=bool)
# Every LLM call — internal support work and the AI Mention Check alike — runs
# through OpenRouter on this one slug.
OPENROUTER_INTERNAL_MODEL = config('OPENROUTER_INTERNAL_MODEL', default='openai/gpt-5-mini')

# ============== IMAGE GENERATION (content editor) ==============
# Two stages, both over OpenRouter (see content/image_generation.py).
#
# Stage 1 writes the prompt with a TEXT model — free models work fine here and
# it defaults to whatever OPENROUTER_INTERNAL_MODEL is set to.
#
# Stage 2 renders pixels with an IMAGE model. NOTE: OpenRouter has NO free
# image-output models — every one of them is paid — so this stage always costs
# something. The default is the cheapest available.
IMAGE_PROMPT_TEXT_MODEL = config('IMAGE_PROMPT_TEXT_MODEL', default=None)
IMAGE_RENDER_MODEL = config('IMAGE_RENDER_MODEL', default='google/gemini-2.5-flash-image')

# Content generation output-token caps (configurable per environment).
#   CONTENT_MAX_TOKENS      - hard ceiling for a single article on the PAID model
#                             (Sonnet 4.5 supports up to 64000).
#   CONTENT_FREE_MAX_TOKENS - ceiling applied on the FREE-model fallback, which
#                             has a smaller output limit; keeps large requests
#                             from erroring at $0 balance.
# Both have safe defaults, so an environment without these keys is unaffected.
CONTENT_MAX_TOKENS = config('CONTENT_MAX_TOKENS', default=64000, cast=int)
CONTENT_FREE_MAX_TOKENS = config('CONTENT_FREE_MAX_TOKENS', default=8192, cast=int)

# Multi-model humanisation. The guarded score-refine loop rotates each refine
# pass through these models (comma-separated slugs) instead of always using the
# paid Claude model — a different model per pass breaks the single-model writing
# pattern that AI detectors key on. Empty/unset uses the generator's built-in
# default (gpt-5-mini, gemini-2.5-flash). Every model still uses the paid-first
# → free-fallback path, so an unavailable slug never fails the job.
HUMANISE_REFINE_MODELS = config('HUMANISE_REFINE_MODELS', default='')

# Stronger-humanisation layer. When True (default) the Pass-1 humanise prompt
# gains extra natural-voice rules (contractions, varied openings, concreteness)
# chosen to NOT conflict with the existing rules. Set False to revert to the
# exact original prompt if it ever hurts tone — no code change, no deploy.
HUMANISE_STRONG_MODE = config('HUMANISE_STRONG_MODE', default=True, cast=bool)

# Google Gemini API Configuration (for AI-powered features)
GOOGLE_GEMINI_API_KEY = config('GOOGLE_GEMINI_API_KEY', default=None)
# Gemini model name — single source of truth so a model retirement (Google returns
# 404 "model not found, use a newer model") is a one-line env change, not a code
# edit across every call site. Mirrors the engine's GEMINI_MODEL setting. Override
# per-environment via the GEMINI_MODEL env var if a key only supports a specific model.
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-flash-latest')

# ---------------------------------------------------------------------------
# Gemini transport for the BACKEND's helper calls (brand niches, semantic
# keywords). The ENGINE was migrated to Vertex; these helpers were left on the
# AI Studio API-key path, which is why adding a domain broke once BYOK moved off
# Google — the per-org key was a placeholder and the AI Studio project's prepaid
# credits are depleted. Vertex authenticates with a service account instead, so
# no API key is involved at all.
#
# Same variable names as engine/llm_monitor_engine/settings.py, so one .env
# entry per tree configures both identically.
# ---------------------------------------------------------------------------
# Transport for the BACKEND's Gemini helper calls only (brand niches, semantic
# keywords). Deliberately a SEPARATE name from the engine's GEMINI_BACKEND:
# the engine's setting governs MEASURED calls, where the transport determines
# whether we are really observing what a Gemini user is told. These helpers are
# internal analysis, so the transport is purely an operational choice.
#   openrouter -> OPENROUTER_GEMINI_MODEL through the internal client (default)
#   vertex     -> service account, bills VERTEX_PROJECT
#   aistudio   -> google.generativeai with a BYOK/.env API key
GEMINI_HELPER_BACKEND = config('GEMINI_HELPER_BACKEND', default='openrouter')
OPENROUTER_GEMINI_MODEL = config('OPENROUTER_GEMINI_MODEL', default='google/gemini-2.5-flash')

GEMINI_BACKEND = config('GEMINI_BACKEND', default='aistudio')
VERTEX_PROJECT = config('VERTEX_PROJECT', default=None)
VERTEX_LOCATION = config('VERTEX_LOCATION', default='us-central1')
VERTEX_GEMINI_MODEL = config('VERTEX_GEMINI_MODEL', default='gemini-2.5-flash')

# Application Default Credentials are read from the PROCESS environment, not
# from Django settings, so a .env entry has to be exported explicitly.
import os as _os
_VERTEX_CREDENTIALS = config('GOOGLE_APPLICATION_CREDENTIALS', default=None)
if _VERTEX_CREDENTIALS:
    _os.environ.setdefault('GOOGLE_APPLICATION_CREDENTIALS', _VERTEX_CREDENTIALS)

# ScrapingDog API Configuration (still used by misinformation crawler & domains/views.py — /scrape endpoint)
SCRAPINGDOG_API_KEY = config('SCRAPINGDOG_API_KEY', default=None)

# DataBlue API Configuration (SEO keyword ranking / SERP — /v1/data/google/serp)
DATABLUE_API_KEY = config('DATABLUE_API_KEY', default='')
DATABLUE_NUM_RESULTS = config('DATABLUE_NUM_RESULTS', default=50, cast=int)
DATABLUE_CONCURRENCY = config('DATABLUE_CONCURRENCY', default=100, cast=int)
DATABLUE_TIMEOUT = config('DATABLUE_TIMEOUT', default=60, cast=int)
# /v1/data/google/serp endpoint (GET + query params). URL is overridable; PLATFORM
# is the default device when a keyword doesn't specify one; PAGES (1-5) overrides
# the num_results→pages derive (each page ~10 results and is billed separately);
# GOOGLE_DOMAIN forces a Google domain (else DataBlue auto-picks by country);
# ADVANCED=false uses the cheaper organic-focused mode (1 credit/page vs 2).
DATABLUE_API_URL = config('DATABLUE_API_URL', default='https://api.datablue.dev/v1/data/google/serp')
DATABLUE_PLATFORM = config('DATABLUE_PLATFORM', default='desktop')
DATABLUE_PAGES = config('DATABLUE_PAGES', default=0, cast=int)  # 0 = derive from NUM_RESULTS
DATABLUE_GOOGLE_DOMAIN = config('DATABLUE_GOOGLE_DOMAIN', default='')
DATABLUE_ADVANCED = config('DATABLUE_ADVANCED', default=False, cast=bool)

# DataBlue web scrape (/v1/scrape, POST) — second-opinion link checking for the
# misinformation scan. Only reached when the free HEAD check is inconclusive
# (403 / 429 / timeout / connection error), so it bills on a fraction of URLs.
# Set MISINFO_DATABLUE_FALLBACK=False to disable and keep the HEAD-only verdict.
MISINFO_DATABLUE_FALLBACK = config('MISINFO_DATABLUE_FALLBACK', default=True, cast=bool)
DATABLUE_SCRAPE_URL = config('DATABLUE_SCRAPE_URL', default='https://api.datablue.dev/v1/scrape')
DATABLUE_SCRAPE_TIMEOUT = config('DATABLUE_SCRAPE_TIMEOUT', default=30, cast=int)
# Request body field holding the target URL. "url" is what /v1/scrape expects
# (verified against the live endpoint); overridable if that ever changes.
DATABLUE_SCRAPE_URL_FIELD = config('DATABLUE_SCRAPE_URL_FIELD', default='url')

# Google PageSpeed Insights API Configuration (for Core Web Vitals & Performance)
GOOGLE_PAGESPEED_API_KEY = config('GOOGLE_PAGESPEED_API_KEY', default=None)

# Domain Overview / GEO audit tuning.
# AVI_PROMPTS_PER_STAGE: funnel prompts generated per TOFU/MOFU/BOFU stage on a domain's
# FIRST audit. Higher = broader category coverage / more statistical rigor, at a linear
# BYOK cost (prompts x engines live LLM calls). Already-persisted prompt sets keep their
# original size so the GEO trend stays apples-to-apples.
AVI_PROMPTS_PER_STAGE = config('AVI_PROMPTS_PER_STAGE', default=3, cast=int)
# Process-wide cap on concurrent background AVI jobs (async run mode). Bounds LLM fan-out
# and stops heavy runs from exhausting web workers; the legacy backend has no Celery, so
# this runs in-process. Excess jobs queue.
AVI_JOB_WORKERS = config('AVI_JOB_WORKERS', default=2, cast=int)

# ==================== AUDIT ENGINE (public URL -> GEO + SEO audit) ====================
# Master switch. Off by default so a deploy that carries the audit code changes
# nothing until this is flipped in .env; the public create endpoint answers 503
# and the engine task refuses to run while it is False. Also the rollback lever.
AUDIT_ENGINE_ENABLED = config('AUDIT_ENGINE_ENABLED', default=False, cast=bool)
# How long a public report link resolves. Claimed audits never expire.
AUDIT_PUBLIC_TTL_DAYS = config('AUDIT_PUBLIC_TTL_DAYS', default=30, cast=int)
# Size of one audit. Each prompt is asked ONCE per engine, so cost scales as
# AUDIT_PROMPT_COUNT x len(AUDIT_ENGINES) live LLM calls per audit.
AUDIT_PROMPT_COUNT = config('AUDIT_PROMPT_COUNT', default=12, cast=int)
# How many times each prompt is asked on each engine. 1 = a directional
# snapshot (the free public audit); 3+ turns single answers into rates and
# multiplies the LLM cost by the same factor.
AUDIT_RUNS_PER_PROMPT = config('AUDIT_RUNS_PER_PROMPT', default=1, cast=int)
# Provider keys as client_factory knows them: openai, gemini, anthropic,
# perplexity, xai, deepseek.
AUDIT_ENGINES = [
    s.strip() for s in config(
        'AUDIT_ENGINES', default='openai,gemini,anthropic,perplexity',
    ).split(',') if s.strip()
]
# The SEO half (keyword discovery + SERP fetch) spends DataBlue/DataForSEO
# quota; kept behind its own flag so GEO-only audits can ship first.
AUDIT_SEO_ENABLED = config('AUDIT_SEO_ENABLED', default=False, cast=bool)

# Where a visitor who arrived from the landing page is sent back to when they
# leave the report. Empty means no back link is shown — the browser's own back
# button still works, this is the explicit way out.
AUDIT_LANDING_URL = config('AUDIT_LANDING_URL', default='')
AUDIT_KEYWORD_COUNT = config('AUDIT_KEYWORD_COUNT', default=50, cast=int)
# The crawl stage (Findable pillar): plain-HTTP sample of the site's own pages
# for schema, bylines, citations and dates. No paid API. Time-boxed so a slow
# site cannot stall an audit; off = the four Findable measures stay "not measured".
AUDIT_CRAWL_ENABLED = config('AUDIT_CRAWL_ENABLED', default=True, cast=bool)
AUDIT_CRAWL_PAGES = config('AUDIT_CRAWL_PAGES', default=20, cast=int)
AUDIT_CRAWL_BUDGET_SECONDS = config('AUDIT_CRAWL_BUDGET_SECONDS', default=60, cast=int)
# Brand narrative: one internal LLM call over the answers that name the brand
# (how it is framed, which descriptors appear / are missing, tone per engine).
AUDIT_NARRATIVE_ENABLED = config('AUDIT_NARRATIVE_ENABLED', default=True, cast=bool)
# Executive summary: one internal LLM call over a numbers-only digest of the
# report (headline, five key findings, section intros). Off = a deterministic
# rules-based summary is used instead; the section always exists.
AUDIT_SUMMARY_ENABLED = config('AUDIT_SUMMARY_ENABLED', default=True, cast=bool)
# On claim, create the new project's prompt groups from the audit's prompts so
# tracking starts with the questions the audit measured (Day 0). The groups
# start in INIT and the engine runs them like any newly added prompts.
AUDIT_CLAIM_SEEDS_PROMPTS = config('AUDIT_CLAIM_SEEDS_PROMPTS', default=True, cast=bool)
# Abuse limits for the public endpoint: same host at most once per window,
# per-IP daily cap, and a global daily cap. All three are cheap DB counts.
AUDIT_REPEAT_HOURS = config('AUDIT_REPEAT_HOURS', default=24, cast=int)
AUDIT_PER_IP_DAILY = config('AUDIT_PER_IP_DAILY', default=3, cast=int)
AUDIT_GLOBAL_DAILY = config('AUDIT_GLOBAL_DAILY', default=50, cast=int)
# Lead alerts. Comma-separated team addresses; empty = no alerts. The engine
# mails "new lead" on publish; the backend mails "claimed" and "warm" (an
# unclaimed landing-page report opened this many times).
AUDIT_LEAD_ALERT_EMAILS = config('AUDIT_LEAD_ALERT_EMAILS', default='')
AUDIT_WARM_LEAD_OPENS = config('AUDIT_WARM_LEAD_OPENS', default=5, cast=int)

# Moz API Configuration (for Website Authority - free tier: 2,500 rows/month)
MOZ_ACCESS_ID = config('MOZ_ACCESS_ID', default=None)
MOZ_SECRET_KEY = config('MOZ_SECRET_KEY', default=None)

# LLM platforms to hide from the AI Visibility Excel export.
# The engine still calls these LLMs and stores their data — only the export
# display omits them (rows and Mentions/Citations totals exclude their share).
# Comma-separated. Match values stored on snapshots: "ChatGPT", "Google Gemini",
# "Perplexity", "Claude", "Grok", "DeepSeek".
AI_VISIBILITY_HIDDEN_PLATFORMS = [
    s.strip() for s in config(
        'AI_VISIBILITY_HIDDEN_PLATFORMS',
        default='Perplexity,Grok,DeepSeek',
    ).split(',') if s.strip()
]

# LLM providers whose per-organisation key is actually consulted at query time.
#
# ChatGPT, Claude and Perplexity all run through OpenRouter now (see
# OPENROUTER_ROUTED in engine/core/services/api_key_service.py), so the single
# "OpenRouter" entry is the credential for all three — their own per-provider
# keys are never read. xAI and DeepSeek are not in ENABLED_PLATFORMS. Only the
# providers listed here are offered in Organization Settings, so the page
# cannot show a key as "Connected" when nothing would ever use it.
BYOK_PROVIDERS = config(
    'BYOK_PROVIDERS',
    default='openrouter,gemini',
    cast=lambda v: [p.strip() for p in v.split(',') if p.strip()],
)

# Billing — accounts allowed to see every organisation's charges consolidated,
# rather than only their own. Comma-separated emails, matched case-insensitively.
# Kept in config so the list can change without a deploy; everyone else is
# restricted to their own organisation by _billing_regions.
BILLING_ALL_ORG_EMAILS = config('BILLING_ALL_ORG_EMAILS', default='aarun@hitasoft.com')

# DataForSEO API Configuration (for Backlink Portfolio in dashboard export)
DATAFORSEO_LOGIN = config('DATAFORSEO_LOGIN', default=None)
DATAFORSEO_PASSWORD = config('DATAFORSEO_PASSWORD', default=None)
# When True, hit sandbox.dataforseo.com instead of api.dataforseo.com. The
# sandbox is free but returns fixed mock data (same numbers for every brand),
# so it's useful before the paid Backlinks subscription is activated. Flip to
# False once the live Backlinks plan is active — same code path.
DATAFORSEO_USE_SANDBOX = config('DATAFORSEO_USE_SANDBOX', default=False, cast=bool)

# Backlinks: allow a project with NO existing data to be pulled for the first
# time. Off by default — every first pull is a fresh charge against a shared
# prepaid balance, and there are ~45 projects that have never been fetched.
# Projects that already hold backlink data can still be refreshed monthly.
BACKLINK_FIRST_FETCH_ENABLED = config('BACKLINK_FIRST_FETCH_ENABLED', default=False, cast=bool)

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='1080254283876-0o3ur4sr7ii1kh4ugaij4c7n1ptibn4j.apps.googleusercontent.com')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='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')
# GOOGLE_OAUTH_REDIRECT_URI - can be set in .env, or will be constructed from SITE_URL
GOOGLE_OAUTH_REDIRECT_URI = config('GOOGLE_OAUTH_REDIRECT_URI', default=None)
if not GOOGLE_OAUTH_REDIRECT_URI:
    # Auto-construct from SITE_URL if not explicitly set
    GOOGLE_OAUTH_REDIRECT_URI = f"{SITE_URL.rstrip('/')}/integrations/google/callback/"

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    # Increased from 60 minutes to 8 hours to reduce frequent session timeouts
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    # Increased from 7 days to 30 days for better user experience
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR.parent / 'logs' / 'backend.log',
            'maxBytes': 1024 * 1024 * 50,  # 50MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'content': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'domains': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
