# Generated by Django 5.2 on 2025-12-10 14:10

import authentication.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organisation', max_length=255)),
                ('team_count', models.PositiveIntegerField(default=1, help_text='Number of team members')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the organisation was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the organisation was last modified')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Email address of the account', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('user', 'User')], default='user', help_text='Role of the account (super-admin, admin or user)', max_length=12)),
                ('active_domain_id', models.IntegerField(blank=True, help_text='ID of the currently active domain for this user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the account was last modified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(help_text='Organisation this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['email'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired')], default='pending', help_text='Current status of the reset token', max_length=10)),
                ('expires_at', models.DateTimeField(default=authentication.models.default_expires_in_1_hour, help_text='When the reset token expires')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='When the token was last modified')),
                ('user', models.ForeignKey(help_text='User requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], default='user', help_text='Role to be assigned to the invited user', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Current status of the invitation', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message to include with the invitation')),
                ('expires_at', models.DateTimeField(default=authentication.models.default_expires_in_7_days, help_text='When the invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='When the invitation was last modified')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Organisation the user is being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'db_table': 'team_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('mentions', 'Mentions'), ('prompts', 'Prompts'), ('alerts', 'Alerts'), ('sentiment_analysis', 'Sentiment Analysis'), ('topics', 'Topics'), ('share_of_voice', 'Share of Voice'), ('historical_trends', 'Historical Trends'), ('content_gaps', 'Content Gaps'), ('competitors', 'Competitors'), ('multilingual', 'Multilingual'), ('ai_copilot', 'AI Copilot'), ('prompt_insights', 'Prompt Insights'), ('agent_analytics', 'Agent Analytics'), ('ai_crawler', 'AI Crawler'), ('traffic_attribution', 'Traffic Attribution'), ('misinformation_alerts', 'Misinformation Alerts'), ('reports', 'Reports'), ('organization_settings', 'Organization Settings'), ('team_management', 'Team Management')], help_text='Module the permission applies to', max_length=30)),
                ('permission_level', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Full Access')], help_text='Level of permission for the module', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the permission was granted')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='When the permission was last modified')),
                ('granted_by', models.ForeignKey(help_text='User who granted this permission', on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User the permission is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'user_permissions',
                'ordering': ['user', 'module'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organisation', 'role', 'is_active'], name='accounts_organis_b05ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organisation', 'created_at'], name='accounts_organis_58fdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['active_domain_id'], name='accounts_active__bf8dce_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['email', 'status'], name='team_invita_email_f39c53_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['organisation', 'status', 'created_at'], name='team_invita_organis_e13f26_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['expires_at'], name='team_invita_expires_785959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together={('email', 'organisation')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'module'], name='user_permis_user_id_224fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['granted_by', 'created_at'], name='user_permis_granted_c81924_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'module')},
        ),
    ]
