# Generated by Django 5.2 on 2025-11-04 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 4, 8, 21, 37, 92890, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 7, 21, 37, 91515, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
