# Generated by Django 5.2 on 2025-10-23 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 16, 59, 56, 440277, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
