# Generated by Django 5.2 on 2025-10-29 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='industry',
            field=models.CharField(blank=True, default=None, help_text='Industry sector of the organisation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 8, 6, 55, 763556, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 6, 55, 761622, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
