# Generated by Django 4.2.26 on 2026-01-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job_role',
            field=models.CharField(blank=True, choices=[('founder', 'Founder / CEO'), ('marketing', 'Marketing Manager'), ('seo', 'SEO Specialist'), ('content', 'Content Strategist'), ('agency', 'Agency / Consultant'), ('other', 'Other')], help_text='Job role/title of the user', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('200+', '200+ employees')], help_text='Number of employees in the organisation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text='List of primary goals for using the platform'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology & Software'), ('ecommerce', 'E-Commerce & Retail'), ('marketing', 'Marketing & Advertising'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare & Medical'), ('education', 'Education & Training'), ('saas', 'SaaS & B2B Services'), ('agency', 'Agency & Consulting'), ('other', 'Other')], help_text='Industry vertical of the organisation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='using_ai_monitoring',
            field=models.BooleanField(blank=True, help_text='Whether the organisation is currently using AI monitoring tools', null=True),
        ),
    ]
