# Generated by Django 6.0.2 on 2026-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_persona_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('mentions', 'Mentions'), ('prompts', 'Prompts'), ('alerts', 'Alerts'), ('sentiment_analysis', 'Sentiment Analysis'), ('topics', 'Topics'), ('share_of_voice', 'Share of Voice'), ('historical_trends', 'Historical Trends'), ('content_gaps', 'Content Gaps'), ('competitors', 'Competitors'), ('multilingual', 'Multilingual'), ('ai_copilot', 'AI Copilot'), ('prompt_insights', 'Prompt Insights'), ('agent_analytics', 'Agent Analytics'), ('ai_crawler', 'AI Crawler'), ('traffic_attribution', 'Traffic Attribution'), ('misinformation_alerts', 'Misinformation Alerts'), ('keyword_rankings', 'Keyword Rankings'), ('organic_reports', 'Organic Reports'), ('reports', 'Reports'), ('organization_settings', 'Organization Settings'), ('team_management', 'Team Management')], help_text='Module the permission applies to', max_length=30),
        ),
    ]
