# Generated by Django 5.2 on 2025-11-04 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 4, 8, 22, 23, 709820, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 7, 22, 23, 708349, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
