# Generated by Django 5.2 on 2025-11-08 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 6, 40, 7, 315042, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 5, 40, 7, 312859, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
