# Generated by Django 6.0.2 on 2026-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_seo_permission_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='seo_keyword_limit',
            field=models.PositiveIntegerField(default=3000, help_text='Maximum number of SEO keywords allowed for this organisation'),
        ),
    ]
