# Generated by Django 5.2 on 2025-10-31 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 14, 5, 38, 949544, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 13, 5, 38, 947957, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organisation', 'role', 'is_active'], name='accounts_organis_b05ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organisation', 'created_at'], name='accounts_organis_58fdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['email', 'status'], name='team_invita_email_f39c53_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['organisation', 'status', 'created_at'], name='team_invita_organis_e13f26_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['expires_at'], name='team_invita_expires_785959_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'module'], name='user_permis_user_id_224fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['granted_by', 'created_at'], name='user_permis_granted_c81924_idx'),
        ),
    ]
