# Generated by Django 5.2 on 2026-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_seo_keyword_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='anthropic_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Anthropic API Key', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='anthropic_enabled',
            field=models.BooleanField(default=True, help_text='Whether Anthropic is enabled'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='deepseek_api_key',
            field=models.TextField(blank=True, help_text='Encrypted DeepSeek API Key', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='deepseek_enabled',
            field=models.BooleanField(default=True, help_text='Whether DeepSeek is enabled'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='gemini_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Gemini API Key', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='gemini_enabled',
            field=models.BooleanField(default=True, help_text='Whether Gemini is enabled'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='openai_api_key',
            field=models.TextField(blank=True, help_text='Encrypted OpenAI API Key', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='openai_enabled',
            field=models.BooleanField(default=True, help_text='Whether OpenAI is enabled'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='perplexity_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Perplexity API Key', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='perplexity_enabled',
            field=models.BooleanField(default=True, help_text='Whether Perplexity is enabled'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='xai_api_key',
            field=models.TextField(blank=True, help_text='Encrypted xAI (Grok) API Key', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='xai_enabled',
            field=models.BooleanField(default=True, help_text='Whether xAI (Grok) is enabled'),
        ),
    ]
