# Generated by Django 5.2 on 2025-10-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_teaminvitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 17, 2, 55, 388831, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
