# Generated by Django 5.2 on 2025-10-31 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 15, 11, 12, 146745, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 14, 11, 12, 144951, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
