# Generated by Django 5.2 on 2025-10-24 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_teaminvitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 8, 20, 14, 658200, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
