# Generated by Django 5.2 on 2026-07-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organisation_content_generation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='content_admin_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Anthropic Admin API Key (sk-ant-admin) for live usage reporting', null=True),
        ),
    ]
