# Generated by Django 5.2 on 2025-11-08 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_active_domain_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_active__bf8dce_idx',
            old_name='accounts_active_d_idx',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 8, 59, 35, 437656, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 7, 59, 35, 436391, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
