# Generated by Django 5.2 on 2025-11-08 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_accounts_active_d_idx_accounts_active__bf8dce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 10, 39, 14, 283197, tzinfo=datetime.timezone.utc), help_text='When the reset token expires'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 9, 39, 14, 281947, tzinfo=datetime.timezone.utc), help_text='When the invitation expires'),
        ),
    ]
