# Generated by Django 5.2 on 2026-07-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_organisation_content_admin_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='content_generation_token_limit',
        ),
    ]
