# Generated by Django 5.2 on 2026-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_teaminvitation_client_role_and_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='billing_address',
            field=models.TextField(blank=True, default='', help_text='Registered address, one line per line'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_gstin',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_legal_name',
            field=models.CharField(blank=True, default='', help_text='Registered name for invoices; falls back to `name` when blank', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_state_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_state_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
