# Generated by Django 5.2 on 2026-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_organisation_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='billing_alt_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_alt_gstin',
            field=models.CharField(blank=True, default='', help_text='Tax registration for the other region (e.g. TRN)', max_length=32),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_alt_legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_alt_state_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='organisation',
            name='billing_alt_state_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
