# Generated by Django 5.2 on 2026-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_organisation_billing_alt_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='openrouter_api_key',
            field=models.TextField(blank=True, help_text='Encrypted OpenRouter API Key (sk-or-...)', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='openrouter_enabled',
            field=models.BooleanField(default=True, help_text='Whether OpenRouter is enabled'),
        ),
    ]
