# Generated by Django 5.2 on 2026-08-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_userpermission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='dataforseo_login',
            field=models.CharField(blank=True, default='', help_text='DataForSEO account login (an email address; not secret)', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='dataforseo_password_enc',
            field=models.TextField(blank=True, help_text='Encrypted DataForSEO API password', null=True),
        ),
    ]
