# Generated by Django 5.2 on 2026-08-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_organisation_dataforseo_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat monthly subscription added to Indian invoices. 0 = not charged.', max_digits=12),
        ),
    ]
