# Generated by Django 5.2 on 2026-08-26 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_add_prompt_keyword_action_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_api_keys', to='authentication.organisation')),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
