# Generated by Django 5.2 on 2026-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_serviceapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_service_account',
            field=models.BooleanField(default=False),
        ),
    ]
