# Generated by Django 5.2 on 2026-08-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_account_is_service_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapikey',
            name='encrypted_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceApiKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='authentication.serviceapikey')),
            ],
            options={
                'db_table': 'service_api_key_usage',
                'indexes': [models.Index(fields=['key', '-created_at'], name='service_api_key_id_4f35e0_idx')],
            },
        ),
    ]
