# Generated by Django 5.2 on 2026-09-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_serviceapikey_encrypted_key_serviceapikeyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('mentions', 'Mentions'), ('prompts', 'Prompts'), ('prompts_add', 'Add Prompts'), ('prompts_edit', 'Edit Prompts'), ('prompts_delete', 'Delete Prompts'), ('alerts', 'Alerts'), ('sentiment_analysis', 'Sentiment Analysis'), ('topics', 'Topics'), ('share_of_voice', 'Share of Voice'), ('historical_trends', 'Historical Trends'), ('content_gaps', 'Content Gaps'), ('competitors', 'Competitors'), ('multilingual', 'Multilingual'), ('ai_copilot', 'AI Copilot'), ('prompt_insights', 'Prompt Insights'), ('agent_analytics', 'Agent Analytics'), ('ai_crawler', 'AI Crawler'), ('traffic_attribution', 'Traffic Attribution'), ('misinformation_alerts', 'Misinformation Alerts'), ('keyword_rankings', 'Keyword Rankings'), ('keywords_add', 'Add Keywords'), ('keywords_edit', 'Edit Keywords'), ('keywords_delete', 'Delete Keywords'), ('seo_competitors', 'SEO Competitors'), ('organic_reports', 'Organic Reports'), ('backlinks', 'Backlinks'), ('reports', 'Reports'), ('audit_engine', 'Audit Engine'), ('organization_settings', 'Organization Settings'), ('team_management', 'Team Management')], help_text='Module the permission applies to', max_length=30),
        ),
    ]
