/**
 * The app frame a lead sees at /audit/<token>, arriving from the landing page.
 *
 * It is deliberately *not* the real Sidebar: the lead has no account, no
 * domain and no permissions, so rendering the live one would mean feeding it
 * an auth context and a domain store it cannot have. This is a static replica
 * — same groups, same labels, same icons, read from the same navigation store
 * — with every row locked except the audit they just requested. Nothing here
 * links anywhere, so there is no route for a lead to wander into.
 *
 * The locks come off when the team converts the audit into a project; until
 * then the only thing the lead can do on this page is watch their audit run
 * and read the report.
 */
import type { ComponentType } from "react";
import { Lock, ScanSearch } from "lucide-react";
import { cn } from "@/lib/utils";
import { useNavigationStore } from "@/stores/navigationStore";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

const ROW = "relative flex items-center gap-2.5 rounded-md text-sm px-2.5 py-1.5 w-full";
const LOCKED_HINT = "Unlocks when this audit becomes a project";

/** One dead nav row: the real label and icon, dimmed, with a padlock. */
function LockedRow({ name, icon: Icon }: { name: string; icon?: ComponentType<{ className?: string }> }) {
  return (
    <Tooltip delayDuration={200}>
      <TooltipTrigger asChild>
        <div className={cn(ROW, "cursor-not-allowed text-foreground/35 select-none")} aria-disabled>
          {Icon && <Icon className="h-4 w-4 shrink-0" />}
          <span className="truncate">{name}</span>
          <Lock className="h-3 w-3 ml-auto shrink-0" />
        </div>
      </TooltipTrigger>
      <TooltipContent side="right">{LOCKED_HINT}</TooltipContent>
    </Tooltip>
  );
}

export function ProspectShell({
  host,
  children,
}: {
  host?: string;
  children: React.ReactNode;
}) {
  // The unfiltered groups — this replica never calls filterByPermissions,
  // because a lead has no permissions to filter by.
  const navGroups = useNavigationStore((s) => s.navGroups);

  return (
    <TooltipProvider>
      <div className="min-h-screen bg-background text-foreground flex">
        <style>{`@media print { .no-print { display: none !important; } body { background: #fff; } }`}</style>

        <aside className="no-print w-64 shrink-0 bg-card border-r border-border h-screen sticky top-0 overflow-y-auto flex flex-col">
          <div className="border-b border-border px-3 pt-3 pb-2">
            <img src="/logo.png" alt="PromptMaxx" className="h-8" />
          </div>

          <nav className="flex-1 px-1.5 py-2 space-y-0.5">
            {navGroups.map((group, gi) => {
              if (group.sectionLabel) {
                return (
                  <div key={`s-${gi}`} className="px-2.5 pt-2.5 pb-0.5">
                    <p className="text-[10px] font-semibold uppercase tracking-wider text-foreground/55">
                      {group.name}
                    </p>
                  </div>
                );
              }
              // The audit itself is the one live row — highlighted, but still
              // not a link: this page *is* that destination.
              if (group.items.some((i) => i.path === "/audits")) {
                return (
                  <div key={`g-${gi}`} className={cn(ROW, "bg-accent text-foreground font-medium")}>
                    <ScanSearch className="h-4 w-4 shrink-0" />
                    <span className="truncate">Your audit</span>
                  </div>
                );
              }
              return group.items.map((item, ii) => (
                <LockedRow key={`${gi}-${ii}`} name={item.name} icon={item.icon} />
              ));
            })}
          </nav>

          <div className="border-t border-border p-3 space-y-1">
            <p className="text-xs font-medium truncate">{host || "Your audit"}</p>
            <p className="text-[11px] text-muted-foreground flex items-center gap-1 pt-1">
              <Lock className="h-3 w-3" />Preview access
            </p>
          </div>
        </aside>

        <div className="flex-1 min-w-0 flex flex-col">
          <main className="flex-1 mx-auto w-full max-w-6xl px-6 py-8">{children}</main>
          <footer className="no-print border-t border-border">
            <div className="mx-auto max-w-6xl px-6 py-6 text-xs text-muted-foreground">
              Generated by PromptMaxx · AI search visibility and content strategy
            </div>
          </footer>
        </div>
      </div>
    </TooltipProvider>
  );
}
