# Generated by Django 5.2 on 2025-10-31 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('domains', '0004_delete_detectedmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_by', '-created_at'], name='alerts_created_dff1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['domain', 'type', 'status'], name='alerts_domain__a6e111_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['resolved_at'], name='alerts_resolve_722a19_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['channel', 'status'], name='alert_notif_channel_5e71f7_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['recipient', '-sent_at'], name='alert_notif_recipie_88a3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['enabled', 'last_triggered_at'], name='alert_rules_enabled_c1dc81_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['domain', '-detection_count'], name='alert_rules_domain__6b0652_idx'),
        ),
    ]
