# Generated by Django 5.2 on 2025-11-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Removed AddField for 'created_by' on 'alert' to avoid duplicate column error
        migrations.AddField(
            model_name='alert',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='domains.domain'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['domain', 'status', 'created_at'], name='alerts_domain__5f7595_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='alerts_status_5203b6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type', 'created_at'], name='alerts_type_cd0135_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_by', '-created_at'], name='alerts_created_dff1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['domain', 'type', 'status'], name='alerts_domain__a6e111_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['resolved_at'], name='alerts_resolve_722a19_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['alert', 'sent_at'], name='alert_notif_alert_i_828dea_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status', 'sent_at'], name='alert_notif_status_72ba91_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['channel', 'status'], name='alert_notif_channel_5e71f7_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['recipient', '-sent_at'], name='alert_notif_recipie_88a3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['domain', 'enabled'], name='alert_rules_domain__b3a9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['enabled', 'last_triggered_at'], name='alert_rules_enabled_c1dc81_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['domain', '-detection_count'], name='alert_rules_domain__6b0652_idx'),
        ),
    ]
