# Generated by Django 5.2 on 2025-10-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_alerts_created_dff1bc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrule',
            name='notification_channels',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notification_channel_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
