# Generated by Django 4.2.26 on 2026-08-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfiguration',
            name='email_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
