# Generated by Django 5.2 on 2025-12-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('visibility_drop', 'Visibility Drop'), ('sentiment_negative', 'Negative Sentiment'), ('competitor_surge', 'Competitor Surge'), ('position_loss', 'Position Loss'), ('misinformation', 'Misinformation')], max_length=50),
        ),
    ]
