# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('domains', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='realtime', max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('slack_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_webhook_url', models.URLField(blank=True, null=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='domains.domain')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='authentication.organisation')),
            ],
            options={
                'db_table': 'alert_configurations',
            },
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['domain'], name='alert_config_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['organisation'], name='alert_config_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False)), fields=('domain',), name='unique_domain_config'),
        ),
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', False)), fields=('organisation',), name='unique_org_config'),
        ),
    ]

