# Generated by Django 5.2 on 2025-11-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertconfiguration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertconfiguration',
            new_name='alert_confi_domain__de3995_idx',
            old_name='alert_config_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='alertconfiguration',
            new_name='alert_confi_organis_624a47_idx',
            old_name='alert_config_org_idx',
        ),
    ]
