# Generated by Django 5.2 on 2025-12-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        # Add template_type field to distinguish between predefined and custom templates
        migrations.AddField(
            model_name='reporttemplate',
            name='template_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('predefined', 'Predefined Template'),
                    ('custom', 'Custom Template')
                ],
                default='predefined',
                help_text='Type of report template'
            ),
        ),

        # Add grid_rows field to store the complete grid layout with widgets
        migrations.AddField(
            model_name='reporttemplate',
            name='grid_rows',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='Grid layout configuration with widgets for custom reports'
            ),
        ),

        # Add organisation field for custom templates (optional, can be null for predefined)
        migrations.AddField(
            model_name='reporttemplate',
            name='organisation',
            field=models.ForeignKey(
                'authentication.Organisation',
                on_delete=models.CASCADE,
                related_name='custom_report_templates',
                null=True,
                blank=True,
                help_text='Organisation that owns this custom template (null for predefined templates)'
            ),
        ),

        # Add created_by field to track who created custom templates
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(
                'authentication.Account',
                on_delete=models.SET_NULL,
                related_name='created_templates',
                null=True,
                blank=True,
                help_text='User who created this custom template'
            ),
        ),

        # Add index for faster filtering by organisation and template_type
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(
                fields=['organisation', 'template_type'],
                name='report_tmpl_org_type_idx'
            ),
        ),
    ]
