# Generated by Django 6.0.2 on 2026-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_html_css_template_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
