# Generated by Django 5.2 on 2025-12-09 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='Full URL')),
                ('url_hash', models.CharField(help_text='SHA256 hash for deduplication', max_length=64)),
                ('is_crawlable', models.BooleanField(default=True, help_text='Whether URL can be crawled')),
                ('crawl_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', help_text='Current crawl status', max_length=20)),
                ('crawl_error', models.TextField(blank=True, help_text='Error message if crawl failed', null=True)),
                ('http_status_code', models.PositiveIntegerField(blank=True, help_text='HTTP response code', null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, help_text='Last successful crawl time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Associated domain', on_delete=django.db.models.deletion.CASCADE, related_name='citation_urls', to='domains.domain')),
                ('prompt_analytics', models.ForeignKey(help_text='Source prompt result', on_delete=django.db.models.deletion.CASCADE, related_name='citation_urls', to='prompts.promptanalytics')),
            ],
            options={
                'verbose_name': 'Citation URL',
                'verbose_name_plural': 'Citation URLs',
                'db_table': 'citation_urls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitationMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_snippet', models.TextField(blank=True, help_text='Extracted context where this citation appeared in the response', null=True)),
                ('position_in_response', models.PositiveIntegerField(default=1, help_text='Position of this citation in the response (1st, 2nd, 3rd, etc.)')),
                ('is_primary_source', models.BooleanField(default=False, help_text='Whether this is the primary/main source cited for the claim')),
                ('mentioned_at', models.DateTimeField(auto_now_add=True, help_text='When this citation was mentioned')),
                ('domain', models.ForeignKey(help_text='Associated domain (denormalized for query efficiency)', on_delete=django.db.models.deletion.CASCADE, related_name='citation_mentions', to='domains.domain')),
                ('prompt_analytics', models.ForeignKey(help_text='The prompt analytics record containing this citation', on_delete=django.db.models.deletion.CASCADE, related_name='citation_mentions', to='prompts.promptanalytics')),
                ('citation_url', models.ForeignKey(help_text='The citation URL being mentioned', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='misinformation.citationurl')),
            ],
            options={
                'verbose_name': 'Citation Mention',
                'verbose_name_plural': 'Citation Mentions',
                'db_table': 'citation_mentions',
                'ordering': ['-mentioned_at'],
            },
        ),
        migrations.CreateModel(
            name='CitationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_html', models.TextField(blank=True, help_text='Original HTML content', null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Clean extracted text', null=True)),
                ('page_title', models.CharField(blank=True, help_text='Page title', max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description', null=True)),
                ('publish_date', models.DateField(blank=True, help_text='Content publish date if found', null=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 hash of extracted_text', max_length=64, null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True, help_text='When content was fetched')),
                ('citation_url', models.OneToOneField(help_text='Associated citation URL', on_delete=django.db.models.deletion.CASCADE, related_name='content', to='misinformation.citationurl')),
            ],
            options={
                'verbose_name': 'Citation Content',
                'verbose_name_plural': 'Citation Contents',
                'db_table': 'citation_content',
            },
        ),
        migrations.CreateModel(
            name='MisinformationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Analytics date')),
                ('total_detected', models.PositiveIntegerField(default=0, help_text='Total alerts for the day')),
                ('broken_links_count', models.PositiveIntegerField(default=0, help_text='Broken link alerts')),
                ('misinformation_count', models.PositiveIntegerField(default=0, help_text='Misinformation alerts')),
                ('outdated_count', models.PositiveIntegerField(default=0, help_text='Outdated info alerts')),
                ('by_severity', models.JSONField(default=dict, help_text='Counts by severity: {low: x, medium: x, high: x, critical: x}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(help_text='Associated domain', on_delete=django.db.models.deletion.CASCADE, related_name='misinformation_analytics', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Misinformation Analytics',
                'verbose_name_plural': 'Misinformation Analytics',
                'db_table': 'misinformation_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MisinformationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the scan', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the scan started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the scan completed', null=True)),
                ('total_prompts_scanned', models.PositiveIntegerField(default=0, help_text='Number of prompts processed')),
                ('total_citations_found', models.PositiveIntegerField(default=0, help_text='Number of citation URLs found')),
                ('total_alerts_generated', models.PositiveIntegerField(default=0, help_text='Number of alerts created')),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(help_text='Domain being scanned', on_delete=django.db.models.deletion.CASCADE, related_name='misinformation_scans', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Misinformation Scan',
                'verbose_name_plural': 'Misinformation Scans',
                'db_table': 'misinformation_scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MisinformationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('misinformation', 'Misinformation'), ('broken_link', 'Broken Link'), ('outdated', 'Outdated Information')], help_text='Type of alert', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level', max_length=10)),
                ('llm_claim', models.TextField(help_text='What the LLM stated')),
                ('source_content', models.TextField(blank=True, help_text='Relevant content from source', null=True)),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation of the issue', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', help_text='Current status of the alert', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the alert was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('citation_url', models.ForeignKey(blank=True, help_text='Related citation URL (nullable for non-URL issues)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='misinformation.citationurl')),
                ('domain', models.ForeignKey(help_text='Associated domain', on_delete=django.db.models.deletion.CASCADE, related_name='misinformation_alerts', to='domains.domain')),
                ('prompt', models.ForeignKey(help_text='Source prompt', on_delete=django.db.models.deletion.CASCADE, related_name='misinformation_alerts', to='prompts.prompt')),
                ('prompt_analytics', models.ForeignKey(help_text='Source prompt result', on_delete=django.db.models.deletion.CASCADE, related_name='misinformation_alerts', to='prompts.promptanalytics')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_misinformation_alerts', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, help_text='Scan that generated this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='misinformation.misinformationscan')),
            ],
            options={
                'verbose_name': 'Misinformation Alert',
                'verbose_name_plural': 'Misinformation Alerts',
                'db_table': 'misinformation_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='citationurl',
            index=models.Index(fields=['domain', 'crawl_status'], name='citation_ur_domain__9888ea_idx'),
        ),
        migrations.AddIndex(
            model_name='citationurl',
            index=models.Index(fields=['url_hash'], name='citation_ur_url_has_da74f5_idx'),
        ),
        migrations.AddIndex(
            model_name='citationurl',
            index=models.Index(fields=['domain', '-last_crawled_at'], name='citation_ur_domain__f8c09d_idx'),
        ),
        migrations.AddIndex(
            model_name='citationurl',
            index=models.Index(fields=['http_status_code'], name='citation_ur_http_st_a3ac65_idx'),
        ),
        migrations.AddIndex(
            model_name='citationmention',
            index=models.Index(fields=['domain', '-mentioned_at'], name='citation_me_domain__ea88e6_idx'),
        ),
        migrations.AddIndex(
            model_name='citationmention',
            index=models.Index(fields=['citation_url', '-mentioned_at'], name='citation_me_citatio_17d7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='citationmention',
            index=models.Index(fields=['prompt_analytics', 'position_in_response'], name='citation_me_prompt__5a7864_idx'),
        ),
        migrations.AddIndex(
            model_name='citationmention',
            index=models.Index(fields=['domain', 'citation_url'], name='citation_me_domain__f4cdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationanalytics',
            index=models.Index(fields=['domain', '-date'], name='misinformat_domain__afc934_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationanalytics',
            index=models.Index(fields=['date', '-total_detected'], name='misinformat_date_a93f6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='misinformationanalytics',
            unique_together={('domain', 'date')},
        ),
        migrations.AddIndex(
            model_name='misinformationscan',
            index=models.Index(fields=['domain', 'status'], name='misinformat_domain__dfbbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationscan',
            index=models.Index(fields=['domain', '-created_at'], name='misinformat_domain__2e26cc_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationscan',
            index=models.Index(fields=['status', 'created_at'], name='misinformat_status_4a5c57_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationalert',
            index=models.Index(fields=['domain', 'alert_type'], name='misinformat_domain__3e7b62_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationalert',
            index=models.Index(fields=['domain', 'severity'], name='misinformat_domain__c95be1_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationalert',
            index=models.Index(fields=['domain', 'status'], name='misinformat_domain__f7e0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationalert',
            index=models.Index(fields=['domain', '-created_at'], name='misinformat_domain__f65440_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationalert',
            index=models.Index(fields=['alert_type', 'severity', 'status'], name='misinformat_alert_t_0b2697_idx'),
        ),
        migrations.AddIndex(
            model_name='misinformationalert',
            index=models.Index(fields=['prompt_analytics', 'alert_type'], name='misinformat_prompt__75d721_idx'),
        ),
    ]
