# Generated by Django 5.2 on 2025-10-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organisation', max_length=255)),
                ('team_count', models.PositiveIntegerField(default=1, help_text='Number of team members')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the organisation was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the organisation was last modified')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the domain', max_length=255)),
                ('url', models.URLField(help_text='URL of the domain')),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score of the domain', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('active_alerts', models.PositiveIntegerField(default=0, help_text='Number of active alerts')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Overall sentiment of mentions', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1.00 to 1.00)', max_digits=3)),
                ('processing_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Current processing status of the domain', max_length=10)),
                ('track_status', models.CharField(default='INIT', help_text='Detailed tracking status', max_length=50)),
                ('track_message', models.TextField(blank=True, help_text='Message or notes about the processing status', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when the domain was last tracked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the domain was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the domain was last modified')),
                ('organisation', models.ForeignKey(help_text='Organisation this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='shared_models.organisation')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domains',
                'ordering': ['name'],
                'unique_together': {('url', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the user', max_length=254, unique=True)),
                ('first_name', models.CharField(help_text='First name of the user', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the user', max_length=100)),
                ('password', models.CharField(help_text='Hashed password', max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Admin'), ('user', 'User')], default='user', help_text='Role of the user', max_length=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the account was last modified')),
                ('organisation', models.ForeignKey(help_text='Organisation this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='shared_models.organisation')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='PromptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(help_text='Unique identifier for the group', max_length=100, unique=True)),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('track_status', models.CharField(default='INIT', help_text='Detailed tracking status of the group', max_length=50)),
                ('track_message', models.TextField(blank=True, help_text='Status message for tracking', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when tracking status was last updated', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this group is published and visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the group was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_groups', to='shared_models.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_groups', to='shared_models.organisation')),
            ],
            options={
                'verbose_name': 'Prompt Group',
                'verbose_name_plural': 'Prompt Groups',
                'db_table': 'prompt_groups',
                'ordering': ['group_id'],
                'unique_together': {('group_id', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The actual prompt text')),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Processing tracking status of the prompt', max_length=10)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', help_text='Type of prompt (primary or secondary)', max_length=10)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when the prompt was last tracked', null=True)),
                ('track_message', models.TextField(blank=True, help_text='Message or notes about the tracking status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the prompt was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the prompt was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='shared_models.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='shared_models.organisation')),
                ('group', models.ForeignKey(blank=True, help_text='Group this prompt belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='shared_models.promptgroup')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'db_table': 'prompts',
                'ordering': ['prompt'],
                'unique_together': {('prompt', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword being tracked', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the keyword was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the keyword was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='shared_models.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='shared_models.organisation')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keywords',
                'ordering': ['keyword'],
                'unique_together': {('keyword', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='PromptAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='ChatGPT', help_text='Name of the AI platform used', max_length=100)),
                ('is_mention', models.BooleanField(default=False, help_text='Whether this analytics entry is a mention or not')),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('position', models.DecimalField(decimal_places=2, default=0.0, help_text='Position in search results', max_digits=8)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Sentiment of the analytics', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1.00 to 1.00)', max_digits=3)),
                ('context_summary', models.TextField(blank=True, help_text='Summary of the context')),
                ('citations', models.JSONField(blank=True, default=list, help_text='List of citations with text and source URLs')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('shares', models.PositiveIntegerField(default=0, help_text='Number of shares')),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Engagement score', max_digits=5)),
                ('competitor_mentions', models.JSONField(blank=True, default=list, help_text='List of competitor mentions')),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='List of key topics extracted')),
                ('position_history', models.JSONField(blank=True, default=list, help_text='Historical position data')),
                ('track_status', models.CharField(default='INIT', help_text='Detailed tracking status of the analytics', max_length=50)),
                ('track_message', models.TextField(blank=True, help_text='Status message for tracking', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when tracking status was last updated', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this analytics is published and visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the analytics was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the analytics was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this analytics belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analytics', to='shared_models.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this analytics belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analytics', to='shared_models.organisation')),
                ('prompt', models.ForeignKey(help_text='Prompt this analytics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='shared_models.prompt')),
            ],
            options={
                'verbose_name': 'Prompt Analytics',
                'verbose_name_plural': 'Prompt Analytics',
                'db_table': 'prompt_analytics',
                'ordering': ['-created_at'],
                'unique_together': {('prompt', 'platform')},
            },
        ),
    ]
