# Generated by Django 5.2 on 2025-10-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='promptanalytics',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='promptanalytics',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='promptgroup',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='group',
            field=models.ForeignKey(help_text='Group this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='shared_models.promptgroup'),
        ),
    ]
