# Generated by Django 5.2 on 2025-10-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    atomic = False

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE prompts DROP COLUMN IF EXISTS processing_status;\n"
            ),
            reverse_sql=(
                "ALTER TABLE prompts ADD COLUMN IF NOT EXISTS processing_status varchar(10) DEFAULT 'INIT';\n"
            ),
        ),
    ]


