# Generated by Django 5.2 on 2025-10-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_remove_processing_status_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='processing_status',
        ),
    ]
