# Generated by Django 5.2 on 2025-11-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_remove_keyword_organisation_remove_prompt_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the competitor', max_length=255)),
                ('url', models.URLField(help_text="URL of the competitor's website", max_length=500)),
                ('total_mentions', models.IntegerField(default=0, help_text='Total number of mentions')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score', max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Average sentiment score', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in AI responses', max_digits=5)),
                ('share_of_voice_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Share of voice percentage', max_digits=5)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Trend percentage change', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last modified')),
            ],
            options={
                'db_table': 'competitors',
                'ordering': ['-total_mentions'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='AI platform name', max_length=100)),
                ('total_mentions', models.IntegerField(default=0, help_text='Number of mentions on this date')),
                ('position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position', max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Average sentiment score', max_digits=5)),
                ('timestamp', models.DateField(help_text='Date of this analytics snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
            ],
            options={
                'db_table': 'competitor_analytics',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text="Theme or topic (e.g., 'Product Quality', 'Customer Service')", max_length=255)),
                ('positive_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of positive sentiment', max_digits=5)),
                ('neutral_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of neutral sentiment', max_digits=5)),
                ('negative_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of negative sentiment', max_digits=5)),
                ('mention_count', models.IntegerField(default=0, help_text='Number of mentions for this theme')),
                ('platform', models.CharField(blank=True, help_text='AI platform (null = aggregated across all platforms)', max_length=100, null=True)),
                ('timestamp', models.DateField(help_text='Date of this analytics snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
            ],
            options={
                'db_table': 'sentiment_analytics',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareOfVoiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='AI platform (null = aggregated across all platforms)', max_length=100, null=True)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Share of voice percentage', max_digits=5)),
                ('mention_count', models.IntegerField(default=0, help_text='Number of mentions')),
                ('market_position', models.IntegerField(blank=True, help_text='Market rank (1 = leader, 2 = second, etc.)', null=True)),
                ('timestamp', models.DateField(help_text='Date of this analytics snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
            ],
            options={
                'db_table': 'share_of_voice_analytics',
                'ordering': ['-timestamp', 'market_position'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False, 'ordering': ['email'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='citations',
            new_name='citation_list',
        ),
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='competitor_mentions',
            new_name='competitor_mention_list',
        ),
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='key_topics',
            new_name='topic_list',
        ),
        migrations.RemoveField(
            model_name='promptanalytics',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='promptanalytics',
            name='sentiment_category',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Sentiment category (positive/neutral/negative)', max_length=10),
        ),
    ]
