# Generated by Django 5.2 on 2025-11-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_competitor_competitoranalytics_sentimentanalytics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False, 'ordering': ['keyword'], 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'managed': False, 'ordering': ['prompt'], 'verbose_name': 'Prompt', 'verbose_name_plural': 'Prompts'},
        ),
        migrations.AlterModelOptions(
            name='promptanalytics',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Prompt Analytics', 'verbose_name_plural': 'Prompt Analytics'},
        ),
        migrations.AlterModelOptions(
            name='promptgroup',
            options={'managed': False, 'ordering': ['group_id'], 'verbose_name': 'Prompt Group', 'verbose_name_plural': 'Prompt Groups'},
        ),
    ]
