# Generated by Django 5.2 on 2025-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_remove_prompt_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptanalytics',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this analytics is published and visible to users'),
        ),
        migrations.AddField(
            model_name='promptgroup',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this group is published and visible to users'),
        ),
    ]
