# Generated by Django 5.2 on 2025-11-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_alter_domain_options_alter_keyword_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPromptAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Complete'), ('FAIL', 'Failed')], default='INIT', help_text='Processing status', max_length=4)),
                ('track_message', models.TextField(blank=True, help_text='Status message or error details', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when last tracked', null=True)),
                ('is_mentioned', models.BooleanField(default=False, help_text='Whether competitor was mentioned')),
                ('position', models.IntegerField(blank=True, help_text='Position where competitor appears', null=True)),
                ('mention_count', models.IntegerField(default=0, help_text='Number of times mentioned in response')),
                ('sentiment_category', models.CharField(blank=True, help_text='Sentiment category (positive/neutral/negative)', max_length=50, null=True)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1 to 1)', max_digits=5)),
                ('platform', models.CharField(blank=True, help_text='AI platform (ChatGPT, Claude, etc.)', max_length=100, null=True)),
                ('response_text', models.TextField(blank=True, help_text='Full AI response', null=True)),
                ('citation_list', models.JSONField(blank=True, default=list, help_text='Citations mentioning competitor')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last modified')),
            ],
            options={
                'db_table': 'competitor_prompt_analytics',
                'ordering': ['competitor', 'position'],
                'managed': False,
            },
        ),
    ]
