# Generated by Django 5.2 on 2025-12-10 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the domain', max_length=255)),
                ('url', models.URLField(help_text='URL of the domain')),
                ('short_description', models.CharField(blank=True, help_text='Brief description of the brand/domain', max_length=500, null=True)),
                ('tone_of_voice', models.TextField(blank=True, help_text="Brand's tone of voice guidelines", null=True)),
                ('content_style', models.TextField(blank=True, help_text='Preferred content style guidelines', null=True)),
                ('key_messages', models.TextField(blank=True, help_text='Key messages or themes to emphasize', null=True)),
                ('topics_to_avoid', models.TextField(blank=True, help_text='Topics or themes to avoid in content', null=True)),
                ('target_audience', models.TextField(blank=True, help_text='Target audience demographics and preferences', null=True)),
                ('brand_values', models.TextField(blank=True, help_text="Brand's core values", null=True)),
                ('key_competitors', models.TextField(blank=True, help_text='Main competitors', null=True)),
                ('country', models.CharField(default='United States', help_text='Country name for domain context', max_length=100)),
                ('niches', models.JSONField(blank=True, help_text='List of industry niches/categories for the brand', null=True)),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score of the domain', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('active_alerts', models.PositiveIntegerField(default=0, help_text='Number of active alerts')),
                ('sentiment_category', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Overall sentiment category of mentions (positive/neutral/negative)', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1.00 to 1.00)', max_digits=3)),
                ('processing_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Current processing status of the domain', max_length=10)),
                ('misinformation_scan_status', models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY', 'Ready'), ('SCANNING', 'Scanning'), ('SCANNED', 'Scanned'), ('NO_ISSUES', 'No Issues Found')], default='NOT_READY', help_text='Misinformation scanning status for this domain', max_length=15)),
                ('last_misinformation_scan_at', models.DateTimeField(blank=True, help_text='Timestamp of the last misinformation scan', null=True)),
                ('competitor_analysis_status', models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY', 'Ready'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed')], default='NOT_READY', help_text='Competitor analysis status for this domain', max_length=15)),
                ('last_competitor_analysis_at', models.DateTimeField(blank=True, help_text='Timestamp of the last competitor analysis', null=True)),
                ('track_message', models.TextField(blank=True, help_text='Message or notes about the processing status', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when the domain was last tracked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the domain was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the domain was last modified')),
                ('organisation', models.ForeignKey(help_text='Organisation this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='domains.domain')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_domain_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Access',
                'verbose_name_plural': 'Domain Access',
                'db_table': 'domain_access',
            },
        ),
        migrations.CreateModel(
            name='DomainHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.PositiveIntegerField(help_text='Total health score achieved (0-100)')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum possible score')),
                ('percentage', models.PositiveIntegerField(help_text='Health score as percentage')),
                ('grade', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], help_text='Grade based on percentage (Excellent/Good/Fair/Poor)', max_length=10)),
                ('grade_color', models.CharField(help_text='Color for grade display (green/blue/yellow/red)', max_length=10)),
                ('checks', models.JSONField(help_text='Array of individual check results with status, score, message')),
                ('total_checks', models.PositiveIntegerField(help_text='Total number of checks performed')),
                ('passed_checks', models.PositiveIntegerField(help_text='Number of checks that passed')),
                ('warning_checks', models.PositiveIntegerField(help_text='Number of checks with warnings')),
                ('failed_checks', models.PositiveIntegerField(help_text='Number of checks that failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when health check was performed')),
                ('checked_by', models.ForeignKey(help_text='User who initiated the health check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(help_text='Domain this health check belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Domain Health Check',
                'verbose_name_plural': 'Domain Health Checks',
                'db_table': 'domain_health_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organisation', 'processing_status'], name='domains_organis_fc59ac_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organisation', '-visibility_score'], name='domains_organis_6ce300_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['processing_status', 'tracked_at'], name='domains_process_5ad01a_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['sentiment_category', '-sentiment_score'], name='domains_sentime_a8113e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('url', 'organisation')},
        ),
        migrations.AddIndex(
            model_name='domainaccess',
            index=models.Index(fields=['granted_by', 'created_at'], name='domain_acce_granted_d10a6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domainaccess',
            unique_together={('user', 'domain')},
        ),
        migrations.AddIndex(
            model_name='domainhealthcheck',
            index=models.Index(fields=['domain', '-created_at'], name='domain_heal_domain__53961f_idx'),
        ),
        migrations.AddIndex(
            model_name='domainhealthcheck',
            index=models.Index(fields=['domain', '-health_score'], name='domain_heal_domain__d0ae08_idx'),
        ),
        migrations.AddIndex(
            model_name='domainhealthcheck',
            index=models.Index(fields=['grade', '-created_at'], name='domain_heal_grade_15dd57_idx'),
        ),
    ]
