# Generated by Django 5.2 on 2025-10-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the domain', max_length=255)),
                ('url', models.URLField(help_text='URL of the domain')),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score of the domain', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('active_alerts', models.PositiveIntegerField(default=0, help_text='Number of active alerts')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Overall sentiment of mentions', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1.00 to 1.00)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the domain was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the domain was last modified')),
                ('organisation', models.ForeignKey(help_text='Organisation this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domains',
                'ordering': ['name'],
                'unique_together': {('url', 'organisation')},
            },
        ),
    ]
