# Generated by Django 5.2 on 2025-10-30 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the domain', max_length=255)),
                ('url', models.URLField(help_text='URL of the domain')),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score of the domain', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('active_alerts', models.PositiveIntegerField(default=0, help_text='Number of active alerts')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Overall sentiment of mentions', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1.00 to 1.00)', max_digits=3)),
                ('processing_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Current processing status of the domain', max_length=10)),
                ('track_status', models.CharField(default='INIT', help_text='Detailed tracking status', max_length=50)),
                ('track_message', models.TextField(blank=True, help_text='Message or notes about the processing status', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when the domain was last tracked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the domain was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the domain was last modified')),
                ('organisation', models.ForeignKey(help_text='Organisation this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domains',
                'ordering': ['name'],
                'unique_together': {('url', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='DetectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Google Gemini', 'Google Gemini'), ('Perplexity', 'Perplexity'), ('Claude', 'Claude'), ('Copilot', 'Copilot'), ('Other', 'Other')], help_text='Name of the detected AI model', max_length=50)),
                ('detection_count', models.PositiveIntegerField(default=1, help_text='Number of times this model was detected')),
                ('first_detected', models.DateTimeField(auto_now_add=True, help_text='When this model was first detected')),
                ('last_detected', models.DateTimeField(auto_now=True, help_text='When this model was last detected')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model detection is active')),
                ('organisation', models.ForeignKey(help_text='Organisation this detection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='detected_models', to='authentication.organisation')),
                ('domain', models.ForeignKey(help_text='Domain where this model was detected', on_delete=django.db.models.deletion.CASCADE, related_name='detected_models', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Detected Model',
                'verbose_name_plural': 'Detected Models',
                'db_table': 'detected_models',
                'ordering': ['-last_detected'],
                'unique_together': {('name', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='DomainAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='domains.domain')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_domain_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Access',
                'verbose_name_plural': 'Domain Access',
                'db_table': 'domain_access',
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
