# Generated by Django 5.2 on 2025-12-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
    ]
