# Generated by Django 4.2.26 on 2025-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description of the brand/domain', max_length=500, null=True),
        ),
    ]
