# Generated by Django 5.2 on 2025-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='niches',
            field=models.JSONField(blank=True, help_text='List of industry niches/categories for the brand', null=True),
        ),
    ]
