# Generated by Django 4.2.26 on 2026-01-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLinkMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic or subject for the link', max_length=255)),
                ('keywords', models.TextField(help_text='Comma-separated keywords that should trigger this link')),
                ('url', models.URLField(help_text='URL to link to when keywords are matched', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the link map entry was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the link map entry was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this link map belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='internal_links', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Internal Link Map',
                'verbose_name_plural': 'Internal Link Maps',
                'db_table': 'internal_link_maps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='internal_li_domain__1ef0d5_idx'), models.Index(fields=['domain', 'topic'], name='internal_li_domain__c790de_idx')],
            },
        ),
    ]
