# Generated by Django 5.2 on 2025-10-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainAccess',
        ),
    ]
