# Generated by Django 5.2 on 2025-10-27 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_passwordresettoken_expires_at_and_more'),
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Google Gemini', 'Google Gemini'), ('Perplexity', 'Perplexity'), ('Claude', 'Claude'), ('Copilot', 'Copilot'), ('Other', 'Other')], help_text='Name of the detected AI model', max_length=50)),
                ('detection_count', models.PositiveIntegerField(default=1, help_text='Number of times this model was detected')),
                ('first_detected', models.DateTimeField(auto_now_add=True, help_text='When this model was first detected')),
                ('last_detected', models.DateTimeField(auto_now=True, help_text='When this model was last detected')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model detection is active')),
                ('domain', models.ForeignKey(help_text='Domain where this model was detected', on_delete=django.db.models.deletion.CASCADE, related_name='detected_models', to='domains.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this detection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='detected_models', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Detected Model',
                'verbose_name_plural': 'Detected Models',
                'db_table': 'detected_models',
                'ordering': ['-last_detected'],
                'unique_together': {('name', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='DomainAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='domains.domain')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_domain_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Access',
                'verbose_name_plural': 'Domain Access',
                'db_table': 'domain_access',
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
