# Generated by Django 5.2 on 2025-10-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='processing_status',
            field=models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Current processing status of the domain', max_length=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='track_message',
            field=models.TextField(blank=True, help_text='Message or notes about the processing status', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='track_status',
            field=models.CharField(default='INIT', help_text='Detailed tracking status', max_length=50),
        ),
        migrations.AddField(
            model_name='domain',
            name='tracked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the domain was last tracked', null=True),
        ),
    ]
