# Generated by Django 6.0.2 on 2026-03-10 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_internal_link_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Uploaded file (null for text notes)', null=True, upload_to='reference_docs/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original file name or title for text notes', max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('docx', 'Word Document'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('text', 'Text Note')], help_text='Type of reference document', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes (0 for text notes)')),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Text content extracted from the uploaded file or user-entered text')),
                ('description', models.TextField(blank=True, default='', help_text='User-provided description or context about this document')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the document was uploaded')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the document was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this reference document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='domains.domain')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reference_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference Document',
                'verbose_name_plural': 'Reference Documents',
                'db_table': 'reference_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='reference_d_domain__8109b5_idx'), models.Index(fields=['domain', 'file_type'], name='reference_d_domain__144d1b_idx')],
            },
        ),
    ]
