# Generated by Django 4.2.26 on 2025-12-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0002_alter_domain_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.PositiveIntegerField(help_text='Total health score achieved (0-100)')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum possible score')),
                ('percentage', models.PositiveIntegerField(help_text='Health score as percentage')),
                ('grade', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], help_text='Grade based on percentage (Excellent/Good/Fair/Poor)', max_length=10)),
                ('grade_color', models.CharField(help_text='Color for grade display (green/blue/yellow/red)', max_length=10)),
                ('checks', models.JSONField(help_text='Array of individual check results with status, score, message')),
                ('total_checks', models.PositiveIntegerField(help_text='Total number of checks performed')),
                ('passed_checks', models.PositiveIntegerField(help_text='Number of checks that passed')),
                ('warning_checks', models.PositiveIntegerField(help_text='Number of checks with warnings')),
                ('failed_checks', models.PositiveIntegerField(help_text='Number of checks that failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when health check was performed')),
                ('checked_by', models.ForeignKey(help_text='User who initiated the health check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(help_text='Domain this health check belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Domain Health Check',
                'verbose_name_plural': 'Domain Health Checks',
                'db_table': 'domain_health_checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='domain_heal_domain__53961f_idx'), models.Index(fields=['domain', '-health_score'], name='domain_heal_domain__d0ae08_idx'), models.Index(fields=['grade', '-created_at'], name='domain_heal_grade_15dd57_idx')],
            },
        ),
    ]
