# Generated by Django 4.2.26 on 2025-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_add_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='content_style',
            field=models.TextField(blank=True, help_text='Preferred content style guidelines', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='key_messages',
            field=models.TextField(blank=True, help_text='Key messages or themes to emphasize', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='tone_of_voice',
            field=models.TextField(blank=True, help_text="Brand's tone of voice guidelines", null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='topics_to_avoid',
            field=models.TextField(blank=True, help_text='Topics or themes to avoid in content', null=True),
        ),
    ]
