# Generated by Django 5.2 on 2025-10-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_domainaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectedModel',
        ),
    ]
