# Generated by Django 4.2.26 on 2025-11-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_add_content_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='brand_values',
            field=models.TextField(blank=True, help_text="Brand's core values", null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='key_competitors',
            field=models.TextField(blank=True, help_text='Main competitors', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Target audience demographics and preferences', null=True),
        ),
    ]
