# Generated by Django 6.0.2 on 2026-03-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_add_reference_document_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk within the document (0-based)')),
                ('chunk_text', models.TextField(help_text='The text content of this chunk')),
                ('document', models.ForeignKey(help_text='Parent reference document', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='domains.referencedocument')),
            ],
            options={
                'verbose_name': 'Reference Document Chunk',
                'verbose_name_plural': 'Reference Document Chunks',
                'db_table': 'reference_document_chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='reference_d_documen_f38711_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
