# Generated by Django 6.0.2 on 2026-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_add_reference_document_chunk_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedocument',
            name='extraction_error',
            field=models.TextField(blank=True, default='', help_text='Error message if text extraction failed'),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', help_text='Status of text extraction from uploaded file', max_length=20),
        ),
    ]
