# Generated by Django 5.2 on 2025-10-31 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_passwordresettoken_expires_at_and_more'),
        ('domains', '0004_delete_detectedmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organisation', 'processing_status'], name='domains_organis_fc59ac_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organisation', '-visibility_score'], name='domains_organis_6ce300_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['track_status', 'tracked_at'], name='domains_track_s_14ee58_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['sentiment', '-sentiment_score'], name='domains_sentime_309c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='domainaccess',
            index=models.Index(fields=['granted_by', 'created_at'], name='domain_acce_granted_d10a6a_idx'),
        ),
    ]
