# Generated by Django 4.2.26 on 2025-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_add_brand_identity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_misinformation_scan_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last misinformation scan', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='misinformation_scan_status',
            field=models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY', 'Ready'), ('SCANNING', 'Scanning'), ('SCANNED', 'Scanned'), ('NO_ISSUES', 'No Issues Found')], default='NOT_READY', help_text='Misinformation scanning status for this domain', max_length=15),
        ),
    ]
