# Generated by Django 6.0.2 on 2026-04-06 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_add_extraction_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('microsite', 'Microsite'), ('blog', 'Blog'), ('other', 'Other')], help_text='Platform type for the link', max_length=20)),
                ('url', models.URLField(help_text='URL of the brand digital asset', max_length=500)),
                ('label', models.CharField(blank=True, default='', help_text='Optional custom label for the link', max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Text content extracted from crawling the URL')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of text extraction from the URL', max_length=20)),
                ('extraction_error', models.TextField(blank=True, default='', help_text='Error message if text extraction failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the link was added')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the link was last modified')),
                ('added_by', models.ForeignKey(help_text='User who added this link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_brand_links', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(help_text='Domain this brand link belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='brand_links', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Brand Link',
                'verbose_name_plural': 'Brand Links',
                'db_table': 'brand_links',
                'ordering': ['platform', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandLinkChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk within the brand link content (0-based)')),
                ('chunk_text', models.TextField(help_text='The text content of this chunk')),
                ('brand_link', models.ForeignKey(help_text='Parent brand link', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='domains.brandlink')),
            ],
            options={
                'verbose_name': 'Brand Link Chunk',
                'verbose_name_plural': 'Brand Link Chunks',
                'db_table': 'brand_link_chunks',
                'ordering': ['brand_link', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='brandlink',
            index=models.Index(fields=['domain', '-created_at'], name='brand_links_domain__6326a7_idx'),
        ),
        migrations.AddIndex(
            model_name='brandlink',
            index=models.Index(fields=['domain', 'platform'], name='brand_links_domain__d1e797_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brandlink',
            unique_together={('domain', 'url')},
        ),
        migrations.AddIndex(
            model_name='brandlinkchunk',
            index=models.Index(fields=['brand_link', 'chunk_index'], name='brand_link__brand_l_fac606_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brandlinkchunk',
            unique_together={('brand_link', 'chunk_index')},
        ),
    ]
