# Generated by Django 5.2 on 2025-10-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_passwordresettoken_expires_at_and_more'),
        ('domains', '0005_domain_domains_organis_fc59ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='domain',
            name='domains_track_s_14ee58_idx',
        ),
        migrations.RemoveIndex(
            model_name='domain',
            name='domains_sentime_309c0a_idx',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='track_status',
        ),
        migrations.AddField(
            model_name='domain',
            name='sentiment_category',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Overall sentiment category of mentions (positive/neutral/negative)', max_length=10),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['processing_status', 'tracked_at'], name='domains_process_5ad01a_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['sentiment_category', '-sentiment_score'], name='domains_sentime_a8113e_idx'),
        ),
    ]
