# Generated by Django 6.0.2 on 2026-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_brandlink_brandlinkchunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandlink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('microsite', 'Microsite'), ('blog', 'Blog'), ('other', 'Other')], help_text='Platform type for the link', max_length=20),
        ),
    ]
