# Generated by Django 5.2 on 2026-07-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_alter_brandlink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text="ISO 3166-1 alpha-2 country code, e.g. 'IN', 'US'", max_length=2)),
                ('country_name', models.CharField(help_text="Human-readable country name for display, e.g. 'India'", max_length=100)),
                ('locale', models.CharField(blank=True, help_text="Optional locale hint for prompt localization, e.g. 'en-IN'", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the engine should query this region on the next run')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary region for the domain (seeded from Domain.country)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this tracked region belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Domain Region',
                'verbose_name_plural': 'Domain Regions',
                'db_table': 'domain_regions',
                'ordering': ['-is_primary', 'country_name'],
                'unique_together': {('domain', 'country_code')},
            },
        ),
    ]
