# Generated by Django 5.2 on 2026-08-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_domain_commercial_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set(),
        ),
    ]
