# Generated by Django 5.2 on 2026-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_alter_domain_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_swept_at',
            field=models.DateTimeField(blank=True, help_text='When the full prompt sweep last covered this domain', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='sweep_cadence',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 15 days'), ('monthly', 'Every 30 days'), ('off', 'Off - no sweep')], default='weekly', help_text='How often the full prompt sweep re-runs this domain', max_length=10),
        ),
    ]
