# Generated by Django 5.2 on 2025-12-09 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated title from first message', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this conversation is about', on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='domains.domain')),
                ('user', models.ForeignKey(help_text='User who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'db_table': 'chat_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Role of the message sender', max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('function_calls', models.JSONField(blank=True, help_text='Function calls made by the assistant (if any)', null=True)),
                ('function_results', models.JSONField(blank=True, help_text='Results from function calls', null=True)),
                ('model_used', models.CharField(blank=True, help_text='AI model used for this message (e.g., gpt-4o-mini)', max_length=50, null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Total tokens used for this message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'domain', '-updated_at'], name='chat_conver_user_id_6bed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['domain', '-created_at'], name='chat_conver_domain__ee77c1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'created_at'], name='chat_messag_role_b6a95d_idx'),
        ),
    ]
