# Generated by Django 5.2 on 2025-11-29 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('google_analytics', 'Google Analytics'), ('search_console', 'Google Search Console'), ('slack', 'Slack'), ('sms', 'SMS Provider'), ('cms', 'CMS')], max_length=50)),
                ('provider_id', models.CharField(max_length=255)),
                ('credentials', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='domains.domain')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSCTrafficInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_status', models.CharField(choices=[('INIT', 'Initialized'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('avg_ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_position', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('top_queries', models.JSONField(default=list)),
                ('top_pages', models.JSONField(default=list)),
                ('device_breakdown', models.JSONField(default=dict)),
                ('country_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_traffic_insights', to='domains.domain')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_insights', to='integrations.integration')),
            ],
            options={
                'db_table': 'gsc_traffic_insights',
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GATrafficInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_status', models.CharField(choices=[('INIT', 'Initialized'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_breakdown', models.JSONField(default=dict)),
                ('device_breakdown', models.JSONField(default=dict)),
                ('geographic_breakdown', models.JSONField(default=dict)),
                ('landing_pages', models.JSONField(default=list)),
                ('conversion_paths', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_traffic_insights', to='domains.domain')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_insights', to='integrations.integration')),
            ],
            options={
                'db_table': 'ga_traffic_insights',
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['domain', 'type'], name='integration_domain__aa1bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['status', 'last_sync_at'], name='integration_status_2bc1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['domain', 'status'], name='integration_domain__5b2bed_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['type', 'status'], name='integration_type_99f848_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['last_sync_at'], name='integration_last_sy_d6ee00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('domain', 'type', 'provider_id')},
        ),
        migrations.AddIndex(
            model_name='gsctrafficinsight',
            index=models.Index(fields=['domain', 'track_status'], name='gsc_traffic_domain__b08b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='gsctrafficinsight',
            index=models.Index(fields=['integration', 'start_date', 'end_date'], name='gsc_traffic_integra_ca4439_idx'),
        ),
        migrations.AddIndex(
            model_name='gsctrafficinsight',
            index=models.Index(fields=['start_date', 'end_date'], name='gsc_traffic_start_d_0c493c_idx'),
        ),
        migrations.AddIndex(
            model_name='gsctrafficinsight',
            index=models.Index(fields=['track_status', 'created_at'], name='gsc_traffic_track_s_48a897_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gsctrafficinsight',
            unique_together={('integration', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='gatrafficinsight',
            index=models.Index(fields=['domain', 'track_status'], name='ga_traffic__domain__6be898_idx'),
        ),
        migrations.AddIndex(
            model_name='gatrafficinsight',
            index=models.Index(fields=['integration', 'start_date', 'end_date'], name='ga_traffic__integra_60cd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='gatrafficinsight',
            index=models.Index(fields=['start_date', 'end_date'], name='ga_traffic__start_d_510b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='gatrafficinsight',
            index=models.Index(fields=['track_status', 'created_at'], name='ga_traffic__track_s_49cdae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gatrafficinsight',
            unique_together={('integration', 'start_date', 'end_date')},
        ),
    ]
