# Generated by Django 5.2 on 2025-10-31 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0004_delete_detectedmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('google_analytics', 'Google Analytics'), ('search_console', 'Google Search Console'), ('slack', 'Slack'), ('sms', 'SMS Provider'), ('cms', 'CMS')], max_length=50)),
                ('provider_id', models.CharField(max_length=255)),
                ('credentials', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='domains.domain')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'type'], name='integration_domain__aa1bf4_idx'), models.Index(fields=['status', 'last_sync_at'], name='integration_status_2bc1c8_idx')],
                'unique_together': {('domain', 'type', 'provider_id')},
            },
        ),
    ]
