# Generated by Django 5.2 on 2025-10-31 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_domains_organis_fc59ac_idx_and_more'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['domain', 'status'], name='integration_domain__5b2bed_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['type', 'status'], name='integration_type_99f848_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['last_sync_at'], name='integration_last_sy_d6ee00_idx'),
        ),
    ]
