# Generated by Django 5.2 on 2026-06-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_alter_brandlink_platform'),
        ('integrations', '0002_add_period_type_to_traffic_insights'),
        ('seo_rankings', '0012_seosecondarydomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='secondary_domain',
            field=models.ForeignKey(blank=True, help_text='Set when this integration belongs to a report-only secondary subdomain instead of a Domain.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='seo_rankings.seosecondarydomain'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='domains.domain'),
        ),
    ]
