# Generated by Django 5.2 on 2026-07-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_domainaccess_access_level_and_is_active'),
        ('integrations', '0003_integration_secondary_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAAITrafficDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text="Day in the GA4 property's timezone")),
                ('platform', models.CharField(default='__all__', help_text="AI source label, or '__all__' for the combined row", max_length=64)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('users', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('avg_duration', models.DecimalField(decimal_places=2, default=0.0, help_text='Mean session duration, seconds', max_digits=10)),
                ('property_id', models.CharField(blank=True, default='', max_length=64)),
                ('property_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(help_text='When this row was last refreshed from GA4. GA restates recent days, so a row is rewritten while it stays inside the rolling window.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_traffic_daily', to='domains.domain')),
            ],
            options={
                'db_table': 'ga_ai_traffic_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['domain', 'date'], name='ga_ai_traff_domain__644c36_idx'), models.Index(fields=['domain', 'platform', 'date'], name='ga_ai_traff_domain__f5278a_idx')],
                'unique_together': {('domain', 'date', 'platform')},
            },
        ),
    ]
