# Generated by Django 4.2.26 on 2025-11-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the generated content', max_length=500)),
                ('content_html', models.TextField(help_text='Generated content in HTML format')),
                ('content_json', models.JSONField(blank=True, help_text='Rich text editor JSON format (for TipTap/ProseMirror)', null=True)),
                ('source_type', models.CharField(choices=[('topic', 'Topic Module'), ('content_gap', 'Content Gap Module'), ('manual', 'Manual Creation')], help_text='Source module that initiated content generation', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='ID of the source record (Topic ID or Content Gap ID)', null=True)),
                ('source_reference', models.TextField(blank=True, help_text='Additional source context (e.g., question text, topic name)', null=True)),
                ('article_type', models.CharField(choices=[('blog', 'Blog Post'), ('guide', 'How-to Guide'), ('comparison', 'Comparison Article'), ('listicle', 'Listicle'), ('technical', 'Technical Article')], default='blog', help_text='Type of article', max_length=20)),
                ('keywords', models.TextField(help_text='Target keywords (comma-separated)')),
                ('tone', models.CharField(default='professional', help_text='Tone of the content (professional, casual, friendly, authoritative)', max_length=50)),
                ('style', models.CharField(default='informative', help_text='Writing style (informative, persuasive, storytelling, analytical)', max_length=50)),
                ('goal', models.CharField(default='educate', help_text='Content goal (educate, convert, engage, inform)', max_length=50)),
                ('audience', models.CharField(default='general', help_text='Target audience (general, beginners, professionals, experts)', max_length=50)),
                ('depth', models.CharField(default='comprehensive', help_text='Content depth (overview, detailed, comprehensive, extensive)', max_length=50)),
                ('word_count', models.IntegerField(default=1500, help_text='Target word count')),
                ('actual_word_count', models.IntegerField(blank=True, help_text='Actual word count of generated content', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('published', 'Published')], default='generated', help_text='Status of the content', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled publication date', null=True)),
                ('published_date', models.DateTimeField(blank=True, help_text='Actual publication date', null=True)),
                ('priority', models.CharField(default='medium', help_text='Priority level (high, medium, low)', max_length=10)),
                ('model_used', models.CharField(default='claude-3-5-sonnet-20241022', help_text='AI model used for generation', max_length=100)),
                ('generation_time_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to generate content', max_digits=8, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Number of prompt tokens used', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='Number of completion tokens used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='shared_models.domain')),
            ],
            options={
                'verbose_name': 'Generated Content',
                'verbose_name_plural': 'Generated Contents',
                'db_table': 'generated_contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='generated_c_domain__5aed04_idx'), models.Index(fields=['source_type', 'source_id'], name='generated_c_source__0b7e08_idx'), models.Index(fields=['status'], name='generated_c_status_ba98e0_idx')],
            },
        ),
    ]
