# Generated by Django 5.2 on 2025-12-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('wordpress', 'WordPress'), ('strapi', 'Strapi'), ('joomla', 'Joomla'), ('drupal', 'Drupal'), ('contentful', 'Contentful')], default='wordpress', help_text='Type of CMS provider', max_length=50)),
                ('name', models.CharField(help_text="Display name for this CMS provider (e.g., 'Main WordPress Site', 'Blog WordPress')", max_length=200)),
                ('settings', models.JSONField(default=dict, help_text='Provider-specific settings')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this CMS configuration is active')),
                ('is_default', models.BooleanField(default=False, help_text='Default CMS provider for this domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this CMS provider belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cms_providers', to='domains.domain')),
            ],
            options={
                'verbose_name': 'CMS Provider',
                'verbose_name_plural': 'CMS Providers',
                'db_table': 'cms_providers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the generated content', max_length=500)),
                ('content_html', models.TextField(help_text='Generated content in HTML format')),
                ('content_json', models.JSONField(blank=True, help_text='Rich text editor JSON format (for TipTap/ProseMirror)', null=True)),
                ('source_type', models.CharField(choices=[('topic', 'Topic Module'), ('content_gap', 'Content Gap Module'), ('answer_gap', 'Answer Gap Module'), ('manual', 'Manual Creation')], help_text='Source module that initiated content generation', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='ID of the source record (Topic ID or Content Gap ID)', null=True)),
                ('source_reference', models.TextField(blank=True, help_text='Additional source context (e.g., question text, topic name)', null=True)),
                ('article_type', models.CharField(choices=[('blog', 'Blog Post'), ('guide', 'How-to Guide'), ('comparison', 'Comparison Article'), ('listicle', 'Listicle'), ('technical', 'Technical Article')], default='blog', help_text='Type of article', max_length=20)),
                ('keywords', models.TextField(help_text='Target keywords (comma-separated)')),
                ('tone', models.CharField(default='professional', help_text='Tone of the content (professional, casual, friendly, authoritative)', max_length=50)),
                ('style', models.CharField(default='informative', help_text='Writing style (informative, persuasive, storytelling, analytical)', max_length=50)),
                ('goal', models.CharField(default='educate', help_text='Content goal (educate, convert, engage, inform)', max_length=50)),
                ('audience', models.CharField(default='general', help_text='Target audience (general, beginners, professionals, experts)', max_length=50)),
                ('depth', models.CharField(default='comprehensive', help_text='Content depth (overview, detailed, comprehensive, extensive)', max_length=50)),
                ('word_count', models.IntegerField(default=1500, help_text='Target word count')),
                ('actual_word_count', models.IntegerField(blank=True, help_text='Actual word count of generated content', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='generated', help_text='Status of the content', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled publication date', null=True)),
                ('published_date', models.DateTimeField(blank=True, help_text='Actual publication date', null=True)),
                ('priority', models.CharField(default='medium', help_text='Priority level (high, medium, low)', max_length=10)),
                ('model_used', models.CharField(default='claude-3-5-sonnet-20241022', help_text='AI model used for generation', max_length=100)),
                ('generation_time_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to generate content', max_digits=8, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Number of prompt tokens used', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='Number of completion tokens used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Generated Content',
                'verbose_name_plural': 'Generated Contents',
                'db_table': 'generated_contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='When to publish this content')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Publication status', max_length=20)),
                ('wordpress_post_id', models.IntegerField(blank=True, help_text='WordPress post/page ID after publication', null=True)),
                ('wordpress_url', models.URLField(blank=True, help_text='URL of published content', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if publication failed', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Actual publication time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cms_provider', models.ForeignKey(help_text='CMS provider to publish to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publications', to='content.cmsprovider')),
                ('content', models.ForeignKey(help_text='Content to be published', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publications', to='content.generatedcontent')),
            ],
            options={
                'verbose_name': 'Scheduled Publication',
                'verbose_name_plural': 'Scheduled Publications',
                'db_table': 'scheduled_publications',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cmsprovider',
            index=models.Index(fields=['domain', 'provider_type'], name='cms_provide_domain__815890_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsprovider',
            index=models.Index(fields=['domain', 'is_active'], name='cms_provide_domain__cb65a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cmsprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('domain',), name='unique_default_cms_per_domain'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['domain', '-created_at'], name='generated_c_domain__5aed04_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['source_type', 'source_id'], name='generated_c_source__0b7e08_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['status'], name='generated_c_status_ba98e0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduled_p_status_6b1566_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['cms_provider', 'scheduled_at'], name='scheduled_p_cms_pro_fea4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['content', 'status'], name='scheduled_p_content_70379f_idx'),
        ),
    ]
