# Generated by Django 4.2.26 on 2026-01-24 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', help_text='Review status', max_length=20)),
                ('overall_comment', models.TextField(blank=True, help_text='Overall comment on the content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(help_text='Content being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.generatedcontent')),
                ('reviewer', models.ForeignKey(help_text='User who is reviewing', on_delete=django.db.models.deletion.CASCADE, related_name='content_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Review',
                'verbose_name_plural': 'Content Reviews',
                'db_table': 'content_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParagraphReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_index', models.IntegerField(help_text='Index of the paragraph (0-based)')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('needs_changes', 'Needs Changes'), ('rejected', 'Rejected')], default='needs_changes', help_text='Paragraph review status', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Comment on this paragraph', null=True)),
                ('suggestion', models.TextField(blank=True, help_text='Suggested rewrite for this paragraph', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_review', models.ForeignKey(help_text='Parent content review', on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_reviews', to='content.contentreview')),
            ],
            options={
                'verbose_name': 'Paragraph Review',
                'verbose_name_plural': 'Paragraph Reviews',
                'db_table': 'paragraph_reviews',
                'ordering': ['paragraph_index'],
                'indexes': [models.Index(fields=['content_review', 'paragraph_index'], name='paragraph_r_content_7cfdd1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paragraphreview',
            constraint=models.UniqueConstraint(fields=('content_review', 'paragraph_index'), name='unique_paragraph_review'),
        ),
        migrations.AddIndex(
            model_name='contentreview',
            index=models.Index(fields=['content', 'reviewer'], name='content_rev_content_59042f_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreview',
            index=models.Index(fields=['content', 'status'], name='content_rev_content_da57b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentreview',
            constraint=models.UniqueConstraint(fields=('content', 'reviewer'), name='unique_review_per_user_content'),
        ),
    ]
