# Generated by Django 5.2 on 2025-12-09 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('domains', '0002_create_domain_health_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('wordpress', 'WordPress')], default='wordpress', help_text='Type of CMS provider', max_length=50)),
                ('name', models.CharField(help_text="Display name for this CMS provider (e.g., 'Main WordPress Site', 'Blog WordPress')", max_length=200)),
                ('settings', models.JSONField(default=dict, help_text='Provider-specific settings')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this CMS configuration is active')),
                ('is_default', models.BooleanField(default=False, help_text='Default CMS provider for this domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this CMS provider belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cms_providers', to='domains.domain')),
            ],
            options={
                'verbose_name': 'CMS Provider',
                'verbose_name_plural': 'CMS Providers',
                'db_table': 'cms_providers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='When to publish this content')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Publication status', max_length=20)),
                ('wordpress_post_id', models.IntegerField(blank=True, help_text='WordPress post/page ID after publication', null=True)),
                ('wordpress_url', models.URLField(blank=True, help_text='URL of published content', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if publication failed', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Actual publication time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cms_provider', models.ForeignKey(help_text='CMS provider to publish to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publications', to='content.cmsprovider')),
                ('content', models.ForeignKey(help_text='Content to be published', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publications', to='content.generatedcontent')),
            ],
            options={
                'verbose_name': 'Scheduled Publication',
                'verbose_name_plural': 'Scheduled Publications',
                'db_table': 'scheduled_publications',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cmsprovider',
            index=models.Index(fields=['domain', 'provider_type'], name='cms_provide_domain__815890_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsprovider',
            index=models.Index(fields=['domain', 'is_active'], name='cms_provide_domain__cb65a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cmsprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('domain',), name='unique_default_cms_per_domain'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduled_p_status_6b1566_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['cms_provider', 'scheduled_at'], name='scheduled_p_cms_pro_fea4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpublication',
            index=models.Index(fields=['content', 'status'], name='scheduled_p_content_70379f_idx'),
        ),
    ]
