# Generated by Django 5.2 on 2025-12-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_cmsprovider_scheduledpublication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='generated', help_text='Status of the content', max_length=20),
        ),
    ]
