# Generated by Django 4.2.26 on 2026-01-24 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_add_content_review_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField(help_text='The text that was highlighted/selected')),
                ('comment', models.TextField(help_text="The reviewer's comment or feedback")),
                ('suggestion', models.TextField(blank=True, help_text='Suggested replacement text (optional)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Comment status', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the comment was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Comment',
                'verbose_name_plural': 'Content Comments',
                'db_table': 'content_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='paragraphreview',
            name='content_review',
        ),
        migrations.DeleteModel(
            name='ContentReview',
        ),
        migrations.DeleteModel(
            name='ParagraphReview',
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='content',
            field=models.ForeignKey(help_text='Content being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.generatedcontent'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who accepted/rejected the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentcomment',
            index=models.Index(fields=['content', 'status'], name='content_com_content_d284e4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcomment',
            index=models.Index(fields=['content', 'author'], name='content_com_content_548520_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcomment',
            index=models.Index(fields=['content', '-created_at'], name='content_com_content_4958b4_idx'),
        ),
    ]
