# Generated by Django 5.2 on 2026-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_replace_review_with_comments'),
    ]

    operations = [
        # AI detection fields already exist in the database (added outside migrations).
        # Use state_operations via SeparateDatabaseAndState to sync Django state
        # without touching the database.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='generatedcontent',
                    name='ai_detection_checked_at',
                    field=models.DateTimeField(blank=True, help_text='Last time AI detection was run', null=True),
                ),
                migrations.AddField(
                    model_name='generatedcontent',
                    name='ai_detection_label',
                    field=models.CharField(blank=True, help_text="AI detection label (e.g., 'AI-generated', 'Human-written', 'Mixed')", max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='generatedcontent',
                    name='ai_detection_score',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='AI-generated content probability score (0-100)', max_digits=5, null=True),
                ),
                migrations.AddField(
                    model_name='generatedcontent',
                    name='human_detection_score',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='Human-written content probability score (0-100)', max_digits=5, null=True),
                ),
                migrations.AlterField(
                    model_name='generatedcontent',
                    name='article_type',
                    field=models.CharField(choices=[('blog', 'Blog Post'), ('guide', 'How-to Guide'), ('comparison', 'Comparison Article'), ('listicle', 'Listicle'), ('technical', 'Technical Article'), ('landing_page', 'Landing Page'), ('services_page', 'Services Page'), ('product_page', 'Product Page'), ('features_page', 'Features Page'), ('resource_page', 'Resource/Guide Page'), ('twitter_post', 'Twitter/X Post'), ('linkedin_post', 'LinkedIn Post'), ('facebook_post', 'Facebook Post'), ('instagram_caption', 'Instagram Caption'), ('social_thread', 'Thread/Carousel'), ('reddit_post', 'Reddit Post'), ('quora_answer', 'Quora Answer'), ('forum_post', 'Forum Post'), ('product_hunt', 'Product Hunt Launch'), ('newsletter_snippet', 'Newsletter Snippet')], default='blog', help_text='Type of article', max_length=30),
                ),
                migrations.AlterField(
                    model_name='generatedcontent',
                    name='audience',
                    field=models.TextField(default='general', help_text='Target audience (general, beginners, professionals, experts)'),
                ),
                migrations.AlterField(
                    model_name='generatedcontent',
                    name='depth',
                    field=models.TextField(default='comprehensive', help_text='Content depth (overview, detailed, comprehensive, extensive)'),
                ),
                migrations.AlterField(
                    model_name='generatedcontent',
                    name='goal',
                    field=models.TextField(default='educate', help_text='Content goal (educate, convert, engage, inform)'),
                ),
                migrations.AlterField(
                    model_name='generatedcontent',
                    name='style',
                    field=models.TextField(default='informative', help_text='Writing style (informative, persuasive, storytelling, analytical)'),
                ),
                migrations.AlterField(
                    model_name='generatedcontent',
                    name='tone',
                    field=models.TextField(default='professional', help_text='Tone of the content (professional, casual, friendly, authoritative)'),
                ),
            ],
            database_operations=[],
        ),
        # New humanise fields - these are genuinely new columns
        migrations.AddField(
            model_name='generatedcontent',
            name='humanise_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the humanisation process completed', null=True),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='humanise_error',
            field=models.TextField(blank=True, help_text='Error message if humanisation failed', null=True),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='humanise_started_at',
            field=models.DateTimeField(blank=True, help_text='When the humanisation process started', null=True),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='humanise_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Status of the humanisation process', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='pre_humanise_content',
            field=models.TextField(blank=True, help_text='Original HTML content before humanisation (for undo)', null=True),
        ),
    ]
