# Generated by Django 5.2 on 2025-12-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_generatedcontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsprovider',
            name='provider_type',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('strapi', 'Strapi')], default='wordpress', help_text='Type of CMS provider', max_length=50),
        ),
    ]
