# Generated by Django 5.2 on 2026-02-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_generatedcontent_ai_detection_checked_at_and_more'),
        ('domains', '0002_internal_link_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original uploaded file name', max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='processing', help_text='Overall batch status', max_length=25)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Total number of content items in batch')),
                ('processed_items', models.PositiveIntegerField(default=0, help_text='Number of items processed so far (generated + failed)')),
                ('successful_items', models.PositiveIntegerField(default=0, help_text='Number of items successfully generated')),
                ('failed_items', models.PositiveIntegerField(default=0, help_text='Number of items that failed generation')),
                ('error_message', models.TextField(blank=True, help_text='Batch-level error message (e.g., parse failure)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the entire batch finished processing', null=True)),
                ('domain', models.ForeignKey(help_text='Domain this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_batches', to='domains.domain')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload Batch',
                'verbose_name_plural': 'Bulk Upload Batches',
                'db_table': 'bulk_upload_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Row number in the Excel file (for reference)')),
                ('content_category', models.CharField(help_text='Content category from Excel (Articles, Web Pages, Social Media, Community)', max_length=50)),
                ('content_type', models.CharField(help_text='Content type from Excel (Blog Post, Landing Page, etc.)', max_length=50)),
                ('title', models.CharField(help_text='Title from Excel', max_length=500)),
                ('keywords', models.TextField(help_text='Keywords from Excel (comma-separated)')),
                ('article_type', models.CharField(choices=[('blog', 'Blog Post'), ('guide', 'How-to Guide'), ('comparison', 'Comparison Article'), ('listicle', 'Listicle'), ('technical', 'Technical Article'), ('landing_page', 'Landing Page'), ('services_page', 'Services Page'), ('product_page', 'Product Page'), ('features_page', 'Features Page'), ('resource_page', 'Resource/Guide Page'), ('twitter_post', 'Twitter/X Post'), ('linkedin_post', 'LinkedIn Post'), ('facebook_post', 'Facebook Post'), ('instagram_caption', 'Instagram Caption'), ('social_thread', 'Thread/Carousel'), ('reddit_post', 'Reddit Post'), ('quora_answer', 'Quora Answer'), ('forum_post', 'Forum Post'), ('product_hunt', 'Product Hunt Launch'), ('newsletter_snippet', 'Newsletter Snippet')], default='blog', help_text='Mapped article type code for ClaudeContentGenerator', max_length=30)),
                ('target_country', models.CharField(default='united_states', max_length=100)),
                ('target_language', models.CharField(default='us_english', max_length=100)),
                ('target_audience', models.CharField(default='general', max_length=50)),
                ('word_count', models.IntegerField(default=1500)),
                ('tone', models.TextField(default='professional')),
                ('style', models.TextField(default='informative')),
                ('key_messages', models.TextField(blank=True, default='')),
                ('topics_to_avoid', models.TextField(blank=True, default='')),
                ('additional_instructions', models.TextField(blank=True, default='')),
                ('reference_urls', models.TextField(blank=True, default='')),
                ('reference_descriptions', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('generating', 'Generating'), ('generated', 'Generated'), ('generation_failed', 'Generation Failed'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='processed', help_text='Item generation lifecycle status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.bulkuploadbatch')),
                ('generated_content', models.OneToOneField(blank=True, help_text='The GeneratedContent record created from this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_upload_item', to='content.generatedcontent')),
            ],
            options={
                'verbose_name': 'Bulk Upload Item',
                'verbose_name_plural': 'Bulk Upload Items',
                'db_table': 'bulk_upload_items',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkuploadbatch',
            index=models.Index(fields=['domain', '-created_at'], name='bulk_upload_domain__94330f_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadbatch',
            index=models.Index(fields=['status'], name='bulk_upload_status_009cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadbatch',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='bulk_upload_uploade_22a9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaditem',
            index=models.Index(fields=['batch', 'status'], name='bulk_upload_batch_i_1edd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaditem',
            index=models.Index(fields=['batch', 'row_number'], name='bulk_upload_batch_i_7cd17d_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaditem',
            index=models.Index(fields=['status'], name='bulk_upload_status_f96925_idx'),
        ),
    ]
