# Generated by Django 5.2 on 2026-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bulkuploadbatch_bulkuploaditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO meta description (auto-generated, ~160 chars)'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='SEO meta title (auto-generated, ~60 chars)', max_length=200),
        ),
    ]
