# Generated by Django 6.0.2 on 2026-03-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_generatedcontent_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='refurbished_from',
            field=models.ForeignKey(blank=True, help_text='Original content this was refurbished from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refurbished_versions', to='content.generatedcontent'),
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('draft', 'Draft'), ('generated', 'Generated'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='generated', help_text='Status of the content', max_length=20),
        ),
    ]
