# Generated by Django 5.2 on 2026-08-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentgenerationusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='source_type',
            field=models.CharField(choices=[('topic', 'Topic Module'), ('content_gap', 'GEO Content Gap'), ('seo_content_gap', 'SEO Content Gap'), ('answer_gap', 'Answer Gap Module'), ('manual', 'Manual Creation')], help_text='Source module that initiated content generation', max_length=20),
        ),
    ]
