# Generated by Django 5.2 on 2026-08-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_ai_detection_columns_for_real'),
        ('content', '0009_alter_generatedcontent_source_type'),
    ]

    operations = [
    ]
