# Generated by Django 5.2 on 2026-08-30 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_serviceapikey_encrypted_key_serviceapikeyusage'),
        ('content', '0010_merge_20260824_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgenerationusage',
            name='cached_tokens',
            field=models.IntegerField(default=0, help_text='Prompt tokens served from cache. Billed differently, so they are tracked separately rather than folded into input_tokens.'),
        ),
        migrations.AddField(
            model_name='contentgenerationusage',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Actual USD cost reported by the provider. NULL when the provider does not report one (Google returns token counts but no price), so a null is 'unknown', never 'free'.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contentgenerationusage',
            name='is_byok',
            field=models.BooleanField(default=False, help_text="True when the organisation's own key paid, False when the system key did. Comes straight from OpenRouter's usage block."),
        ),
        migrations.AddField(
            model_name='contentgenerationusage',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('other', 'Other')], default='openrouter', help_text='Which credential paid for the call. Kept separate from model_name because OpenRouter bills in dollars while Gemini bills against a request quota.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contentgenerationusage',
            index=models.Index(fields=['organisation', 'model_name', '-created_at'], name='content_gen_organis_5cb832_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationusage',
            index=models.Index(fields=['organisation', 'provider', '-created_at'], name='content_gen_organis_21431b_idx'),
        ),
    ]
