# Generated by Django 5.2 on 2026-09-12 06:50

import audits.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0011_alter_domain_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=audits.models._new_public_token, editable=False, help_text='Unguessable slug for the public report URL', max_length=32, unique=True)),
                ('host', models.CharField(db_index=True, help_text="Normalised hostname, e.g. 'hdfcbank.com' (no scheme, no www)", max_length=255)),
                ('website', models.URLField(help_text='Canonical URL the crawl started from')),
                ('country', models.CharField(default='us', help_text='ISO 3166-1 alpha-2 market the prompts and SERP are run for', max_length=2)),
                ('source', models.CharField(choices=[('manual', 'Run from the app'), ('landing', 'Landing page'), ('api', 'Public API')], default='manual', max_length=8)),
                ('requester_email', models.EmailField(blank=True, default='', max_length=254)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INIT', 'Queued'), ('PROC', 'Processing'), ('DONE', 'Published'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('stage', models.CharField(blank=True, choices=[('profile', 'Reading the site'), ('prompts', 'Writing buyer prompts'), ('engines', 'Asking the AI engines'), ('serp', 'Checking Google rankings'), ('score', 'Scoring'), ('publish', 'Publishing the report')], default='', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('stage_detail', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('competitors', models.JSONField(blank=True, default=list, help_text="[{'name': 'ICICI Bank', 'host': 'icicibank.com'}, ...]")),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text="['WordPress', 'Cloudflare']")),
                ('grounding', models.JSONField(blank=True, default=dict)),
                ('geo_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100', null=True)),
                ('geo_stage', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present'), ('preferred', 'Preferred'), ('default', 'Default')], default='', max_length=10)),
                ('appearances', models.PositiveIntegerField(default=0, help_text='Runs where the brand was mentioned')),
                ('cited_runs', models.PositiveIntegerField(default=0, help_text="Runs where the brand's site was cited")),
                ('total_runs', models.PositiveIntegerField(default=0, help_text='Runs that completed (denominator)')),
                ('engines_preferred', models.PositiveSmallIntegerField(default=0, help_text='Engines mentioning the brand on >50% of prompts')),
                ('engines_total', models.PositiveSmallIntegerField(default=0)),
                ('share_of_voice', models.DecimalField(blank=True, decimal_places=2, help_text='Percent', max_digits=5, null=True)),
                ('seo_visibility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('keywords_top10', models.PositiveSmallIntegerField(default=0)),
                ('keywords_total', models.PositiveSmallIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('opens', models.PositiveIntegerField(default=0, help_text='Public report views')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Public link stops resolving after this; claimed audits never expire', null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_claimed', to=settings.AUTH_USER_MODEL)),
                ('claimed_domain', models.ForeignKey(blank=True, help_text='Domain created from this audit; the audit is its Day-0 baseline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='domains.domain')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'db_table': 'audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditKeywordResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Organic rank; null when not in the top 100', null=True)),
                ('ranking_url', models.URLField(blank=True, default='', max_length=1000)),
                ('outranked_by', models.JSONField(blank=True, default=list, help_text='Hosts ranking above the brand, in order')),
                ('serp_features', models.JSONField(blank=True, default=list, help_text="e.g. ['featured_snippet', 'people_also_ask']")),
                ('geo_engines_mentioning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_results', to='audits.audit')),
            ],
            options={
                'verbose_name': 'Audit Keyword Result',
                'verbose_name_plural': 'Audit Keyword Results',
                'db_table': 'audit_keyword_results',
                'ordering': ['audit', '-search_volume'],
            },
        ),
        migrations.CreateModel(
            name='AuditPromptResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_index', models.PositiveSmallIntegerField()),
                ('prompt_text', models.TextField()),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('funnel_stage', models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='', max_length=6)),
                ('platform', models.CharField(max_length=32)),
                ('run_index', models.PositiveSmallIntegerField(default=1, help_text='1-based; audits run each prompt once')),
                ('status', models.CharField(choices=[('ok', 'Answered'), ('failed', 'Failed'), ('rate_limited', 'Rate limited'), ('skipped', 'Skipped')], default='ok', max_length=12)),
                ('is_mention', models.BooleanField(default=False)),
                ('is_cited', models.BooleanField(default=False, help_text="The brand's own site appears in the citations")),
                ('position', models.DecimalField(blank=True, decimal_places=2, help_text='Order in which the brand is named among brands in the answer; null when absent', max_digits=5, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='', max_length=8)),
                ('competitors_mentioned', models.JSONField(blank=True, default=list, help_text='Competitor names found in the answer')),
                ('cited_domains', models.JSONField(blank=True, default=list, help_text='Hosts of every URL the answer cited, in order')),
                ('response_text', models.TextField(blank=True, default='')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_results', to='audits.audit')),
            ],
            options={
                'verbose_name': 'Audit Prompt Result',
                'verbose_name_plural': 'Audit Prompt Results',
                'db_table': 'audit_prompt_results',
                'ordering': ['audit', 'prompt_index', 'platform', 'run_index'],
            },
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['status'], name='audits_status_7f0541_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['host', '-created_at'], name='audits_host_a6ee0f_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['source', '-created_at'], name='audits_source_5d20bc_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['requester_ip', '-created_at'], name='audits_request_26fd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditkeywordresult',
            index=models.Index(fields=['audit'], name='audit_keywo_audit_i_5c2cac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditkeywordresult',
            unique_together={('audit', 'keyword')},
        ),
        migrations.AddIndex(
            model_name='auditpromptresult',
            index=models.Index(fields=['audit', 'prompt_index'], name='audit_promp_audit_i_4eb52b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditpromptresult',
            index=models.Index(fields=['audit', 'platform'], name='audit_promp_audit_i_f1d1a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditpromptresult',
            unique_together={('audit', 'prompt_index', 'platform', 'run_index')},
        ),
    ]
