# Generated by Django 5.2 on 2026-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_page_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpromptresult',
            name='rival_positions',
            field=models.JSONField(blank=True, default=dict, help_text='Order each named brand (rivals and you) first appears in the answer, 1 = first'),
        ),
    ]
