# Generated by Django 5.2 on 2026-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_page_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='email_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times the report has been emailed'),
        ),
        migrations.AddField(
            model_name='audit',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='When the report was last emailed', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='emailed_to',
            field=models.JSONField(blank=True, default=list, help_text='Addresses the last send went to'),
        ),
    ]
