# Generated by Django 5.2 on 2025-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('positive_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('neutral_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('negative_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mention_count', models.IntegerField(default=0)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentiment_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShareOfVoiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mention_count', models.IntegerField(default=0)),
                ('market_position', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'share_of_voice_analytics',
                'ordering': ['-timestamp', 'market_position'],
            },
        ),
    ]
