# Generated by Django 5.2 on 2025-12-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_date', models.DateField(help_text='Date of the snapshot (can be daily, weekly, monthly, quarterly)')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='daily', help_text='Type of period this snapshot represents', max_length=20)),
                ('positive_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('neutral_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('negative_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mention_count', models.IntegerField(default=0)),
                ('mentions', models.PositiveIntegerField(default=0, help_text='Total mentions')),
                ('citations', models.PositiveIntegerField(default=0, help_text='Total citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentiment_analytics',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareOfVoiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mention_count', models.IntegerField(default=0)),
                ('market_position', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'share_of_voice_analytics',
                'ordering': ['-timestamp', 'market_position'],
            },
        ),
    ]
