# Generated by Django 5.2 on 2025-11-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('competitors', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalytics',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analytics', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='shareofvoiceanalytics',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sov_analytics', to='competitors.competitor'),
        ),
        migrations.AddField(
            model_name='shareofvoiceanalytics',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sov_analytics', to='domains.domain'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'timestamp'], name='sentiment_a_domain__760a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['theme', 'timestamp'], name='sentiment_a_theme_d98b66_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'platform', 'timestamp'], name='sentiment_a_domain__508f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'theme', '-negative_percentage'], name='sentiment_a_domain__ff51e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['timestamp', '-mention_count'], name='sentiment_a_timesta_b59eac_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'timestamp'], name='share_of_vo_domain__5251b3_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['competitor', 'timestamp'], name='share_of_vo_competi_0a1523_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'platform', 'timestamp'], name='share_of_vo_domain__bc13d9_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['timestamp', '-share_percentage'], name='share_of_vo_timesta_15e8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'competitor', 'platform', 'timestamp'], name='share_of_vo_domain__19b6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['market_position', 'timestamp'], name='share_of_vo_market__0f1e79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shareofvoiceanalytics',
            unique_together={('domain', 'competitor', 'platform', 'timestamp')},
        ),
    ]
