# Generated by Django 5.2 on 2025-11-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('competitors', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalytics',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analytics', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='shareofvoiceanalytics',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sov_analytics', to='competitors.competitor'),
        ),
        migrations.AddField(
            model_name='shareofvoiceanalytics',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sov_analytics', to='domains.domain'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'snapshot_date'], name='sentiment_a_domain__8d4e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['theme', 'snapshot_date'], name='sentiment_a_theme_5678fa_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'platform', 'snapshot_date'], name='sentiment_a_domain__a0fadd_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'theme', '-sentiment_score'], name='sentiment_a_domain__20fa37_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['snapshot_date', '-mention_count'], name='sentiment_a_snapsho_bd9689_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'period_type', 'snapshot_date'], name='sentiment_a_domain__3cd29f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentimentanalytics',
            unique_together={('domain', 'theme', 'platform', 'snapshot_date', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'timestamp'], name='share_of_vo_domain__5251b3_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['competitor', 'timestamp'], name='share_of_vo_competi_0a1523_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'platform', 'timestamp'], name='share_of_vo_domain__bc13d9_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['timestamp', '-share_percentage'], name='share_of_vo_timesta_15e8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'competitor', 'platform', 'timestamp'], name='share_of_vo_domain__19b6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['market_position', 'timestamp'], name='share_of_vo_market__0f1e79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shareofvoiceanalytics',
            unique_together={('domain', 'competitor', 'platform', 'timestamp')},
        ),
    ]
