# Generated by Django 5.2 on 2025-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('competitors', '0001_initial'),
        ('domains', '0004_delete_detectedmodel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'platform', 'timestamp'], name='sentiment_a_domain__508f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['domain', 'theme', '-negative_percentage'], name='sentiment_a_domain__ff51e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalytics',
            index=models.Index(fields=['timestamp', '-mention_count'], name='sentiment_a_timesta_b59eac_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'platform', 'timestamp'], name='share_of_vo_domain__bc13d9_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['timestamp', '-share_percentage'], name='share_of_vo_timesta_15e8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['domain', 'competitor', 'platform', 'timestamp'], name='share_of_vo_domain__19b6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shareofvoiceanalytics',
            index=models.Index(fields=['market_position', 'timestamp'], name='share_of_vo_market__0f1e79_idx'),
        ),
    ]
