# Generated by Django 5.2 on 2025-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_update_sentiment_analytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sentimentanalytics',
            new_name='sentiment_a_domain__8d4e3d_idx',
            old_name='sentiment_a_domain__snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='sentimentanalytics',
            new_name='sentiment_a_theme_5678fa_idx',
            old_name='sentiment_a_theme_snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='sentimentanalytics',
            new_name='sentiment_a_domain__a0fadd_idx',
            old_name='sentiment_a_domain__platform_snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='sentimentanalytics',
            new_name='sentiment_a_domain__20fa37_idx',
            old_name='sentiment_a_domain__theme_sentiment_idx',
        ),
        migrations.RenameIndex(
            model_name='sentimentanalytics',
            new_name='sentiment_a_snapsho_bd9689_idx',
            old_name='sentiment_a_snapshot_mention_idx',
        ),
        migrations.RenameIndex(
            model_name='sentimentanalytics',
            new_name='sentiment_a_domain__3cd29f_idx',
            old_name='sentiment_a_domain__period_snapshot_idx',
        ),
        migrations.AlterField(
            model_name='sentimentanalytics',
            name='average_position',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
