# Generated by Django 5.2 on 2025-12-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword being tracked', max_length=255)),
                ('auto_generate_prompts', models.BooleanField(default=True, help_text='If True, this keyword will be used to auto-generate prompt groups')),
                ('priority', models.IntegerField(default=0, help_text='Priority for prompt generation (higher = more important)')),
                ('volume_level', models.CharField(blank=True, help_text='Search volume level: very-low, low, medium, high, very-high', max_length=20, null=True)),
                ('intent', models.CharField(blank=True, help_text='Search intent: informational, navigational, transactional, commercial', max_length=50, null=True)),
                ('entity', models.CharField(blank=True, help_text='Entity/subject of the keyword', max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, help_text='Attribute/characteristic being queried', max_length=255, null=True)),
                ('variable', models.CharField(blank=True, help_text='Variable/modifier in the keyword', max_length=255, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of keyword: ai-generated, seed, manual', max_length=50, null=True)),
                ('topic', models.CharField(blank=True, help_text='Main topic/category of the keyword', max_length=255, null=True)),
                ('cluster_id', models.CharField(blank=True, help_text='Cluster identifier for grouping related keywords', max_length=100, null=True)),
                ('last_used_for_generation', models.DateTimeField(blank=True, help_text='When this keyword was last used to generate prompts', null=True)),
                ('last_used_for_topic_generation', models.DateTimeField(blank=True, help_text='When this keyword was last used for topic generation (can be used multiple times)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the keyword was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the keyword was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keywords',
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='keywords_domain__984fab_idx'), models.Index(fields=['domain', 'auto_generate_prompts', 'priority'], name='keywords_domain__17f954_idx'), models.Index(fields=['domain', 'last_used_for_generation'], name='keywords_domain__b94e12_idx'), models.Index(fields=['domain', 'last_used_for_topic_generation'], name='keywords_domain__986b70_idx')],
                'unique_together': {('keyword', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='SecondaryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword being stored', max_length=255)),
                ('volume_level', models.CharField(blank=True, help_text='Search volume level: very-low, low, medium, high, very-high', max_length=20, null=True)),
                ('intent', models.CharField(blank=True, help_text='Search intent: informational, navigational, transactional, commercial', max_length=50, null=True)),
                ('entity', models.CharField(blank=True, help_text='Entity/subject of the keyword', max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, help_text='Attribute/characteristic being queried', max_length=255, null=True)),
                ('variable', models.CharField(blank=True, help_text='Variable/modifier in the keyword', max_length=255, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of keyword: ai-generated, seed, manual', max_length=50, null=True)),
                ('topic', models.CharField(blank=True, help_text='Main topic/category of the keyword', max_length=255, null=True)),
                ('cluster_id', models.CharField(blank=True, help_text='Cluster identifier for grouping related keywords', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the keyword was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the keyword was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_keywords', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Secondary Keyword',
                'verbose_name_plural': 'Secondary Keywords',
                'db_table': 'secondary_keywords',
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='secondary_k_domain__d6c700_idx'), models.Index(fields=['domain', 'topic'], name='secondary_k_domain__97a0d7_idx'), models.Index(fields=['domain', 'cluster_id'], name='secondary_k_domain__783158_idx')],
                'unique_together': {('keyword', 'domain')},
            },
        ),
    ]
