# Generated by Django 5.2 on 2025-11-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword being tracked', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the keyword was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the keyword was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keywords',
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='keywords_domain__984fab_idx')],
                'unique_together': {('keyword', 'domain')},
            },
        ),
    ]
