# Generated by Django 4.2.26 on 2025-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='attribute',
            field=models.CharField(blank=True, help_text='Attribute/characteristic being queried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='cluster_id',
            field=models.CharField(blank=True, help_text='Cluster identifier for grouping related keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='entity',
            field=models.CharField(blank=True, help_text='Entity/subject of the keyword', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='intent',
            field=models.CharField(blank=True, help_text='Search intent: informational, navigational, transactional, commercial', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='source',
            field=models.CharField(blank=True, help_text='Source of keyword: ai-generated, seed, manual', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='topic',
            field=models.CharField(blank=True, help_text='Main topic/category of the keyword', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='variable',
            field=models.CharField(blank=True, help_text='Variable/modifier in the keyword', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='volume_level',
            field=models.CharField(blank=True, help_text='Search volume level: very-low, low, medium, high, very-high', max_length=20, null=True),
        ),
    ]
