# Generated by Django 5.2 on 2025-11-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_add_keyword_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='keyword',
            new_name='keywords_domain__17f954_idx',
            old_name='keywords_domain__auto_gen_idx',
        ),
        migrations.RenameIndex(
            model_name='keyword',
            new_name='keywords_domain__b94e12_idx',
            old_name='keywords_domain__last_use_idx',
        ),
    ]
