# Generated by Django 4.2.26 on 2025-11-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_add_niches_field'),
        ('keywords', '0002_add_semantic_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword being stored', max_length=255)),
                ('volume_level', models.CharField(blank=True, help_text='Search volume level: very-low, low, medium, high, very-high', max_length=20, null=True)),
                ('intent', models.CharField(blank=True, help_text='Search intent: informational, navigational, transactional, commercial', max_length=50, null=True)),
                ('entity', models.CharField(blank=True, help_text='Entity/subject of the keyword', max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, help_text='Attribute/characteristic being queried', max_length=255, null=True)),
                ('variable', models.CharField(blank=True, help_text='Variable/modifier in the keyword', max_length=255, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of keyword: ai-generated, seed, manual', max_length=50, null=True)),
                ('topic', models.CharField(blank=True, help_text='Main topic/category of the keyword', max_length=255, null=True)),
                ('cluster_id', models.CharField(blank=True, help_text='Cluster identifier for grouping related keywords', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the keyword was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the keyword was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_keywords', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Secondary Keyword',
                'verbose_name_plural': 'Secondary Keywords',
                'db_table': 'secondary_keywords',
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='secondary_k_domain__d6c700_idx'), models.Index(fields=['domain', 'topic'], name='secondary_k_domain__97a0d7_idx'), models.Index(fields=['domain', 'cluster_id'], name='secondary_k_domain__783158_idx')],
                'unique_together': {('keyword', 'domain')},
            },
        ),
    ]
