# Generated by Django 5.2 on 2025-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_domains_organis_fc59ac_idx_and_more'),
        ('keywords', '0002_remove_keyword_organisation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['domain', 'created_at'], name='keywords_domain__984fab_idx'),
        ),
    ]
