# Generated by Django 5.2 on 2025-10-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(help_text='Unique identifier for the cluster', max_length=100, unique=True)),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score of the cluster', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the cluster was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the cluster was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this cluster belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_clusters', to='domains.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this cluster belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_clusters', to='authentication.organisation')),
            ],
            options={
                'verbose_name': 'Prompt Cluster',
                'verbose_name_plural': 'Prompt Clusters',
                'db_table': 'prompt_clusters',
                'ordering': ['cluster_id'],
                'unique_together': {('cluster_id', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The actual prompt text')),
                ('track_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', help_text='Current tracking status of the prompt', max_length=10)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', help_text='Type of prompt (primary or secondary)', max_length=10)),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score of the prompt', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the prompt was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the prompt was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='domains.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='authentication.organisation')),
                ('cluster', models.ForeignKey(help_text='Cluster this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompts.promptcluster')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'db_table': 'prompts',
                'ordering': ['prompt'],
                'unique_together': {('prompt', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='PromptAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the AI model used', max_length=100)),
                ('total_mentions', models.PositiveIntegerField(default=0, help_text='Total number of mentions')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total number of citations')),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score', max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Sentiment of the analytics', max_length=10)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sentiment score (-1.00 to 1.00)', max_digits=3)),
                ('context_summary', models.TextField(blank=True, help_text='Summary of the context')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the analytics was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the analytics was last modified')),
                ('domain', models.ForeignKey(help_text='Domain this analytics belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analytics', to='domains.domain')),
                ('organisation', models.ForeignKey(help_text='Organisation this analytics belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analytics', to='authentication.organisation')),
                ('prompt', models.ForeignKey(help_text='Prompt this analytics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='prompts.prompt')),
            ],
            options={
                'verbose_name': 'Prompt Analytics',
                'verbose_name_plural': 'Prompt Analytics',
                'db_table': 'prompt_analytics',
                'ordering': ['-created_at'],
                'unique_together': {('prompt', 'model_name')},
            },
        ),
    ]
