# Generated by Django 5.2 on 2025-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='theme',
            field=models.CharField(blank=True, help_text='Common theme extracted from prompts in this group using NLP', max_length=255, null=True),
        ),
    ]
