# Generated by Django 5.2 on 2025-10-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_mention',
            field=models.BooleanField(default=False, help_text='Whether this prompt is a mention or not'),
        ),
    ]
