# Generated by Django 5.2 on 2025-10-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgroup',
            name='track_message',
            field=models.TextField(blank=True, help_text='Status message for tracking', null=True),
        ),
    ]
