# Generated by Django 5.2 on 2026-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_domainregion'),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domainmetricsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='promptanalytics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='region',
            field=models.CharField(db_index=True, default='GLOBAL', help_text="Geographic region: ISO 3166-1 alpha-2 country code, or 'GLOBAL' for unattributed. See docs/GEO_AI_MENTION_TRACKING_DESIGN.md.", max_length=8),
        ),
        migrations.AddField(
            model_name='promptanalytics',
            name='region',
            field=models.CharField(db_index=True, default='GLOBAL', help_text="Geographic region: ISO 3166-1 alpha-2 country code, or 'GLOBAL' for unattributed. See docs/GEO_AI_MENTION_TRACKING_DESIGN.md.", max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='domainmetricsnapshot',
            unique_together={('domain', 'platform', 'snapshot_date', 'period_type', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='promptanalytics',
            unique_together={('prompt', 'platform', 'region')},
        ),
    ]
