# Generated by Django 4.2.26 on 2025-12-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promptanalytics',
            index=models.Index(fields=['track_status', '-created_at'], name='prompt_anal_track_s_66ce96_idx'),
        ),
    ]
