# Generated by Django 5.2 on 2025-11-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_add_snapshot_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domainmetricsnapshot',
            new_name='domain_metr_domain__5f235d_idx',
            old_name='domain_metr_domain__snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='domainmetricsnapshot',
            new_name='domain_metr_platfor_8d4f6a_idx',
            old_name='domain_metr_platform_snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='domainmetricsnapshot',
            new_name='domain_metr_snapsho_820c9a_idx',
            old_name='domain_metr_snapshot_visibility_idx',
        ),
        migrations.RenameIndex(
            model_name='domainmetricsnapshot',
            new_name='domain_metr_domain__050690_idx',
            old_name='domain_metr_domain__period_idx',
        ),
        migrations.RenameIndex(
            model_name='promptgroupmetricsnapshot',
            new_name='prompt_grou_prompt__fbbc0b_idx',
            old_name='prompt_grou_prompt__snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='promptgroupmetricsnapshot',
            new_name='prompt_grou_platfor_c45970_idx',
            old_name='prompt_grou_platform_snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='promptgroupmetricsnapshot',
            new_name='prompt_grou_snapsho_36008a_idx',
            old_name='prompt_grou_snapshot_visibility_idx',
        ),
        migrations.RenameIndex(
            model_name='promptgroupmetricsnapshot',
            new_name='prompt_grou_prompt__2e8b30_idx',
            old_name='prompt_grou_prompt__period_idx',
        ),
        migrations.RenameIndex(
            model_name='promptmetricsnapshot',
            new_name='prompt_metr_prompt__ea1a48_idx',
            old_name='prompt_metr_prompt__snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='promptmetricsnapshot',
            new_name='prompt_metr_platfor_8e7e40_idx',
            old_name='prompt_metr_platform_snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='promptmetricsnapshot',
            new_name='prompt_metr_snapsho_1a7268_idx',
            old_name='prompt_metr_snapshot_visibility_idx',
        ),
        migrations.RenameIndex(
            model_name='promptmetricsnapshot',
            new_name='prompt_metr_prompt__b9a272_idx',
            old_name='prompt_metr_prompt__period_idx',
        ),
    ]
