# Generated by Django 5.2 on 2025-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_domains_organis_fc59ac_idx_and_more'),
        ('prompts', '0002_remove_prompt_domain_remove_prompt_organisation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['group', 'track_status'], name='prompts_group_i_6e4021_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['group', 'type'], name='prompts_group_i_6fe0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['tracked_at'], name='prompts_tracked_5d9c14_idx'),
        ),
        migrations.AddIndex(
            model_name='promptanalytics',
            index=models.Index(fields=['prompt', 'platform', 'created_at'], name='prompt_anal_prompt__fa5de1_idx'),
        ),
        migrations.AddIndex(
            model_name='promptanalytics',
            index=models.Index(fields=['prompt', 'is_mention', '-position'], name='prompt_anal_prompt__7aefc6_idx'),
        ),
        migrations.AddIndex(
            model_name='promptanalytics',
            index=models.Index(fields=['platform', 'is_mention', 'created_at'], name='prompt_anal_platfor_9e5ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='promptanalytics',
            index=models.Index(fields=['prompt', '-sentiment_score'], name='prompt_anal_prompt__38da78_idx'),
        ),
        migrations.AddIndex(
            model_name='promptgroup',
            index=models.Index(fields=['domain', 'is_published'], name='prompt_grou_domain__c8169c_idx'),
        ),
        migrations.AddIndex(
            model_name='promptgroup',
            index=models.Index(fields=['domain', 'track_status'], name='prompt_grou_domain__d3e645_idx'),
        ),
        migrations.AddIndex(
            model_name='promptgroup',
            index=models.Index(fields=['domain', '-total_mentions'], name='prompt_grou_domain__972001_idx'),
        ),
    ]
