# Generated by Django 5.2 on 2025-10-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_is_mention'),
    ]

    operations = [
    ]
