# Generated by Django 4.2.26 on 2026-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_sweepguardstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='cited_pages',
            field=models.PositiveIntegerField(default=0, help_text='Distinct pages on this domain cited by AI (running total as at snapshot_date)'),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_citations',
            field=models.PositiveIntegerField(default=0, help_text="Citation URLs recorded within this snapshot's period"),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_cited_pages',
            field=models.PositiveIntegerField(default=0, help_text="Distinct domain-owned pages cited within this snapshot's period"),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_mentions',
            field=models.PositiveIntegerField(default=0, help_text="Mentions recorded within this snapshot's period"),
        ),
    ]
