# Generated by Django 5.2 on 2025-10-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_promptanalytics_track_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptanalytics',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this analytics is published and visible to users'),
        ),
        migrations.AddField(
            model_name='promptgroup',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this group is published and visible to users'),
        ),
    ]
