# Generated by Django 5.2 on 2025-10-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_prompt_prompts_group_i_6e4021_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='citations',
            new_name='citation_list',
        ),
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='competitor_mentions',
            new_name='competitor_mention_list',
        ),
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='position_history',
            new_name='position_history_list',
        ),
        migrations.RenameField(
            model_name='promptanalytics',
            old_name='key_topics',
            new_name='topic_list',
        ),
        migrations.RemoveField(
            model_name='promptanalytics',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='promptanalytics',
            name='sentiment_category',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Sentiment category (positive/neutral/negative)', max_length=10),
        ),
    ]
