# Generated by Django 5.2 on 2025-10-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_auto_20251024_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='average_position',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='is_mention',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='total_citations',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='total_mentions',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='visibility_score',
        ),
        migrations.AddField(
            model_name='prompt',
            name='last_tracked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the prompt was last tracked', null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='track_message',
            field=models.TextField(blank=True, help_text='Message or notes about the tracking status'),
        ),
    ]
