# Generated by Django 5.2 on 2026-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_prompt_analytics_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_avg_position',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Mean position over this period's mention rows (0 = unknown)", max_digits=8),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_avg_sentiment',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text="Mean sentiment (-1..1) over this period's mention rows", max_digits=4),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_mentioned_responses',
            field=models.PositiveIntegerField(default=0, help_text='Answers in this period that mentioned the brand'),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_own_cited_responses',
            field=models.PositiveIntegerField(default=0, help_text="Answers in this period that cited the brand's own domain"),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='period_responses',
            field=models.PositiveIntegerField(default=0, help_text='AI answers checked in this period (visibility denominator)'),
        ),
        migrations.AddField(
            model_name='domainmetricsnapshot',
            name='visibility_formula_version',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Which formula produced visibility_score. 0 = legacy MAX-normalised score with no recorded inputs; 1 = rate-based compute_visibility_score with the period_* inputs above. Readers must never compare across versions.'),
        ),
    ]
