# Generated by Django 5.2 on 2025-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_remove_prompt_average_position_and_more'),
    ]

    operations = [
        # Add is_mention field to PromptAnalytics
        migrations.AddField(
            model_name='promptanalytics',
            name='is_mention',
            field=models.BooleanField(default=False, help_text='Whether this analytics entry is a mention or not'),
        ),
        # Add position field to PromptAnalytics (replacing average_position)
        migrations.AddField(
            model_name='promptanalytics',
            name='position',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Position in search results', max_digits=8),
        ),
        # Remove visibility_score from PromptCluster
        migrations.RemoveField(
            model_name='promptcluster',
            name='visibility_score',
        ),
        # Remove average_position from PromptAnalytics
        migrations.RemoveField(
            model_name='promptanalytics',
            name='average_position',
        ),
        # Remove visibility_score from PromptAnalytics
        migrations.RemoveField(
            model_name='promptanalytics',
            name='visibility_score',
        ),
    ]
