# Generated by Django 5.2 on 2025-10-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_auto_20251024_1022'),
    ]

    operations = [
        # Add citations field to PromptAnalytics
        migrations.AddField(
            model_name='promptanalytics',
            name='citations',
            field=models.JSONField(blank=True, default=list, help_text='List of citations with text and source URLs'),
        ),
    ]
