# Generated by Django 5.2 on 2025-10-31 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0004_delete_detectedmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(default=list)),
                ('mentions', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('platforms', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='domains.domain')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['-mentions'],
            },
        ),
        migrations.CreateModel(
            name='TopicAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='topics.topic')),
            ],
            options={
                'db_table': 'topic_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TopicPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('relevance_score', models.IntegerField(default=0)),
                ('search_volume', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='topics.topic')),
            ],
            options={
                'db_table': 'topic_prompts',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-mentions'], name='topics_domain__063178_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['topic', 'timestamp'], name='topic_analy_topic_i_a44f54_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprompt',
            index=models.Index(fields=['topic', '-relevance_score'], name='topic_promp_topic_i_0a10c5_idx'),
        ),
    ]
