# Generated by Django 5.2 on 2025-11-25 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('keywords', '0001_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keyword_list', models.JSONField(blank=True, default=list)),
                ('total_mentions', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('platform_list', models.JSONField(blank=True, default=list)),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Processing status: INIT/SCHD/PROC/COMP/FAIL', max_length=10)),
                ('track_message', models.TextField(blank=True, help_text='Status message for tracking', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when tracking status was last updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='domains.domain')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['-total_mentions'],
            },
        ),
        migrations.CreateModel(
            name='TopicAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='All Platforms', help_text="AI platform name (e.g., ChatGPT, Claude, Perplexity). Use 'All Platforms' for aggregated data.", max_length=100)),
                ('total_mentions', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_analytics', to='topics.topic')),
            ],
            options={
                'db_table': 'topic_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Relevance score of keyword to topic (0-100)', max_digits=5)),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('COMP', 'Completed')], default='INIT', help_text='Processing status: INIT/COMP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_keywords', to='keywords.keyword')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_keywords', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Topic Keyword',
                'verbose_name_plural': 'Topic Keywords',
                'db_table': 'topic_keywords',
            },
        ),
        migrations.CreateModel(
            name='TopicPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('relevance_score', models.IntegerField(default=0)),
                ('search_volume', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('platform_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_prompts', to='topics.topic')),
            ],
            options={
                'db_table': 'topic_prompts',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='KeywordAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='AI platform name (e.g., ChatGPT, Claude, Perplexity)', max_length=100)),
                ('mentions', models.IntegerField(default=0, help_text='Number of mentions of this keyword')),
                ('avg_position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average position in search results', max_digits=8)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Visibility score calculated from average position', max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Average sentiment score (-1.00 to 1.00)', max_digits=5)),
                ('timestamp', models.DateField(help_text='Date of this analytics snapshot')),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', help_text='Processing status: INIT/SCHD/PROC/COMP/FAIL', max_length=10)),
                ('track_message', models.TextField(blank=True, help_text='Status message for tracking', null=True)),
                ('tracked_at', models.DateTimeField(blank=True, help_text='Timestamp when tracking status was last updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_analytics', to='keywords.keyword')),
            ],
            options={
                'verbose_name': 'Keyword Analytics',
                'verbose_name_plural': 'Keyword Analytics',
                'db_table': 'keyword_analytics',
                'ordering': ['-timestamp', '-mentions'],
                'indexes': [models.Index(fields=['keyword', 'platform', 'timestamp'], name='keyword_ana_keyword_70ab15_idx'), models.Index(fields=['keyword', 'track_status'], name='keyword_ana_keyword_bd3103_idx'), models.Index(fields=['platform', 'timestamp'], name='keyword_ana_platfor_589e31_idx'), models.Index(fields=['timestamp', '-mentions'], name='keyword_ana_timesta_48114a_idx')],
                'unique_together': {('keyword', 'platform', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PromptKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Relevance score of prompt to keyword (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_keywords', to='keywords.keyword')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_keywords', to='prompts.prompt')),
            ],
            options={
                'verbose_name': 'Prompt Keyword',
                'verbose_name_plural': 'Prompt Keywords',
                'db_table': 'prompt_keywords',
                'indexes': [models.Index(fields=['prompt', 'keyword'], name='prompt_keyw_prompt__e781d7_idx'), models.Index(fields=['keyword', 'prompt'], name='prompt_keyw_keyword_032f06_idx'), models.Index(fields=['keyword', '-relevance_score'], name='prompt_keyw_keyword_eb19b2_idx')],
                'unique_together': {('prompt', 'keyword')},
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-total_mentions'], name='topics_domain__d8ed12_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-visibility_score'], name='topics_domain__4c93a4_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-trend_percentage'], name='topics_domain__7fc5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', 'created_at'], name='topics_domain__5d893a_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', 'track_status'], name='topics_domain__c4c47e_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['topic', 'platform', 'timestamp'], name='topic_analy_topic_i_2cd0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['topic', '-timestamp', '-total_mentions'], name='topic_analy_topic_i_0de881_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['platform', 'timestamp'], name='topic_analy_platfor_bea7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['timestamp'], name='topic_analy_timesta_bd9c42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicanalytics',
            unique_together={('topic', 'platform', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['topic', 'track_status'], name='topic_keywo_topic_i_96d3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['keyword', 'track_status'], name='topic_keywo_keyword_45922a_idx'),
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['topic', '-relevance_score'], name='topic_keywo_topic_i_c6ebc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topickeyword',
            unique_together={('topic', 'keyword')},
        ),
        migrations.AddIndex(
            model_name='topicprompt',
            index=models.Index(fields=['topic', '-relevance_score'], name='topic_promp_topic_i_0a10c5_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprompt',
            index=models.Index(fields=['search_volume', '-relevance_score'], name='topic_promp_search__be488d_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprompt',
            index=models.Index(fields=['topic', 'search_volume'], name='topic_promp_topic_i_3ca795_idx'),
        ),
    ]
