# Generated by Django 5.2 on 2025-10-31 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_domains_organis_fc59ac_idx_and_more'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-visibility_score'], name='topics_domain__4c93a4_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-trend_percentage'], name='topics_domain__7fc5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', 'created_at'], name='topics_domain__5d893a_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['topic', '-timestamp', '-mentions'], name='topic_analy_topic_i_6bf30b_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['timestamp'], name='topic_analy_timesta_bd9c42_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprompt',
            index=models.Index(fields=['search_volume', '-relevance_score'], name='topic_promp_search__be488d_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprompt',
            index=models.Index(fields=['topic', 'search_volume'], name='topic_promp_topic_i_3ca795_idx'),
        ),
    ]
