# Generated by Django 5.2 on 2025-10-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_remove_domain_domains_track_s_14ee58_idx_and_more'),
        ('topics', '0002_topic_topics_domain__4c93a4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-total_mentions']},
        ),
        migrations.RemoveIndex(
            model_name='topic',
            name='topics_domain__063178_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicanalytics',
            name='topic_analy_topic_i_6bf30b_idx',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='sentiment',
            new_name='sentiment_score',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='mentions',
            new_name='total_mentions',
        ),
        migrations.RenameField(
            model_name='topicanalytics',
            old_name='sentiment',
            new_name='sentiment_score',
        ),
        migrations.RenameField(
            model_name='topicanalytics',
            old_name='mentions',
            new_name='total_mentions',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='topicprompt',
            name='platforms',
        ),
        migrations.AddField(
            model_name='topic',
            name='keyword_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='platform_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topicprompt',
            name='platform_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='topicanalytics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_analytics', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='topicprompt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_prompts', to='topics.topic'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['domain', '-total_mentions'], name='topics_domain__d8ed12_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalytics',
            index=models.Index(fields=['topic', '-timestamp', '-total_mentions'], name='topic_analy_topic_i_0de881_idx'),
        ),
    ]
