# Generated by Django 5.2 on 2025-10-31 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0004_delete_detectedmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('mentions', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('share_of_voice', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='domains.domain')),
            ],
            options={
                'db_table': 'competitors',
                'ordering': ['-mentions'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('mentions', models.IntegerField(default=0)),
                ('position', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='competitors.competitor')),
            ],
            options={
                'db_table': 'competitor_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('mentions', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('your_mentions', models.IntegerField(default=0)),
                ('platforms', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='competitors.competitor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competitor_prompts',
                'ordering': ['-mentions'],
            },
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain'], name='competitors_domain__3c12bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together={('name', 'domain')},
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['competitor', 'timestamp'], name='competitor__competi_a6e53a_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['platform', 'timestamp'], name='competitor__platfor_7ec755_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', '-mentions'], name='competitor__competi_4134a1_idx'),
        ),
    ]
