# Generated by Django 5.2 on 2025-11-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Complete'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('tracked_at', models.DateTimeField(blank=True, null=True)),
                ('total_mentions', models.IntegerField(default=0)),
                ('total_citations', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('share_of_voice_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='domains.domain')),
            ],
            options={
                'db_table': 'competitors',
                'ordering': ['-total_mentions'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('total_mentions', models.IntegerField(default=0)),
                ('position', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analytics', to='competitors.competitor')),
            ],
            options={
                'db_table': 'competitor_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_mentions', models.IntegerField(default=0)),
                ('total_citations', models.IntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_position', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('share_of_voice_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('track_status', models.CharField(blank=True, max_length=4, null=True)),
                ('platform_metrics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='competitors.competitor')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_metric_snapshots', to='domains.domain')),
            ],
            options={
                'db_table': 'competitor_metric_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('total_mentions', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('your_mentions', models.IntegerField(default=0)),
                ('platform_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prompts', to='competitors.competitor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competitor_prompts',
                'ordering': ['-total_mentions'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPromptAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Complete'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('tracked_at', models.DateTimeField(blank=True, null=True)),
                ('is_mentioned', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('sentiment_category', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('citation_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analytics', to='competitors.competitor')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analytics', to='prompts.prompt')),
            ],
            options={
                'db_table': 'competitor_prompt_analytics',
                'ordering': ['competitor', 'position'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('snapshot_version', models.CharField(max_length=255)),
                ('insight_data', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_insights', to='domains.domain')),
            ],
            options={
                'db_table': 'competitive_insights',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['domain', '-generated_at'], name='competitive_domain__cd8747_idx'), models.Index(fields=['domain', 'snapshot_version'], name='competitive_domain__df85ca_idx'), models.Index(fields=['impact'], name='competitive_impact_b8d10c_idx')],
                'unique_together': {('domain', 'snapshot_version', 'title')},
            },
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain'], name='competitors_domain__3c12bc_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['track_status', 'modified_at'], name='competitors_track_s_ebbbba_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-share_of_voice_percentage'], name='competitors_domain__4daa12_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-visibility_score'], name='competitors_domain__8e22e1_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-total_mentions'], name='competitors_domain__935e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', 'created_at'], name='competitors_domain__0f8cc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together={('name', 'domain')},
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['competitor', 'timestamp'], name='competitor__competi_a6e53a_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['platform', 'timestamp'], name='competitor__platfor_7ec755_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['competitor', 'platform', '-timestamp'], name='competitor__competi_8891f0_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['timestamp', '-total_mentions'], name='competitor__timesta_da7f68_idx'),
        ),
        migrations.AddIndex(
            model_name='competitormetricsnapshot',
            index=models.Index(fields=['competitor', '-timestamp'], name='competitor__competi_01ed3a_idx'),
        ),
        migrations.AddIndex(
            model_name='competitormetricsnapshot',
            index=models.Index(fields=['domain', '-timestamp'], name='competitor__domain__bab52c_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', '-total_mentions'], name='competitor__competi_9a5b85_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', '-position'], name='competitor__competi_8e1626_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['your_mentions', '-total_mentions'], name='competitor__your_me_65a8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', 'created_at'], name='competitor__competi_7f6848_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'track_status'], name='competitor__competi_530806_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['prompt', 'track_status'], name='competitor__prompt__cfb536_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['track_status', 'modified_at'], name='competitor__track_s_185e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'is_mentioned'], name='competitor__competi_cf315a_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', '-position'], name='competitor__competi_350114_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'platform', 'tracked_at'], name='competitor__competi_9d9913_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'is_mentioned', '-mention_count'], name='competitor__competi_c08f60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitorpromptanalytics',
            unique_together={('competitor', 'prompt')},
        ),
    ]
