# Generated by Django 5.2 on 2025-10-31 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
        ('domains', '0005_domain_domains_organis_fc59ac_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-share_of_voice'], name='competitors_domain__12da31_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-visibility_score'], name='competitors_domain__8e22e1_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-mentions'], name='competitors_domain__905454_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', 'created_at'], name='competitors_domain__0f8cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['competitor', 'platform', '-timestamp'], name='competitor__competi_8891f0_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['timestamp', '-mentions'], name='competitor__timesta_f79973_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', '-position'], name='competitor__competi_8e1626_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['your_mentions', '-mentions'], name='competitor__your_me_fbfb18_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', 'created_at'], name='competitor__competi_7f6848_idx'),
        ),
    ]
