# Generated by Django 5.2 on 2025-11-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
        ('domains', '0001_initial'),
        ('prompts', '0002_promptgroup_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPromptAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_status', models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Complete'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('tracked_at', models.DateTimeField(blank=True, null=True)),
                ('is_mentioned', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('sentiment_category', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('citation_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competitor_prompt_analytics',
                'ordering': ['competitor', 'position'],
            },
        ),
        migrations.AddField(
            model_name='competitor',
            name='track_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='track_status',
            field=models.CharField(choices=[('INIT', 'Initial'), ('SCHD', 'Scheduled'), ('PROC', 'Processing'), ('COMP', 'Complete'), ('FAIL', 'Failed')], default='INIT', max_length=4),
        ),
        migrations.AddField(
            model_name='competitor',
            name='tracked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['track_status', 'modified_at'], name='competitors_track_s_ebbbba_idx'),
        ),
        migrations.AddField(
            model_name='competitorpromptanalytics',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analytics', to='competitors.competitor'),
        ),
        migrations.AddField(
            model_name='competitorpromptanalytics',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analytics', to='prompts.prompt'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'track_status'], name='competitor__competi_530806_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['prompt', 'track_status'], name='competitor__prompt__cfb536_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['track_status', 'modified_at'], name='competitor__track_s_185e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'is_mentioned'], name='competitor__competi_cf315a_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', '-position'], name='competitor__competi_350114_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'platform', 'tracked_at'], name='competitor__competi_9d9913_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitorpromptanalytics',
            unique_together={('competitor', 'prompt')},
        ),
    ]
