# Generated by Django 4.2.26 on 2025-11-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_competitormetricsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitormetricsnapshot',
            name='platform_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='competitormetricsnapshot',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='competitors.competitor'),
        ),
    ]
