# Generated by Django 5.2 on 2025-10-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_competitor_competitors_domain__12da31_idx_and_more'),
        ('domains', '0006_remove_domain_domains_track_s_14ee58_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ['-total_mentions']},
        ),
        migrations.AlterModelOptions(
            name='competitorprompt',
            options={'ordering': ['-total_mentions']},
        ),
        migrations.RemoveIndex(
            model_name='competitor',
            name='competitors_domain__12da31_idx',
        ),
        migrations.RemoveIndex(
            model_name='competitor',
            name='competitors_domain__905454_idx',
        ),
        migrations.RemoveIndex(
            model_name='competitoranalytics',
            name='competitor__timesta_f79973_idx',
        ),
        migrations.RemoveIndex(
            model_name='competitorprompt',
            name='competitor__competi_4134a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='competitorprompt',
            name='competitor__your_me_fbfb18_idx',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='sentiment',
            new_name='sentiment_score',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='share_of_voice',
            new_name='share_of_voice_percentage',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='mentions',
            new_name='total_mentions',
        ),
        migrations.RenameField(
            model_name='competitoranalytics',
            old_name='sentiment',
            new_name='sentiment_score',
        ),
        migrations.RenameField(
            model_name='competitoranalytics',
            old_name='mentions',
            new_name='total_mentions',
        ),
        migrations.RenameField(
            model_name='competitorprompt',
            old_name='mentions',
            new_name='total_mentions',
        ),
        migrations.RemoveField(
            model_name='competitorprompt',
            name='platforms',
        ),
        migrations.AddField(
            model_name='competitorprompt',
            name='platform_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='competitoranalytics',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analytics', to='competitors.competitor'),
        ),
        migrations.AlterField(
            model_name='competitorprompt',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prompts', to='competitors.competitor'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-share_of_voice_percentage'], name='competitors_domain__4daa12_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain', '-total_mentions'], name='competitors_domain__935e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['timestamp', '-total_mentions'], name='competitor__timesta_da7f68_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['competitor', '-total_mentions'], name='competitor__competi_9a5b85_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorprompt',
            index=models.Index(fields=['your_mentions', '-total_mentions'], name='competitor__your_me_65a8ee_idx'),
        ),
    ]
