# Generated by Django 4.2.26 on 2025-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0004_competitiveinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='total_citations',
            field=models.IntegerField(default=0),
        ),
    ]
