# Generated by Django 4.2.26 on 2025-11-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0005_competitor_total_citations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='competitorpromptanalytics',
            index=models.Index(fields=['competitor', 'is_mentioned', '-mention_count'], name='competitor__competi_c08f60_idx'),
        ),
    ]
