"""
Django settings for llm_monitor_engine project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-j-ftjg4gs$tc&hneu1h4pr^qsn1g@$+ttp3s$*^)h*o^2j9sv^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shared_models',
    'integrations',  # Engine's integrations app
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llm_monitor_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llm_monitor_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='llm_monitor'),
        'USER': config('DB_USER', default='arun'),
        'PASSWORD': config('DB_PASSWORD', default='admin'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'gssencmode': 'disable',  # Disable GSSAPI to prevent macOS fork crashes
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 600,  # Connection pooling to reduce reconnections
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'PAGE_SIZE': config('REST_FRAMEWORK_PAGE_SIZE', default=20, cast=int),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Domain processing settings
MAX_CONCURRENT_DOMAINS = config('MAX_CONCURRENT_DOMAINS', default=10, cast=int)
MAX_CONCURRENT_PROMPT_ANALYTICS = config('MAX_CONCURRENT_PROMPT_ANALYTICS', default=10, cast=int)
MAX_CONCURRENT_COMPETITOR_PROMPTS = config('MAX_CONCURRENT_COMPETITOR_PROMPTS', default=10, cast=int)

# Prompt engine knobs
# Number of prompts to generate per keyword
PROMPT_MIN_COUNT = config('PROMPT_MIN_COUNT', default=2, cast=int)
OPENAI_API_KEY = config('OPENAI_API_KEY', default=None)
GEMINI_API_KEY = config('GEMINI_API_KEY', default=None)
PERPLEXITY_API_KEY = config('PERPLEXITY_API_KEY', default=None)

# ScrapingDog API Configuration (still used by misinformation crawler — /scrape endpoint)
SCRAPINGDOG_API_KEY = config('SCRAPINGDOG_API_KEY', default=None)

# DataBlue API Configuration (SEO keyword ranking / SERP — /v1/data/google/search)
DATABLUE_API_KEY = config('DATABLUE_API_KEY', default='')
DATABLUE_NUM_RESULTS = config('DATABLUE_NUM_RESULTS', default=50, cast=int)
DATABLUE_CONCURRENCY = config('DATABLUE_CONCURRENCY', default=100, cast=int)
DATABLUE_TIMEOUT = config('DATABLUE_TIMEOUT', default=60, cast=int)

# ==================== EMAIL CONFIGURATION (MAILGUN HTTP API) ====================
# Mailgun HTTP API Configuration for report email delivery
MAILGUN_API_KEY = config('MAILGUN_API_KEY', default='')
MAILGUN_DOMAIN = config('MAILGUN_DOMAIN', default='')
MAILGUN_API_URL = config('MAILGUN_API_URL', default='https://api.mailgun.net/v3')

# Sender Email
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='LLM Monitor <noreply@sandbox.mailgun.org>'
)

# Frontend URL for email links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8080')

# Email timeout (seconds)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)
# ==================== END EMAIL CONFIGURATION ====================

# Backend API URL for report generation
BACKEND_API_URL = config('BACKEND_API_URL', default='http://localhost:8000')

# Platform tracking settings (lowercase keys, converted to proper case in code)
# Default: 'chatgpt,gemini' - enables both ChatGPT and Google Gemini
ENABLED_PLATFORMS = config('ENABLED_PLATFORMS', default='chatgpt,gemini', cast=lambda v: [p.strip() for p in v.split(',')])

# Celery settings (for background processing)
# Use a dedicated Redis DB index for engine tasks (e.g., DB 5)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/5')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/5')
CELERY_ACCEPT_CONTENT = [config('CELERY_ACCEPT_CONTENT', default='json')]
CELERY_TASK_SERIALIZER = config('CELERY_TASK_SERIALIZER', default='json')
CELERY_RESULT_SERIALIZER = config('CELERY_RESULT_SERIALIZER', default='json')
CELERY_TIMEZONE = TIME_ZONE

# Route SEO ranking tasks to a dedicated queue so user-triggered refreshes
# don't get stuck behind the prompt/competitor analytics backlog on the
# default queue (which can pile up to thousands of tasks during scheduler
# bursts). Other tasks keep their existing routing — the default 'celery'
# queue. A dedicated worker must be running with `-Q seo` for SEO tasks to
# be processed; see start-celery.sh.
CELERY_TASK_ROUTES = {
    'core.processing_tasks.process_seo_domain_task': {'queue': 'seo'},
    'core.processing_tasks.process_seo_keyword_task': {'queue': 'seo'},
    'core.processing_tasks.seo_rankings_daily_scheduler': {'queue': 'seo'},
}

# Auto-expire task results after 1 day (reduce Redis usage); set to None if not needed
from datetime import timedelta
CELERY_RESULT_EXPIRES = timedelta(days=config('CELERY_RESULT_EXPIRES_DAYS', default=1, cast=int))

# Celery Beat schedule: tick every 15 seconds to dispatch domain processing
CELERY_BEAT_SCHEDULE = {
    'domain-scheduler-tick-every-15s': {
        'task': 'core.processing_tasks.scheduler_tick',
        'schedule': config('CELERY_BEAT_SCHEDULE_DOMAIN', default=15.0, cast=float),
    },
    'prompt-analytics-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_prompt_analytics_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_PROMPT_ANALYTICS', default=15.0, cast=float),
    },
    'topic-analytics-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_topic_analytics_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_TOPIC_ANALYTICS', default=15.0, cast=float),
    },
    'integration-insights-scheduler-every-hour': {
        'task': 'core.processing_tasks.process_integration_insights_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_INTEGRATION_INSIGHTS', default=15.0, cast=float),  # Every 15 seconds for testing (change to 3600.0 for production)
    },
    'competitor-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_competitor_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_COMPETITOR', default=15.0, cast=float),
    },
    'report-email-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_report_email_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_REPORT_EMAIL', default=15.0, cast=float),
    },
    # Weekly batch reprocessing (off-peak). Adjust crontab as needed.
    'weekly-prompts-batch': {
        'task': 'core.processing_tasks.schedule_weekly_prompt_batches',
        'schedule': crontab(day_of_week='sun', hour=0, minute=0),
    },
    'weekly-competitors-batch': {
        'task': 'core.processing_tasks.schedule_weekly_competitor_batches',
        'schedule': crontab(day_of_week='sun', hour=1, minute=0),
    },
    'cmsmanager-scheduler-every-60s': {
        'task': 'core.processing_tasks.process_cmsmanager_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_CMSMANAGER', default=60.0, cast=float),
    },
    # Daily SEO keyword ranking refresh at 2:00 AM
    'seo-rankings-daily-refresh': {
        'task': 'core.processing_tasks.seo_rankings_daily_scheduler',
        'schedule': crontab(hour=2, minute=0),
    },
    # Daily GA + GSC monthly insight scheduling for MOM/YOY in reports (runs at 1:00 AM)
    'monthly-insights-daily-schedule': {
        'task': 'core.processing_tasks.schedule_all_monthly_insights_task',
        'schedule': crontab(hour=1, minute=0),
    },
}
