"""
Django settings for llm_monitor_engine project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j-ftjg4gs$tc&hneu1h4pr^qsn1g@$+ttp3s$*^)h*o^2j9sv^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shared_models',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llm_monitor_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llm_monitor_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'llm_monitor',
        'USER': 'arun',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'PAGE_SIZE': 20,
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Domain processing settings
MAX_CONCURRENT_DOMAINS = 10
MAX_CONCURRENT_PROMPT_ANALYTICS = 10

# Prompt engine knobs
# How many keywords to fetch from DataForSEO per domain
KEYWORD_EXTRACT_LIMIT = 3
# Minimum number of distinct prompts to produce overall
PROMPT_MIN_COUNT = 1
DATAFORSEO_USERNAME = "abulkalam.serpple@gmail.com"
DATAFORSEO_PASSWORD = "e816abfef0ba5fa5"
OPENAI_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyD0tOPBuYGk4NEIdCEMKFjszkQWLBiyvAY"
PERPLEXITY_API_KEY = "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"

# Celery settings (for background processing)
# Use a dedicated Redis DB index for engine tasks (e.g., DB 5)
CELERY_BROKER_URL = 'redis://localhost:6379/5'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/5'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Auto-expire task results after 1 day (reduce Redis usage); set to None if not needed
from datetime import timedelta
CELERY_RESULT_EXPIRES = timedelta(days=1)

# Celery Beat schedule: tick every 15 seconds to dispatch domain processing
CELERY_BEAT_SCHEDULE = {
    'domain-scheduler-tick-every-15s': {
        'task': 'core.processing_tasks.scheduler_tick',
        'schedule': 15.0,
    },
    'prompt-analytics-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_prompt_analytics_scheduler',
        'schedule': 15.0,
    },
}
