"""
Django settings for llm_monitor_engine project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-j-ftjg4gs$tc&hneu1h4pr^qsn1g@$+ttp3s$*^)h*o^2j9sv^')

# Secret used to encrypt/decrypt per-organisation BYOK API keys at rest.
# MUST match the backend's API_KEY_ENCRYPTION_SECRET, otherwise the engine cannot
# decrypt the keys the backend stored. The default mirrors the backend default
# (which equals the backend SECRET_KEY default) so a default-config deployment
# resolves keys correctly; override via env in production (same value in both).
API_KEY_ENCRYPTION_SECRET = config(
    'API_KEY_ENCRYPTION_SECRET',
    default='django-insecure-1^ql#^w)r=70(!w2s-m9(y)y8ux!0yp3wniaeylu^z5u#pgy8q',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shared_models',
    'integrations',  # Engine's integrations app
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llm_monitor_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llm_monitor_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='llm_monitor'),
        'USER': config('DB_USER', default='arun'),
        'PASSWORD': config('DB_PASSWORD', default='admin'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'gssencmode': 'disable',  # Disable GSSAPI to prevent macOS fork crashes
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 600,  # Connection pooling to reduce reconnections
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'PAGE_SIZE': config('REST_FRAMEWORK_PAGE_SIZE', default=20, cast=int),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Domain processing settings
MAX_CONCURRENT_DOMAINS = config('MAX_CONCURRENT_DOMAINS', default=10, cast=int)
MAX_CONCURRENT_PROMPT_ANALYTICS = config('MAX_CONCURRENT_PROMPT_ANALYTICS', default=10, cast=int)
MAX_CONCURRENT_COMPETITOR_PROMPTS = config('MAX_CONCURRENT_COMPETITOR_PROMPTS', default=10, cast=int)

# Prompt engine knobs
# Number of prompts to generate per keyword
PROMPT_MIN_COUNT = config('PROMPT_MIN_COUNT', default=2, cast=int)
OPENAI_API_KEY = config('OPENAI_API_KEY', default=None)
GEMINI_API_KEY = config('GEMINI_API_KEY', default=None)
PERPLEXITY_API_KEY = config('PERPLEXITY_API_KEY', default=None)
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default=None)
XAI_API_KEY = config('XAI_API_KEY', default=None)
DEEPSEEK_API_KEY = config('DEEPSEEK_API_KEY', default=None)

# ============== OPENROUTER (ChatGPT + Claude + Perplexity transport) ==============
# ChatGPT, Claude and Perplexity are no longer called through their vendors'
# APIs directly — every such call is routed via OpenRouter's OpenAI-compatible
# endpoint (Claude through the adapter in core/services/openrouter_client.py),
# authenticated with OPENROUTER_API_KEY. OPENAI_API_KEY, ANTHROPIC_API_KEY and
# PERPLEXITY_API_KEY above are now unused by those paths and are retained only
# so existing deployments keep loading; per-org OpenAI/Anthropic/Perplexity BYOK
# keys are ignored for them until an openrouter_api_key column exists on
# Organisation. See OPENROUTER_ROUTED in core/services/api_key_service.py.
OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default=None)
OPENROUTER_BASE_URL = config('OPENROUTER_BASE_URL', default='https://openrouter.ai/api/v1')
# Optional attribution headers shown on OpenRouter's public leaderboards.
OPENROUTER_SITE_URL = config('OPENROUTER_SITE_URL', default=None)
OPENROUTER_SITE_TITLE = config('OPENROUTER_SITE_TITLE', default=None)

# LLM web-search grounding — when enabled, each provider's prompt-analytics call
# uses that provider's live web-search tool so responses reflect the *current*
# date/year (matching real ChatGPT/Claude/Gemini/Grok UIs). If a provider's
# Responses/Search API errors out or isn't available, the code falls back to the
# pre-existing chat-completions path automatically — set any of these to False to
# disable grounding for that provider without changing code.
# ChatGPT now runs on OpenRouter, whose `web` plugin answers the web_search tool
# request in place of OpenAI's native one. Same on/off switch, different search
# backend, billed per query on top of token cost.
OPENAI_CHATGPT_WEB_SEARCH = config('OPENAI_CHATGPT_WEB_SEARCH', default=True, cast=bool)
# OpenRouter model slug, NOT the bare 'gpt-4o' the direct OpenAI API takes.
# Deliberately the SAME slug as OPENROUTER_INTERNAL_MODEL below: the platform
# runs one model for every call, measured and internal alike. Kept as its own
# setting so the two can be split again from .env without a deploy.
#
# NOTE: gpt-5-mini is a reasoning model — see LLM_MAX_OUTPUT_TOKENS, whose
# ceiling has to cover the hidden reasoning tokens this model spends before it
# emits any text.
OPENAI_CHATGPT_MODEL = config('OPENAI_CHATGPT_MODEL', default='openai/gpt-5-mini')
# Claude now runs on OpenRouter, whose `web` plugin replaces Anthropic's native
# web_search tool. Same on/off switch, different search backend — see
# core/services/openrouter_client.py. Billed per query on top of token cost.
ANTHROPIC_WEB_SEARCH = config('ANTHROPIC_WEB_SEARCH', default=True, cast=bool)
# OpenRouter model slug, not an Anthropic model id.
ANTHROPIC_MODEL = config('ANTHROPIC_MODEL', default='anthropic/claude-sonnet-5')
# Perplexity also runs on OpenRouter now, so this is an OpenRouter model slug
# ("perplexity/sonar"), NOT the bare "sonar" the direct Perplexity API takes.
# Web search is built into Sonar itself, so there is no separate search toggle.
PERPLEXITY_MODEL = config('PERPLEXITY_MODEL', default='perplexity/sonar')
XAI_WEB_SEARCH = config('XAI_WEB_SEARCH', default=True, cast=bool)
XAI_MODEL = config('XAI_MODEL', default='grok-2-latest')
GEMINI_WEB_SEARCH = config('GEMINI_WEB_SEARCH', default=True, cast=bool)
# gemini-2.0-flash is discontinued (returns HTTP 404). Default to a current model.
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-flash-latest')
DEEPSEEK_MODEL = config('DEEPSEEK_MODEL', default='deepseek-chat')

# Ceiling on the generated answer length for EVERY pipeline LLM call (was
# hardcoded at 3000 in nine places).
#
# This is a SAFETY CEILING, NOT a cost saving. Measured on prod 2026-07-23 over
# 8 real prompts on gpt-4o: output was 455-640 tokens (median 579) and every
# call ended with finish_reason='stop' — the 3000 cap was never once reached.
# You are billed for tokens actually generated, so lowering the cap saves
# nothing here; the cost driver is the NUMBER of calls, not their length.
#
# RAISED 1500 -> 8000 when the tracked call moved to gpt-5-mini. That is a
# REASONING model: it spends hidden reasoning tokens against this same ceiling
# before emitting a single character of the answer, AND it writes far longer
# answers than gpt-4o did. Measured on prod against OpenRouter 2026-07-27 using
# the REAL analytics prompt (_build_analytics_user_prompt), not a toy one:
#   max_tokens=3000 -> 1792 reasoning, finish_reason='length' (TRUNCATED)
#   max_tokens=5000 -> 1984 reasoning, finish_reason='length' (TRUNCATED)
#   max_tokens=8000 -> 1216 reasoning, finish_reason='stop', 4228 total (OK)
# Reasoning alone varies 1200-2000 tokens run to run, so the headroom is not
# optional. Below ~6000 the answer truncates mid-sentence, dropping the source
# list at the end — silently deflating the Citations page rather than erroring.
#
# This is a CEILING, not a target: billing follows tokens actually generated
# (4228 above, not 8000), and the non-reasoning providers (Perplexity, Claude,
# Grok, DeepSeek) still stop early and cost nothing extra for the higher cap.
# Tunable from .env without a deploy.
LLM_MAX_OUTPUT_TOKENS = config('LLM_MAX_OUTPUT_TOKENS', default=8000, cast=int)

# Model for INTERNAL LLM work (topic extraction, prompt generation, competitor
# insight summaries) — output nobody reads as "what ChatGPT says about my
# brand", so it does not need the flagship model. The mention-tracking call
# deliberately keeps OPENAI_CHATGPT_MODEL: that one exists to measure what real
# ChatGPT users are told, so cheapening it would change the measurement itself.
# Superseded by OPENROUTER_INTERNAL_MODEL below; retained so deployments that
# still set it keep loading.
OPENAI_INTERNAL_MODEL = config('OPENAI_INTERNAL_MODEL', default='gpt-4o-mini')

# Every LLM call in the platform — internal support work AND the tracked ChatGPT
# measurement — runs through OpenRouter on this one slug. OPENAI_CHATGPT_MODEL
# above defaults to the same value; they stay separate settings only so the
# measured call can be pointed at a different model from .env if the measurement
# ever needs to diverge from the internal one again.
OPENROUTER_INTERNAL_MODEL = config('OPENROUTER_INTERNAL_MODEL', default='openai/gpt-5-mini')

# ==================== GEMINI BACKEND: AI Studio vs Vertex AI ====================
# 'aistudio' (default) keeps the API-key path via google.generativeai.
# 'vertex' routes Gemini through Vertex AI on a GCP project so calls bill against
# that project's billing account (e.g. free-trial credit) instead of an API key.
# Reverting is a single env change - GEMINI_BACKEND=aistudio - with no code change.
#
# Vertex auth uses Application Default Credentials, NOT an API key: point
# GOOGLE_APPLICATION_CREDENTIALS at a service-account JSON whose account holds the
# "Vertex AI User" role on VERTEX_PROJECT. Never commit that file.
GEMINI_BACKEND = config('GEMINI_BACKEND', default='aistudio')
# Vertex requires concrete model IDs; AI Studio's '-latest' aliases do not resolve
# there, and gemini-2.0-* returns 404 on newer projects - verified against
# gen-lang-client-0074241504, where only the 2.5 family is served.
VERTEX_GEMINI_MODEL = config('VERTEX_GEMINI_MODEL', default='gemini-2.5-flash')
VERTEX_PROJECT = config('VERTEX_PROJECT', default=None)
VERTEX_LOCATION = config('VERTEX_LOCATION', default='us-central1')
# Gemini 2.5 enables "thinking" by default and bills those tokens as output. A
# measured call spent 1150 thinking tokens to produce 91 tokens of answer, which
# at pipeline volume is a large cost with no benefit for mention detection.
# 0 disables thinking; a positive value caps it; -1 leaves the model default.
VERTEX_THINKING_BUDGET = config('VERTEX_THINKING_BUDGET', default=0, cast=int)
# google-genai resolves credentials from the OS environment, but decouple only
# exposes .env through config(), so a GOOGLE_APPLICATION_CREDENTIALS entry there
# would never reach the SDK. Bridge it across without clobbering a real env var.
_VERTEX_CREDENTIALS = config('GOOGLE_APPLICATION_CREDENTIALS', default=None)
if _VERTEX_CREDENTIALS:
    import os as _os
    _os.environ.setdefault('GOOGLE_APPLICATION_CREDENTIALS', _VERTEX_CREDENTIALS)

# ==================== LLM QUOTA / CREDIT ALERTS ====================
# Probes every configured paid key and emails recipients when a key is
# depleted/erroring or recovers. Recipients are .env-configurable.
QUOTA_ALERT_ENABLED = config('QUOTA_ALERT_ENABLED', default=True, cast=bool)
QUOTA_ALERT_RECIPIENTS = config(
    'QUOTA_ALERT_RECIPIENTS', default='',
    cast=lambda v: [e.strip() for e in v.split(',') if e.strip()]
)
QUOTA_ALERT_REPEAT_HOURS = config('QUOTA_ALERT_REPEAT_HOURS', default=12, cast=int)
# A provider must look depleted on this many consecutive checks before it is
# alerted on, so one bad probe cannot flap a key in/out of the alert set.
QUOTA_ALERT_CONFIRM_RUNS = config('QUOTA_ALERT_CONFIRM_RUNS', default=2, cast=int)
# Hard floor between any two quota alert emails. Backstop against alert floods
# (duplicate schedulers, flapping providers, a failing mailer). 0 disables it.
QUOTA_ALERT_MIN_INTERVAL_MINUTES = config('QUOTA_ALERT_MIN_INTERVAL_MINUTES', default=60, cast=int)
# Also email a one-time "credits restored" note when a depleted provider recovers.
QUOTA_ALERT_ON_RECOVERY = config('QUOTA_ALERT_ON_RECOVERY', default=True, cast=bool)
# Cheap models used only for the health probe (not for analysis). All are
# OpenRouter slugs where that provider is routed through OpenRouter — a bare
# vendor model id 404s there and would report a healthy key as MODEL_UNAVAILABLE.
QUOTA_PROBE_OPENAI_MODEL = config('QUOTA_PROBE_OPENAI_MODEL', default='openai/gpt-4o-mini')
QUOTA_PROBE_ANTHROPIC_MODEL = config('QUOTA_PROBE_ANTHROPIC_MODEL', default='anthropic/claude-sonnet-5')
QUOTA_PROBE_PERPLEXITY_MODEL = config('QUOTA_PROBE_PERPLEXITY_MODEL', default='perplexity/sonar')
QUOTA_PROBE_XAI_MODEL = config('QUOTA_PROBE_XAI_MODEL', default='grok-2-latest')
QUOTA_PROBE_DEEPSEEK_MODEL = config('QUOTA_PROBE_DEEPSEEK_MODEL', default='deepseek-chat')

# ==================== WEEKLY SWEEP COST GUARDS ====================
# A weekly sweep resets EVERY prompt/competitor and re-queries every enabled
# platform — roughly 10,800 LLM calls per run. These guard against paying for
# it more often than intended. See core/weekly_sweep_guard.py.
# Minimum days between two sweeps of the same type. The cron is every 7 days,
# so 6 leaves slack for jitter while still refusing an accidental manual re-run.
# 0 disables the cooldown.
WEEKLY_SWEEP_COOLDOWN_DAYS = config('WEEKLY_SWEEP_COOLDOWN_DAYS', default=6, cast=float)
# Probe provider keys before starting a sweep and refuse to start when NO
# enabled platform has a usable key (which would burn the queue for nothing and
# strand every prompt in INIT). A sweep still runs if even one platform is up.
WEEKLY_SWEEP_PREFLIGHT_ENABLED = config('WEEKLY_SWEEP_PREFLIGHT_ENABLED', default=True, cast=bool)

# ScrapingDog API Configuration (still used by misinformation crawler — /scrape endpoint)
SCRAPINGDOG_API_KEY = config('SCRAPINGDOG_API_KEY', default=None)

# DataBlue API Configuration (SEO keyword ranking / SERP — /v1/data/google/serp)
DATABLUE_API_KEY = config('DATABLUE_API_KEY', default='')
DATABLUE_NUM_RESULTS = config('DATABLUE_NUM_RESULTS', default=50, cast=int)
DATABLUE_CONCURRENCY = config('DATABLUE_CONCURRENCY', default=100, cast=int)
DATABLUE_TIMEOUT = config('DATABLUE_TIMEOUT', default=60, cast=int)
# /v1/data/google/serp endpoint (GET + query params). URL is overridable; PLATFORM
# is the default device when a keyword doesn't specify one; PAGES (1-5) overrides
# the num_results→pages derive (each page ~10 results and is billed separately);
# GOOGLE_DOMAIN forces a Google domain (else DataBlue auto-picks by country);
# ADVANCED=false uses the cheaper organic-focused mode (1 credit/page vs 2).
DATABLUE_API_URL = config('DATABLUE_API_URL', default='https://api.datablue.dev/v1/data/google/serp')
DATABLUE_PLATFORM = config('DATABLUE_PLATFORM', default='desktop')
DATABLUE_PAGES = config('DATABLUE_PAGES', default=0, cast=int)  # 0 = derive from NUM_RESULTS
DATABLUE_GOOGLE_DOMAIN = config('DATABLUE_GOOGLE_DOMAIN', default='')
DATABLUE_ADVANCED = config('DATABLUE_ADVANCED', default=False, cast=bool)

# ==================== EMAIL CONFIGURATION (MAILGUN HTTP API) ====================
# Mailgun HTTP API Configuration for report email delivery
MAILGUN_API_KEY = config('MAILGUN_API_KEY', default='')
MAILGUN_DOMAIN = config('MAILGUN_DOMAIN', default='')
MAILGUN_API_URL = config('MAILGUN_API_URL', default='https://api.mailgun.net/v3')

# Sender Email
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='LLM Monitor <noreply@sandbox.mailgun.org>'
)

# Frontend URL for email links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8080')

# Email timeout (seconds)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)
# ==================== END EMAIL CONFIGURATION ====================

# Backend API URL for report generation
BACKEND_API_URL = config('BACKEND_API_URL', default='http://localhost:8000')

# Platform tracking settings (lowercase keys, converted to proper case in code)
# Default: 'chatgpt,gemini' - enables both ChatGPT and Google Gemini
ENABLED_PLATFORMS = config('ENABLED_PLATFORMS', default='chatgpt,gemini', cast=lambda v: [p.strip() for p in v.split(',')])

# Celery settings (for background processing)
# Use a dedicated Redis DB index for engine tasks (e.g., DB 5)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/5')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/5')
CELERY_ACCEPT_CONTENT = [config('CELERY_ACCEPT_CONTENT', default='json')]
CELERY_TASK_SERIALIZER = config('CELERY_TASK_SERIALIZER', default='json')
CELERY_RESULT_SERIALIZER = config('CELERY_RESULT_SERIALIZER', default='json')
CELERY_TIMEZONE = TIME_ZONE

# Route SEO ranking tasks to a dedicated queue so user-triggered refreshes
# don't get stuck behind the prompt/competitor analytics backlog on the
# default queue (which can pile up to thousands of tasks during scheduler
# bursts). Other tasks keep their existing routing — the default 'celery'
# queue. A dedicated worker must be running with `-Q seo` for SEO tasks to
# be processed; see start-celery.sh.
CELERY_TASK_ROUTES = {
    'core.processing_tasks.process_seo_domain_task': {'queue': 'seo'},
    'core.processing_tasks.process_seo_keyword_task': {'queue': 'seo'},
    'core.processing_tasks.seo_rankings_daily_scheduler': {'queue': 'seo'},
}

# Auto-expire task results after 1 day (reduce Redis usage); set to None if not needed
from datetime import timedelta
CELERY_RESULT_EXPIRES = timedelta(days=config('CELERY_RESULT_EXPIRES_DAYS', default=1, cast=int))

# Celery Beat schedule: tick every 15 seconds to dispatch domain processing
# Row caps for the per-insight "top N" sections. These were hardcoded to 10,
# which made every report look permanently half-empty. Kept moderate and
# configurable rather than maximal because the consumers do NOT paginate or
# slice: reports/services/widget_data_fetcher renders every stored row into the
# report table, and the keywords endpoint returns all of them. Raising these
# directly grows report length, API payloads and the stored JSON.
GSC_TOP_ROWS_LIMIT = config('GSC_TOP_ROWS_LIMIT', default=100, cast=int)
GSC_COUNTRY_ROWS_LIMIT = config('GSC_COUNTRY_ROWS_LIMIT', default=25, cast=int)
GA_TOP_ROWS_LIMIT = config('GA_TOP_ROWS_LIMIT', default=100, cast=int)

CELERY_BEAT_SCHEDULE = {
    'domain-scheduler-tick-every-15s': {
        'task': 'core.processing_tasks.scheduler_tick',
        'schedule': config('CELERY_BEAT_SCHEDULE_DOMAIN', default=15.0, cast=float),
    },
    'prompt-analytics-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_prompt_analytics_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_PROMPT_ANALYTICS', default=15.0, cast=float),
    },
    'topic-analytics-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_topic_analytics_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_TOPIC_ANALYTICS', default=15.0, cast=float),
    },
    'integration-insights-scheduler-every-hour': {
        'task': 'core.processing_tasks.process_integration_insights_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_INTEGRATION_INSIGHTS', default=15.0, cast=float),  # Every 15 seconds for testing (change to 3600.0 for production)
    },
    'competitor-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_competitor_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_COMPETITOR', default=15.0, cast=float),
    },
    'report-email-scheduler-every-15s': {
        'task': 'core.processing_tasks.process_report_email_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_REPORT_EMAIL', default=15.0, cast=float),
    },
    # Weekly batch reprocessing (off-peak). Adjust crontab as needed.
    'weekly-prompts-batch': {
        'task': 'core.processing_tasks.schedule_weekly_prompt_batches',
        'schedule': crontab(day_of_week='sun', hour=0, minute=0),
    },
    'weekly-competitors-batch': {
        'task': 'core.processing_tasks.schedule_weekly_competitor_batches',
        'schedule': crontab(day_of_week='sun', hour=1, minute=0),
    },
    'cmsmanager-scheduler-every-60s': {
        'task': 'core.processing_tasks.process_cmsmanager_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_CMSMANAGER', default=60.0, cast=float),
    },
    # Daily SEO keyword ranking refresh at 2:00 AM
    'seo-rankings-daily-refresh': {
        'task': 'core.processing_tasks.seo_rankings_daily_scheduler',
        'schedule': crontab(hour=2, minute=0),
    },
    # Daily GA + GSC monthly insight scheduling for MOM/YOY in reports (runs at 1:00 AM)
    'monthly-insights-daily-schedule': {
        'task': 'core.processing_tasks.schedule_all_monthly_insights_task',
        'schedule': crontab(hour=1, minute=0),
    },
    # Daily refresh of the ROLLING 30-day GA + GSC window (2:30 AM). Without this
    # the rolling window stays frozen at whatever was fetched when the integration
    # was first connected — only the monthly records above ever refreshed.
    'rolling-insights-daily-refresh': {
        'task': 'core.processing_tasks.schedule_all_rolling_insights_task',
        'schedule': crontab(hour=2, minute=30),
    },
    # LLM credit monitor — checks hourly so a depleted provider is caught within
    # ~1h, and emails QUOTA_ALERT_RECIPIENTS ONLY when a key is out of credits
    # (or recovers). Transient errors/rate-limits never trigger mail.
    'llm-quota-alert': {
        'task': 'core.processing_tasks.quota_alert_scheduler',
        'schedule': config('CELERY_BEAT_SCHEDULE_QUOTA_ALERT', default=3600.0, cast=float),
    },
    # Daily Content Generation usage digest — emailed to each org's active
    # super-admins every night at 11:59 PM.
    'llm-daily-usage-digest': {
        'task': 'core.processing_tasks.send_daily_usage_digests',
        'schedule': crontab(hour=23, minute=59),
    },
}
