/**
 * /audit/<token> — where a lead lands, straight from the landing page form.
 *
 * Two audiences, one route:
 *
 *   the team (a signed-in admin) gets the plain report frame, for reading
 *   only — exports live on /audits/<id>, behind login, because a public link
 *   is shareable by definition and anything reachable from it is public;
 *
 *   a lead gets the app frame with every left-panel row locked (ProspectShell)
 *   and, if they arrived from the landing page, a way back to it. The report is
 *   read here; nothing is posted out and nothing leads into the app.
 */
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Loader2 } from "lucide-react";
import { apiClient } from "@/services/api";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { RunTimer, StageStrip, fmtDate } from "@/components/audits/AuditBits";
import { AuditReportView } from "@/components/audits/AuditReportView";
import { ProspectShell } from "@/components/audits/ProspectShell";
import type { PublicAudit as PublicAuditType } from "@/types/audit";

const POLL_MS = 5_000;

export default function PublicAudit() {
  const { token = "" } = useParams<{ token: string }>();
  const { toast } = useToast();
  const { user, isAuthenticated } = useAuth();
  // Anyone who is not the team is a lead, and gets the locked frame. Neither
  // audience downloads anything from this page any more; the difference is the
  // frame and the "email me the audit" card.
  const isTeam = isAuthenticated && (user?.role === "admin" || user?.role === "super_admin");
  const locked = !isTeam;

  const [audit, setAudit] = useState<PublicAuditType | null>(null);
  const [error, setError] = useState<{ status?: number; message: string } | null>(null);

  const load = useCallback(async () => {
    if (!token) return;
    try {
      setAudit(await apiClient.getPublicAudit(token));
      setError(null);
    } catch (e) {
      const err = e as Error & { status?: number };
      setError({ status: err.status, message: err.message });
    }
  }, [token]);

  useEffect(() => { load(); }, [load]);

  const live = audit?.status === "INIT" || audit?.status === "PROC";
  useEffect(() => {
    if (!live) return;
    const t = setInterval(load, POLL_MS);
    return () => clearInterval(t);
  }, [live, load]);

  useEffect(() => {
    document.title = audit?.brand_name ? `${audit.brand_name} — AI visibility audit · PromptMaxx` : "AI visibility audit · PromptMaxx";
    return () => { document.title = "PromptMaxx"; };
  }, [audit?.brand_name]);

  const teamShell = (children: React.ReactNode) => (
    <div className="min-h-screen bg-background text-foreground">
      <style>{`@media print { .no-print { display: none !important; } body { background: #fff; } }`}</style>
      <header className="no-print border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-3 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link to="/" className="text-lg font-bold tracking-tight text-primary">PROMPTMAXX</Link>
            <span className="text-sm text-muted-foreground">· Free AI visibility audit</span>
          </div>
          {/* Read-only. Exports are on /audits/<id>, behind login. */}
          <div className="flex items-center gap-2">
            {audit?.status === "DONE" && (
              <span className="hidden sm:inline text-xs text-muted-foreground">
                Public link{audit.expires_at ? ` · expires ${fmtDate(audit.expires_at)}` : ""} · {audit.opens} open{audit.opens === 1 ? "" : "s"}
              </span>
            )}
          </div>
        </div>
      </header>
      <main className="mx-auto max-w-6xl px-6 py-8">{children}</main>
      <footer className="no-print border-t border-border">
        <div className="mx-auto max-w-6xl px-6 py-6 text-xs text-muted-foreground flex flex-wrap justify-between gap-2">
          <span>Generated by PromptMaxx · AI search visibility and content strategy</span>
          <Link to="/signin" className="hover:text-foreground">Sign in</Link>
        </div>
      </footer>
    </div>
  );

  /** A visitor who arrived from the landing page gets an explicit way back.
   *  Browser-back already works (the landing page redirects rather than
   *  replaces), but leaving the only exit to a browser chrome button is not an
   *  exit a visitor can see. Absent for audits the team started by hand. */
  const backHome = audit?.landing_url ? (
    <div className="no-print pt-2">
      <Button variant="outline" asChild>
        <a href={audit.landing_url}>
          <ArrowLeft className="h-4 w-4 mr-2" />Back to {new URL(audit.landing_url).hostname.replace(/^www\./, "")}
        </a>
      </Button>
    </div>
  ) : null;

  const shell = (children: React.ReactNode) =>
    locked ? <ProspectShell host={audit?.host}>{children}</ProspectShell> : teamShell(children);

  if (error) {
    return shell(
      <div className="py-24 text-center">
        <h1 className="text-2xl font-bold">{error.status === 404 ? "This audit link is no longer available" : "Could not load this audit"}</h1>
        <p className="text-muted-foreground mt-2">
          {error.status === 404 ? "Public reports expire after a while unless they are claimed. Run a new audit to get a fresh one." : error.message}
        </p>
      </div>,
    );
  }
  if (!audit) {
    return shell(<div className="py-24 flex justify-center text-muted-foreground"><Loader2 className="h-6 w-6 animate-spin" /></div>);
  }

  if (audit.status === "FAIL") {
    return shell(
      <div className="py-24 text-center">
        <h1 className="text-2xl font-bold">We couldn't finish the audit of {audit.host}</h1>
        <p className="text-muted-foreground mt-2">{audit.error}</p>
      </div>,
    );
  }

  if (live) {
    const engines = audit.stage_detail?.engines as { done?: number; total?: number } | undefined;
    return shell(
      <div className="space-y-6">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">AI visibility audit</p>
          <h1 className="text-3xl font-bold tracking-tight mt-1">Auditing {audit.host}</h1>
          <p className="text-muted-foreground mt-1">
            {audit.seo_enabled ? "Seven stages" : "Six stages"} · this page updates itself, so you can leave it open.
          </p>
        </div>
        <div className="rounded-lg border border-border p-5 space-y-4">
          <div className="flex items-center justify-between text-sm">
            <span className="font-medium">{audit.stage_label || "Queued"}{engines?.total ? ` · ${engines.done ?? 0} / ${engines.total} answers` : ""}</span>
            <span className="flex items-center gap-3">
              <RunTimer startedAt={audit.created_at} finishedAt={audit.completed_at} running seoEnabled={audit.seo_enabled} />
              <span className="text-muted-foreground tabular-nums">{audit.progress}%</span>
            </span>
          </div>
          <Progress value={audit.progress} className="h-2" />
          <StageStrip status={audit.status} stage={audit.stage} stageDetail={audit.stage_detail || {}} seoEnabled={audit.seo_enabled} />
        </div>
        {audit.brand_name && (
          <div className="rounded-lg border border-border p-5">
            <p className="text-sm font-semibold mb-2">Profile · detected</p>
            <dl className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
              <div><dt className="text-xs text-muted-foreground">Brand</dt><dd className="font-medium">{audit.brand_name}</dd></div>
              <div><dt className="text-xs text-muted-foreground">Industry</dt><dd className="font-medium">{audit.industry || "—"}</dd></div>
              <div><dt className="text-xs text-muted-foreground">Stack</dt><dd className="font-medium">{audit.tech_stack.join(" · ") || "—"}</dd></div>
              <div><dt className="text-xs text-muted-foreground">Competitors</dt><dd className="font-medium">{audit.competitors.map((c) => c.name).join(" · ") || "—"}</dd></div>
            </dl>
          </div>
        )}
      </div>,
    );
  }

  return shell(
    <div className="space-y-10">
      <AuditReportView audit={audit} />
      {locked && backHome}
    </div>,
  );
}
