# Generated by Django 6.0.2 on 2026-02-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0002_internal_link_map'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoKeywordRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', help_text='Device type: desktop or mobile', max_length=10)),
                ('rank_now', models.IntegerField(default=0, help_text='Current rank position (0 = not ranked)')),
                ('top_rank', models.IntegerField(blank=True, help_text='Best rank ever achieved', null=True)),
                ('rank_since_start', models.IntegerField(default=0, help_text='Rank when keyword was first added')),
                ('day_val', models.IntegerField(default=0, help_text='Rank change vs 1 day ago (absolute)')),
                ('day_mark', models.CharField(default='-', help_text='up/down/-', max_length=5)),
                ('week_val', models.IntegerField(default=0, help_text='Rank change vs 7 days ago')),
                ('week_mark', models.CharField(default='-', max_length=5)),
                ('half_month_val', models.IntegerField(default=0, help_text='Rank change vs 15 days ago')),
                ('half_month_mark', models.CharField(default='-', max_length=5)),
                ('month_val', models.IntegerField(default=0, help_text='Rank change vs 30 days ago')),
                ('month_mark', models.CharField(default='-', max_length=5)),
                ('status_from_start', models.CharField(default='-', help_text='up/down/- since start', max_length=5)),
                ('featured_snippet', models.BooleanField(default=False)),
                ('knowledge_panel', models.BooleanField(default=False)),
                ('ads', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('total_rating', models.CharField(blank=True, default='-', max_length=5)),
                ('total_review', models.CharField(blank=True, default='-', max_length=15)),
                ('snippets_details', models.JSONField(blank=True, default=dict, help_text='Full SERP feature data')),
                ('keyword_snippet', models.JSONField(blank=True, default=dict, help_text='Today and best snippet: {tdy: {}, best: {}}')),
                ('gsc_clicks', models.IntegerField(default=0)),
                ('gsc_impressions', models.IntegerField(default=0)),
                ('site_url', models.CharField(blank=True, default='', max_length=500)),
                ('target_url', models.CharField(blank=True, default='', max_length=500)),
                ('search_results', models.CharField(blank=True, default='-', max_length=50)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(default='google.com', max_length=20)),
                ('isocode', models.CharField(default='us', max_length=5)),
                ('language_code', models.CharField(default='en', max_length=8)),
                ('geo_target', models.CharField(blank=True, default='', max_length=255)),
                ('geo_target_uule', models.CharField(blank=True, default='', max_length=500)),
                ('crawl_url', models.TextField(blank=True, default='')),
                ('auto_call_status', models.CharField(choices=[('avail', 'Available'), ('busy', 'Busy'), ('load', 'Loading'), ('read', 'Reading'), ('done', 'Done'), ('fail', 'Failed')], default='avail', help_text='Engine processing status', max_length=5)),
                ('auto_refresh_count', models.IntegerField(default=0)),
                ('manual_call_status', models.BooleanField(default=False)),
                ('last_ranked_date', models.DateTimeField(blank=True, null=True)),
                ('cannibalisation', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Domain this ranking belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seo_keyword_ranks', to='domains.domain')),
                ('keyword', models.ForeignKey(help_text='Link to the existing Promptmaxx keyword', on_delete=django.db.models.deletion.CASCADE, related_name='seo_ranks', to='keywords.keyword')),
            ],
            options={
                'verbose_name': 'SEO Keyword Rank',
                'verbose_name_plural': 'SEO Keyword Ranks',
                'db_table': 'seo_keyword_ranks',
            },
        ),
        migrations.CreateModel(
            name='SeoRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.IntegerField(help_text='Rank position on this date (0 = not ranked)')),
                ('snapshot_date', models.DateField(help_text='Date of this rank snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='seo_rankings.seokeywordrank')),
            ],
            options={
                'verbose_name': 'SEO Rank History',
                'verbose_name_plural': 'SEO Rank Histories',
                'db_table': 'seo_rank_history',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='SeoSerpFeatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_snippet_url_list', models.JSONField(blank=True, default=list)),
                ('featured_snippet_history', models.JSONField(blank=True, default=dict)),
                ('new_featured_snippet_date', models.DateTimeField(blank=True, null=True)),
                ('ad_snippet_url_list', models.JSONField(blank=True, default=list)),
                ('ad_snippet_history', models.JSONField(blank=True, default=dict)),
                ('new_ad_snippet_date', models.DateTimeField(blank=True, null=True)),
                ('url_status', models.CharField(default='CMN', max_length=5)),
                ('other_history', models.JSONField(blank=True, default=dict)),
                ('comp_today', models.JSONField(blank=True, default=dict)),
                ('ratings_changed_date', models.DateTimeField(blank=True, null=True)),
                ('top_ratings', models.CharField(default='-', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('seo_keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_feature_history', to='seo_rankings.seokeywordrank')),
            ],
            options={
                'verbose_name': 'SEO SERP Feature History',
                'verbose_name_plural': 'SEO SERP Feature Histories',
                'db_table': 'seo_serp_feature_history',
            },
        ),
        migrations.CreateModel(
            name='SeoDomainDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_meter', models.DecimalField(decimal_places=2, default=0.0, help_text='Rankmax score: weighted score 0-100', max_digits=8)),
                ('top_score', models.DecimalField(blank=True, decimal_places=2, help_text='Best Rankmax score ever achieved', max_digits=8, null=True)),
                ('improved_count', models.IntegerField(default=0)),
                ('declined_count', models.IntegerField(default=0)),
                ('no_change_count', models.IntegerField(default=0)),
                ('activity_level', models.DecimalField(decimal_places=2, default=0.0, help_text='((improved - declined) / total) * 100', max_digits=8)),
                ('top_1_count', models.IntegerField(default=0)),
                ('top_3_count', models.IntegerField(default=0)),
                ('top_10_count', models.IntegerField(default=0)),
                ('top_50_count', models.IntegerField(default=0)),
                ('top_100_count', models.IntegerField(default=0)),
                ('not_ranked_count', models.IntegerField(default=0)),
                ('desktop_count', models.IntegerField(default=0)),
                ('mobile_count', models.IntegerField(default=0)),
                ('total_keywords', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField(help_text='Date of this metrics snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_daily_metrics', to='domains.domain')),
            ],
            options={
                'verbose_name': 'SEO Domain Daily Metrics',
                'verbose_name_plural': 'SEO Domain Daily Metrics',
                'db_table': 'seo_domain_daily_metrics',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['domain', '-snapshot_date'], name='seo_domain__domain__4c97c1_idx')],
                'unique_together': {('domain', 'snapshot_date')},
            },
        ),
        migrations.AddIndex(
            model_name='seokeywordrank',
            index=models.Index(fields=['domain', 'platform', '-rank_now'], name='seo_keyword_domain__a34710_idx'),
        ),
        migrations.AddIndex(
            model_name='seokeywordrank',
            index=models.Index(fields=['domain', 'auto_call_status'], name='seo_keyword_domain__621370_idx'),
        ),
        migrations.AddIndex(
            model_name='seokeywordrank',
            index=models.Index(fields=['domain', '-last_ranked_date'], name='seo_keyword_domain__cee82a_idx'),
        ),
        migrations.AddIndex(
            model_name='seokeywordrank',
            index=models.Index(fields=['keyword', 'platform'], name='seo_keyword_keyword_43fe0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seokeywordrank',
            unique_together={('keyword', 'domain', 'platform')},
        ),
        migrations.AddIndex(
            model_name='seorankhistory',
            index=models.Index(fields=['seo_keyword_rank', '-snapshot_date'], name='seo_rank_hi_seo_key_cc4071_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seorankhistory',
            unique_together={('seo_keyword_rank', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='seoserpfeaturehistory',
            index=models.Index(fields=['seo_keyword_rank', '-modified_at'], name='seo_serp_fe_seo_key_b60627_idx'),
        ),
    ]
