# Generated by Django 6.0.2 on 2026-02-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='ads_others_above',
            field=models.IntegerField(default=0, help_text="Others' ads: above fold only"),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='ads_others_above_below',
            field=models.IntegerField(default=0, help_text="Others' ads: above & below fold"),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='ads_others_below',
            field=models.IntegerField(default=0, help_text="Others' ads: below fold only"),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='ads_you_above',
            field=models.IntegerField(default=0, help_text='Your ads: above fold only'),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='ads_you_above_below',
            field=models.IntegerField(default=0, help_text='Your ads: above & below fold'),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='ads_you_below',
            field=models.IntegerField(default=0, help_text='Your ads: below fold only'),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='rating_0_2',
            field=models.IntegerField(default=0, help_text='Keywords with 0-2 star ratings'),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='rating_2_4',
            field=models.IntegerField(default=0, help_text='Keywords with 2-4 star ratings'),
        ),
        migrations.AddField(
            model_name='seodomaindailymetrics',
            name='rating_4_5',
            field=models.IntegerField(default=0, help_text='Keywords with 4-5 star ratings'),
        ),
    ]
