# Generated by Django 6.0.2 on 2026-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_rankings', '0002_seodomaindailymetrics_ads_others_above_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seokeywordrank',
            name='favour',
            field=models.IntegerField(default=0, help_text='0=unfavorite, 1=favorite'),
        ),
        migrations.AddField(
            model_name='seokeywordrank',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings'),
        ),
    ]
