# Generated by Django 6.0.2 on 2026-03-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_internal_link_map'),
        ('seo_rankings', '0003_add_tags_and_favour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoCompetitorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INIT', 'Not started'), ('SCHD', 'Analyzing'), ('COMP', 'Completed'), ('FAIL', 'Failed')], default='INIT', max_length=5)),
                ('total_keywords', models.IntegerField(default=0)),
                ('unique_domains', models.IntegerField(default=0)),
                ('total_domain_hits', models.IntegerField(default=0)),
                ('analysis_json', models.JSONField(blank=True, default=dict, help_text='Aggregated data: {domains: {domain: count}, keys: {domain: [kw_ids]}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_analyses', to='domains.domain')),
            ],
            options={
                'db_table': 'seo_competitor_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoCompetitorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_domain', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_projects', to='domains.domain')),
            ],
            options={
                'db_table': 'seo_competitor_project',
                'ordering': ['competitor_domain'],
                'unique_together': {('domain', 'competitor_domain')},
            },
        ),
        migrations.CreateModel(
            name='SeoCompetitorKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.TextField()),
                ('our_rank', models.IntegerField(default=0)),
                ('their_rank', models.IntegerField(default=0)),
                ('our_url', models.TextField(blank=True, default='')),
                ('their_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_kw_rows', to='domains.domain')),
                ('seo_keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_kw_rows', to='seo_rankings.seokeywordrank')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='seo_rankings.seocompetitorproject')),
            ],
            options={
                'db_table': 'seo_competitor_keyword',
                'ordering': ['our_rank', 'keyword_text'],
                'unique_together': {('competitor', 'seo_keyword_rank')},
            },
        ),
    ]
