# Generated by Django 6.0.2 on 2026-03-19 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_add_reference_document_model'),
        ('seo_rankings', '0005_add_seo_report_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoKeywordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('note_date', models.DateField(help_text='Date the note refers to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Keyword Note',
                'verbose_name_plural': 'SEO Keyword Notes',
                'db_table': 'seo_keyword_notes',
                'ordering': ['-note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoKeywordVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_volume', models.IntegerField(default=0, help_text='Average monthly search volume')),
                ('top_volume', models.IntegerField(default=0, help_text='Highest monthly volume in the period')),
                ('low_volume', models.IntegerField(default=0, help_text='Lowest monthly volume in the period')),
                ('comp_level', models.CharField(default='-', help_text='Competition level: Low/Medium/High/UNSPECIFIED', max_length=20)),
                ('comp_index', models.CharField(default='-', help_text='Competition index: 0-100 or -', max_length=10)),
                ('month_wise_volume', models.JSONField(blank=True, default=list, help_text='Array of monthly search volumes, e.g. [20, 30, 30, 30, 210, 260]')),
                ('month_labels', models.JSONField(blank=True, default=list, help_text="Array of month labels, e.g. ['June', 'August', 'October', ...]")),
                ('status', models.CharField(default='new', help_text='Volume fetch status: new/done/fail', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Keyword Volume',
                'verbose_name_plural': 'SEO Keyword Volumes',
                'db_table': 'seo_keyword_volumes',
            },
        ),
        migrations.RenameIndex(
            model_name='seoreportsheet',
            new_name='seo_report__domain__38456f_idx',
            old_name='seo_report_sh_domain__6e9a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='seoreportsheet',
            new_name='seo_report__domain__e3b788_idx',
            old_name='seo_report_sh_domain__8f2b1a_idx',
        ),
        migrations.AddField(
            model_name='seokeywordnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_keyword_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seokeywordnote',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_keyword_notes', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='seokeywordnote',
            name='seo_keyword_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='seo_rankings.seokeywordrank'),
        ),
        migrations.AddField(
            model_name='seokeywordvolume',
            name='seo_keyword_rank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volume_data', to='seo_rankings.seokeywordrank'),
        ),
        migrations.AddIndex(
            model_name='seokeywordnote',
            index=models.Index(fields=['seo_keyword_rank', '-note_date'], name='seo_keyword_seo_key_456e2b_idx'),
        ),
    ]
