# Generated by Django 5.2 on 2026-06-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_alter_brandlink_platform'),
        ('seo_rankings', '0010_seoreportsheet_summary_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoreportsheet',
            name='secondary_domain',
            field=models.ForeignKey(blank=True, help_text='Optional second domain whose GA/GSC (and other) data is pooled into this report. NULL = single-domain report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_report_sheets_as_secondary', to='domains.domain'),
        ),
    ]
