# Generated by Django 5.2 on 2026-06-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_seo_keyword_limit'),
        ('domains', '0007_alter_brandlink_platform'),
        ('seo_rankings', '0011_seoreportsheet_secondary_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSecondaryDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display host, e.g. blog.example.com', max_length=255)),
                ('url', models.CharField(help_text='Normalised URL, e.g. https://blog.example.com', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_secondary_subdomains_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Denormalised from the primary domain for scoping.', on_delete=django.db.models.deletion.CASCADE, related_name='seo_secondary_subdomains', to='authentication.organisation')),
                ('primary_domain', models.ForeignKey(help_text='The primary domain whose report this subdomain is combined into.', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_subdomains', to='domains.domain')),
            ],
            options={
                'verbose_name': 'SEO Secondary Subdomain',
                'verbose_name_plural': 'SEO Secondary Subdomains',
                'db_table': 'seo_secondary_domains',
                'ordering': ['-created_at'],
                'unique_together': {('primary_domain', 'url')},
            },
        ),
        # The secondary_domain FK now targets seo_secondary_domains instead of
        # domains. Existing values point at the old lightweight Domain rows, which
        # do NOT exist in the new table — clear them so the new FK constraint
        # validates. ("Migrate, don't delete": the old Domain rows are left intact;
        # affected reports simply revert to single-domain until reconnected.)
        migrations.RunSQL(
            sql='UPDATE seo_report_sheets SET secondary_domain_id = NULL WHERE secondary_domain_id IS NOT NULL;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='seoreportsheet',
            name='secondary_domain',
            field=models.ForeignKey(blank=True, help_text='Optional report-only secondary subdomain whose GA/GSC data is pooled into this report. NULL = single-domain report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_report_sheets_as_secondary', to='seo_rankings.seosecondarydomain'),
        ),
    ]
