# Generated by Django 5.2 on 2026-08-04 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_rankings', '0012_seosecondarydomain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_gstin', models.CharField(blank=True, default='', max_length=32)),
                ('company_state_name', models.CharField(blank=True, default='', max_length=64)),
                ('company_state_code', models.CharField(blank=True, default='', max_length=8)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice/')),
                ('invoice_prefix', models.CharField(blank=True, default='INV', max_length=16)),
                ('financial_year', models.CharField(blank=True, default='', max_length=16)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('hsn_sac', models.CharField(blank=True, default='', max_length=16)),
                ('tax_type', models.CharField(choices=[('IGST', 'IGST (inter-state)'), ('CGST_SGST', 'CGST + SGST (intra-state)')], default='IGST', max_length=16)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=64)),
                ('bank_branch_ifsc', models.CharField(blank=True, default='', max_length=255)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='invoice/')),
                ('footer_note', models.CharField(blank=True, default='This is a Computer Generated Invoice', max_length=255)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('reference_no', models.CharField(blank=True, default='', max_length=255)),
                ('other_references', models.CharField(blank=True, default='', max_length=255)),
                ('buyers_order_no', models.CharField(blank=True, default='', max_length=255)),
                ('dispatch_doc_no', models.CharField(blank=True, default='', max_length=255)),
                ('dispatched_through', models.CharField(blank=True, default='', max_length=255)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('terms_of_delivery', models.TextField(blank=True, default='')),
                ('buyers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
                'db_table': 'invoice_settings',
            },
        ),
    ]
