# Generated by Django 5.2 on 2026-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_rankings', '0013_invoicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='export_declaration',
            field=models.CharField(blank=True, default='SUPPLY MEANT FOR EXPORT/SUPPLY TO SEZ UNIT OR SEZ DEVELOPER FOR AUTHORISED OPERATIONS ON PAYMENT OF IGST', max_length=255),
        ),
    ]
