# Generated by Django 5.2 on 2026-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_rankings', '0014_invoicesettings_export_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('as_of', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fx_rates',
                'indexes': [models.Index(fields=['base', 'quote', 'as_of'], name='fx_rates_base_ea15a6_idx')],
                'unique_together': {('base', 'quote', 'as_of')},
            },
        ),
    ]
