# Generated by Django 5.2 on 2026-08-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_domain_commercial_profile'),
        ('keywords', '0001_initial'),
        ('seo_rankings', '0016_seobacklinksnapshot_seobacklinkreferringdomain_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seokeywordrank',
            unique_together={('keyword', 'domain', 'platform', 'language_code', 'region')},
        ),
    ]
